// Code generated by Kitex v0.15.4. DO NOT EDIT.

package userservice

import (
	"context"
	user "example_shop/kitex_gen/user"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Register(ctx context.Context, req *user.RegisterReq, callOptions ...callopt.Option) (r *user.RegisterResp, err error)
	Login(ctx context.Context, req *user.LoginReq, callOptions ...callopt.Option) (r *user.LoginResp, err error)
	VerifyRealName(ctx context.Context, req *user.VerifyRealNameReq, callOptions ...callopt.Option) (r *user.BaseResp, err error)
	GetUserInfo(ctx context.Context, req *user.GetUserInfoReq, callOptions ...callopt.Option) (r *user.GetUserInfoResp, err error)
	GetTrainDetail(ctx context.Context, req *user.GetTrainDetailReq, callOptions ...callopt.Option) (r *user.GetTrainDetailResp, err error)
	CreateOrder(ctx context.Context, req *user.CreateOrderReq, callOptions ...callopt.Option) (r *user.CreateOrderResp, err error)
	PayOrder(ctx context.Context, req *user.PayOrderReq, callOptions ...callopt.Option) (r *user.PayOrderResp, err error)
	ConfirmPay(ctx context.Context, req *user.ConfirmPayReq, callOptions ...callopt.Option) (r *user.ConfirmPayResp, err error)
	ChangeOrder(ctx context.Context, req *user.ChangeOrderReq, callOptions ...callopt.Option) (r *user.ChangeOrderResp, err error)
	CancelOrder(ctx context.Context, req *user.CancelOrderReq, callOptions ...callopt.Option) (r *user.BaseResp, err error)
	RefundOrder(ctx context.Context, req *user.RefundOrderReq, callOptions ...callopt.Option) (r *user.RefundOrderResp, err error)
	GetOrder(ctx context.Context, req *user.GetOrderReq, callOptions ...callopt.Option) (r *user.GetOrderResp, err error)
	ListOrders(ctx context.Context, req *user.ListOrdersReq, callOptions ...callopt.Option) (r *user.ListOrdersResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) Register(ctx context.Context, req *user.RegisterReq, callOptions ...callopt.Option) (r *user.RegisterResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Register(ctx, req)
}

func (p *kUserServiceClient) Login(ctx context.Context, req *user.LoginReq, callOptions ...callopt.Option) (r *user.LoginResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, req)
}

func (p *kUserServiceClient) VerifyRealName(ctx context.Context, req *user.VerifyRealNameReq, callOptions ...callopt.Option) (r *user.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.VerifyRealName(ctx, req)
}

func (p *kUserServiceClient) GetUserInfo(ctx context.Context, req *user.GetUserInfoReq, callOptions ...callopt.Option) (r *user.GetUserInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserInfo(ctx, req)
}

func (p *kUserServiceClient) GetTrainDetail(ctx context.Context, req *user.GetTrainDetailReq, callOptions ...callopt.Option) (r *user.GetTrainDetailResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetTrainDetail(ctx, req)
}

func (p *kUserServiceClient) CreateOrder(ctx context.Context, req *user.CreateOrderReq, callOptions ...callopt.Option) (r *user.CreateOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateOrder(ctx, req)
}

func (p *kUserServiceClient) PayOrder(ctx context.Context, req *user.PayOrderReq, callOptions ...callopt.Option) (r *user.PayOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PayOrder(ctx, req)
}

func (p *kUserServiceClient) ConfirmPay(ctx context.Context, req *user.ConfirmPayReq, callOptions ...callopt.Option) (r *user.ConfirmPayResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ConfirmPay(ctx, req)
}

func (p *kUserServiceClient) ChangeOrder(ctx context.Context, req *user.ChangeOrderReq, callOptions ...callopt.Option) (r *user.ChangeOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ChangeOrder(ctx, req)
}

func (p *kUserServiceClient) CancelOrder(ctx context.Context, req *user.CancelOrderReq, callOptions ...callopt.Option) (r *user.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CancelOrder(ctx, req)
}

func (p *kUserServiceClient) RefundOrder(ctx context.Context, req *user.RefundOrderReq, callOptions ...callopt.Option) (r *user.RefundOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RefundOrder(ctx, req)
}

func (p *kUserServiceClient) GetOrder(ctx context.Context, req *user.GetOrderReq, callOptions ...callopt.Option) (r *user.GetOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOrder(ctx, req)
}

func (p *kUserServiceClient) ListOrders(ctx context.Context, req *user.ListOrdersReq, callOptions ...callopt.Option) (r *user.ListOrdersResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListOrders(ctx, req)
}
