// Code generated by Kitex v0.15.4. DO NOT EDIT.

package userservice

import (
	"context"
	"errors"
	user "example_shop/kitex_gen/user"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Register": kitex.NewMethodInfo(
		registerHandler,
		newUserServiceRegisterArgs,
		newUserServiceRegisterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Login": kitex.NewMethodInfo(
		loginHandler,
		newUserServiceLoginArgs,
		newUserServiceLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"VerifyRealName": kitex.NewMethodInfo(
		verifyRealNameHandler,
		newUserServiceVerifyRealNameArgs,
		newUserServiceVerifyRealNameResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUserInfo": kitex.NewMethodInfo(
		getUserInfoHandler,
		newUserServiceGetUserInfoArgs,
		newUserServiceGetUserInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetTrainDetail": kitex.NewMethodInfo(
		getTrainDetailHandler,
		newUserServiceGetTrainDetailArgs,
		newUserServiceGetTrainDetailResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateOrder": kitex.NewMethodInfo(
		createOrderHandler,
		newUserServiceCreateOrderArgs,
		newUserServiceCreateOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"PayOrder": kitex.NewMethodInfo(
		payOrderHandler,
		newUserServicePayOrderArgs,
		newUserServicePayOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ConfirmPay": kitex.NewMethodInfo(
		confirmPayHandler,
		newUserServiceConfirmPayArgs,
		newUserServiceConfirmPayResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ChangeOrder": kitex.NewMethodInfo(
		changeOrderHandler,
		newUserServiceChangeOrderArgs,
		newUserServiceChangeOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CancelOrder": kitex.NewMethodInfo(
		cancelOrderHandler,
		newUserServiceCancelOrderArgs,
		newUserServiceCancelOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RefundOrder": kitex.NewMethodInfo(
		refundOrderHandler,
		newUserServiceRefundOrderArgs,
		newUserServiceRefundOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetOrder": kitex.NewMethodInfo(
		getOrderHandler,
		newUserServiceGetOrderArgs,
		newUserServiceGetOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListOrders": kitex.NewMethodInfo(
		listOrdersHandler,
		newUserServiceListOrdersArgs,
		newUserServiceListOrdersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	userServiceServiceInfo                = NewServiceInfo()
	userServiceServiceInfoForClient       = NewServiceInfoForClient()
	userServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return userServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "UserService"
	handlerType := (*user.UserService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "user",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.4",
		Extra:           extra,
	}
	return svcInfo
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceRegisterArgs)
	realResult := result.(*user.UserServiceRegisterResult)
	success, err := handler.(user.UserService).Register(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceRegisterArgs() interface{} {
	return user.NewUserServiceRegisterArgs()
}

func newUserServiceRegisterResult() interface{} {
	return user.NewUserServiceRegisterResult()
}

func loginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceLoginArgs)
	realResult := result.(*user.UserServiceLoginResult)
	success, err := handler.(user.UserService).Login(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceLoginArgs() interface{} {
	return user.NewUserServiceLoginArgs()
}

func newUserServiceLoginResult() interface{} {
	return user.NewUserServiceLoginResult()
}

func verifyRealNameHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceVerifyRealNameArgs)
	realResult := result.(*user.UserServiceVerifyRealNameResult)
	success, err := handler.(user.UserService).VerifyRealName(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceVerifyRealNameArgs() interface{} {
	return user.NewUserServiceVerifyRealNameArgs()
}

func newUserServiceVerifyRealNameResult() interface{} {
	return user.NewUserServiceVerifyRealNameResult()
}

func getUserInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceGetUserInfoArgs)
	realResult := result.(*user.UserServiceGetUserInfoResult)
	success, err := handler.(user.UserService).GetUserInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetUserInfoArgs() interface{} {
	return user.NewUserServiceGetUserInfoArgs()
}

func newUserServiceGetUserInfoResult() interface{} {
	return user.NewUserServiceGetUserInfoResult()
}

func getTrainDetailHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceGetTrainDetailArgs)
	realResult := result.(*user.UserServiceGetTrainDetailResult)
	success, err := handler.(user.UserService).GetTrainDetail(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetTrainDetailArgs() interface{} {
	return user.NewUserServiceGetTrainDetailArgs()
}

func newUserServiceGetTrainDetailResult() interface{} {
	return user.NewUserServiceGetTrainDetailResult()
}

func createOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceCreateOrderArgs)
	realResult := result.(*user.UserServiceCreateOrderResult)
	success, err := handler.(user.UserService).CreateOrder(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceCreateOrderArgs() interface{} {
	return user.NewUserServiceCreateOrderArgs()
}

func newUserServiceCreateOrderResult() interface{} {
	return user.NewUserServiceCreateOrderResult()
}

func payOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServicePayOrderArgs)
	realResult := result.(*user.UserServicePayOrderResult)
	success, err := handler.(user.UserService).PayOrder(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServicePayOrderArgs() interface{} {
	return user.NewUserServicePayOrderArgs()
}

func newUserServicePayOrderResult() interface{} {
	return user.NewUserServicePayOrderResult()
}

func confirmPayHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceConfirmPayArgs)
	realResult := result.(*user.UserServiceConfirmPayResult)
	success, err := handler.(user.UserService).ConfirmPay(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceConfirmPayArgs() interface{} {
	return user.NewUserServiceConfirmPayArgs()
}

func newUserServiceConfirmPayResult() interface{} {
	return user.NewUserServiceConfirmPayResult()
}

func changeOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceChangeOrderArgs)
	realResult := result.(*user.UserServiceChangeOrderResult)
	success, err := handler.(user.UserService).ChangeOrder(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceChangeOrderArgs() interface{} {
	return user.NewUserServiceChangeOrderArgs()
}

func newUserServiceChangeOrderResult() interface{} {
	return user.NewUserServiceChangeOrderResult()
}

func cancelOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceCancelOrderArgs)
	realResult := result.(*user.UserServiceCancelOrderResult)
	success, err := handler.(user.UserService).CancelOrder(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceCancelOrderArgs() interface{} {
	return user.NewUserServiceCancelOrderArgs()
}

func newUserServiceCancelOrderResult() interface{} {
	return user.NewUserServiceCancelOrderResult()
}

func refundOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceRefundOrderArgs)
	realResult := result.(*user.UserServiceRefundOrderResult)
	success, err := handler.(user.UserService).RefundOrder(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceRefundOrderArgs() interface{} {
	return user.NewUserServiceRefundOrderArgs()
}

func newUserServiceRefundOrderResult() interface{} {
	return user.NewUserServiceRefundOrderResult()
}

func getOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceGetOrderArgs)
	realResult := result.(*user.UserServiceGetOrderResult)
	success, err := handler.(user.UserService).GetOrder(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetOrderArgs() interface{} {
	return user.NewUserServiceGetOrderArgs()
}

func newUserServiceGetOrderResult() interface{} {
	return user.NewUserServiceGetOrderResult()
}

func listOrdersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceListOrdersArgs)
	realResult := result.(*user.UserServiceListOrdersResult)
	success, err := handler.(user.UserService).ListOrders(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceListOrdersArgs() interface{} {
	return user.NewUserServiceListOrdersArgs()
}

func newUserServiceListOrdersResult() interface{} {
	return user.NewUserServiceListOrdersResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Register(ctx context.Context, req *user.RegisterReq) (r *user.RegisterResp, err error) {
	var _args user.UserServiceRegisterArgs
	_args.Req = req
	var _result user.UserServiceRegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Login(ctx context.Context, req *user.LoginReq) (r *user.LoginResp, err error) {
	var _args user.UserServiceLoginArgs
	_args.Req = req
	var _result user.UserServiceLoginResult
	if err = p.c.Call(ctx, "Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) VerifyRealName(ctx context.Context, req *user.VerifyRealNameReq) (r *user.BaseResp, err error) {
	var _args user.UserServiceVerifyRealNameArgs
	_args.Req = req
	var _result user.UserServiceVerifyRealNameResult
	if err = p.c.Call(ctx, "VerifyRealName", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserInfo(ctx context.Context, req *user.GetUserInfoReq) (r *user.GetUserInfoResp, err error) {
	var _args user.UserServiceGetUserInfoArgs
	_args.Req = req
	var _result user.UserServiceGetUserInfoResult
	if err = p.c.Call(ctx, "GetUserInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetTrainDetail(ctx context.Context, req *user.GetTrainDetailReq) (r *user.GetTrainDetailResp, err error) {
	var _args user.UserServiceGetTrainDetailArgs
	_args.Req = req
	var _result user.UserServiceGetTrainDetailResult
	if err = p.c.Call(ctx, "GetTrainDetail", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateOrder(ctx context.Context, req *user.CreateOrderReq) (r *user.CreateOrderResp, err error) {
	var _args user.UserServiceCreateOrderArgs
	_args.Req = req
	var _result user.UserServiceCreateOrderResult
	if err = p.c.Call(ctx, "CreateOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) PayOrder(ctx context.Context, req *user.PayOrderReq) (r *user.PayOrderResp, err error) {
	var _args user.UserServicePayOrderArgs
	_args.Req = req
	var _result user.UserServicePayOrderResult
	if err = p.c.Call(ctx, "PayOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ConfirmPay(ctx context.Context, req *user.ConfirmPayReq) (r *user.ConfirmPayResp, err error) {
	var _args user.UserServiceConfirmPayArgs
	_args.Req = req
	var _result user.UserServiceConfirmPayResult
	if err = p.c.Call(ctx, "ConfirmPay", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ChangeOrder(ctx context.Context, req *user.ChangeOrderReq) (r *user.ChangeOrderResp, err error) {
	var _args user.UserServiceChangeOrderArgs
	_args.Req = req
	var _result user.UserServiceChangeOrderResult
	if err = p.c.Call(ctx, "ChangeOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CancelOrder(ctx context.Context, req *user.CancelOrderReq) (r *user.BaseResp, err error) {
	var _args user.UserServiceCancelOrderArgs
	_args.Req = req
	var _result user.UserServiceCancelOrderResult
	if err = p.c.Call(ctx, "CancelOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RefundOrder(ctx context.Context, req *user.RefundOrderReq) (r *user.RefundOrderResp, err error) {
	var _args user.UserServiceRefundOrderArgs
	_args.Req = req
	var _result user.UserServiceRefundOrderResult
	if err = p.c.Call(ctx, "RefundOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetOrder(ctx context.Context, req *user.GetOrderReq) (r *user.GetOrderResp, err error) {
	var _args user.UserServiceGetOrderArgs
	_args.Req = req
	var _result user.UserServiceGetOrderResult
	if err = p.c.Call(ctx, "GetOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListOrders(ctx context.Context, req *user.ListOrdersReq) (r *user.ListOrdersResp, err error) {
	var _args user.UserServiceListOrdersArgs
	_args.Req = req
	var _result user.UserServiceListOrdersResult
	if err = p.c.Call(ctx, "ListOrders", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
