// Code generated by Kitex v0.15.4. DO NOT EDIT.

package orderservice

import (
	"context"
	common "example_shop/kitex_gen/common"
	orderapi "example_shop/kitex_gen/orderapi"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateOrder(ctx context.Context, req *orderapi.CreateOrderReq, callOptions ...callopt.Option) (r *orderapi.CreateOrderResp, err error)
	PayOrder(ctx context.Context, req *orderapi.PayOrderReq, callOptions ...callopt.Option) (r *orderapi.PayOrderResp, err error)
	ConfirmPay(ctx context.Context, req *orderapi.ConfirmPayReq, callOptions ...callopt.Option) (r *orderapi.ConfirmPayResp, err error)
	ChangeOrder(ctx context.Context, req *orderapi.ChangeOrderReq, callOptions ...callopt.Option) (r *orderapi.ChangeOrderResp, err error)
	CancelOrder(ctx context.Context, req *orderapi.CancelOrderReq, callOptions ...callopt.Option) (r *common.BaseResp, err error)
	RefundOrder(ctx context.Context, req *orderapi.RefundOrderReq, callOptions ...callopt.Option) (r *orderapi.RefundOrderResp, err error)
	GetOrder(ctx context.Context, req *orderapi.GetOrderReq, callOptions ...callopt.Option) (r *orderapi.GetOrderResp, err error)
	ListOrders(ctx context.Context, req *orderapi.ListOrdersReq, callOptions ...callopt.Option) (r *orderapi.ListOrdersResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kOrderServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kOrderServiceClient struct {
	*kClient
}

func (p *kOrderServiceClient) CreateOrder(ctx context.Context, req *orderapi.CreateOrderReq, callOptions ...callopt.Option) (r *orderapi.CreateOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateOrder(ctx, req)
}

func (p *kOrderServiceClient) PayOrder(ctx context.Context, req *orderapi.PayOrderReq, callOptions ...callopt.Option) (r *orderapi.PayOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PayOrder(ctx, req)
}

func (p *kOrderServiceClient) ConfirmPay(ctx context.Context, req *orderapi.ConfirmPayReq, callOptions ...callopt.Option) (r *orderapi.ConfirmPayResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ConfirmPay(ctx, req)
}

func (p *kOrderServiceClient) ChangeOrder(ctx context.Context, req *orderapi.ChangeOrderReq, callOptions ...callopt.Option) (r *orderapi.ChangeOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ChangeOrder(ctx, req)
}

func (p *kOrderServiceClient) CancelOrder(ctx context.Context, req *orderapi.CancelOrderReq, callOptions ...callopt.Option) (r *common.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CancelOrder(ctx, req)
}

func (p *kOrderServiceClient) RefundOrder(ctx context.Context, req *orderapi.RefundOrderReq, callOptions ...callopt.Option) (r *orderapi.RefundOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RefundOrder(ctx, req)
}

func (p *kOrderServiceClient) GetOrder(ctx context.Context, req *orderapi.GetOrderReq, callOptions ...callopt.Option) (r *orderapi.GetOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOrder(ctx, req)
}

func (p *kOrderServiceClient) ListOrders(ctx context.Context, req *orderapi.ListOrdersReq, callOptions ...callopt.Option) (r *orderapi.ListOrdersResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListOrders(ctx, req)
}
