// Code generated by Kitex v0.15.4. DO NOT EDIT.

package orderservice

import (
	"context"
	"errors"
	common "example_shop/kitex_gen/common"
	orderapi "example_shop/kitex_gen/orderapi"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateOrder": kitex.NewMethodInfo(
		createOrderHandler,
		newOrderServiceCreateOrderArgs,
		newOrderServiceCreateOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"PayOrder": kitex.NewMethodInfo(
		payOrderHandler,
		newOrderServicePayOrderArgs,
		newOrderServicePayOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ConfirmPay": kitex.NewMethodInfo(
		confirmPayHandler,
		newOrderServiceConfirmPayArgs,
		newOrderServiceConfirmPayResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ChangeOrder": kitex.NewMethodInfo(
		changeOrderHandler,
		newOrderServiceChangeOrderArgs,
		newOrderServiceChangeOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CancelOrder": kitex.NewMethodInfo(
		cancelOrderHandler,
		newOrderServiceCancelOrderArgs,
		newOrderServiceCancelOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RefundOrder": kitex.NewMethodInfo(
		refundOrderHandler,
		newOrderServiceRefundOrderArgs,
		newOrderServiceRefundOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetOrder": kitex.NewMethodInfo(
		getOrderHandler,
		newOrderServiceGetOrderArgs,
		newOrderServiceGetOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListOrders": kitex.NewMethodInfo(
		listOrdersHandler,
		newOrderServiceListOrdersArgs,
		newOrderServiceListOrdersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	orderServiceServiceInfo                = NewServiceInfo()
	orderServiceServiceInfoForClient       = NewServiceInfoForClient()
	orderServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return orderServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return orderServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return orderServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "OrderService"
	handlerType := (*orderapi.OrderService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "orderapi",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.4",
		Extra:           extra,
	}
	return svcInfo
}

func createOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*orderapi.OrderServiceCreateOrderArgs)
	realResult := result.(*orderapi.OrderServiceCreateOrderResult)
	success, err := handler.(orderapi.OrderService).CreateOrder(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOrderServiceCreateOrderArgs() interface{} {
	return orderapi.NewOrderServiceCreateOrderArgs()
}

func newOrderServiceCreateOrderResult() interface{} {
	return orderapi.NewOrderServiceCreateOrderResult()
}

func payOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*orderapi.OrderServicePayOrderArgs)
	realResult := result.(*orderapi.OrderServicePayOrderResult)
	success, err := handler.(orderapi.OrderService).PayOrder(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOrderServicePayOrderArgs() interface{} {
	return orderapi.NewOrderServicePayOrderArgs()
}

func newOrderServicePayOrderResult() interface{} {
	return orderapi.NewOrderServicePayOrderResult()
}

func confirmPayHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*orderapi.OrderServiceConfirmPayArgs)
	realResult := result.(*orderapi.OrderServiceConfirmPayResult)
	success, err := handler.(orderapi.OrderService).ConfirmPay(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOrderServiceConfirmPayArgs() interface{} {
	return orderapi.NewOrderServiceConfirmPayArgs()
}

func newOrderServiceConfirmPayResult() interface{} {
	return orderapi.NewOrderServiceConfirmPayResult()
}

func changeOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*orderapi.OrderServiceChangeOrderArgs)
	realResult := result.(*orderapi.OrderServiceChangeOrderResult)
	success, err := handler.(orderapi.OrderService).ChangeOrder(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOrderServiceChangeOrderArgs() interface{} {
	return orderapi.NewOrderServiceChangeOrderArgs()
}

func newOrderServiceChangeOrderResult() interface{} {
	return orderapi.NewOrderServiceChangeOrderResult()
}

func cancelOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*orderapi.OrderServiceCancelOrderArgs)
	realResult := result.(*orderapi.OrderServiceCancelOrderResult)
	success, err := handler.(orderapi.OrderService).CancelOrder(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOrderServiceCancelOrderArgs() interface{} {
	return orderapi.NewOrderServiceCancelOrderArgs()
}

func newOrderServiceCancelOrderResult() interface{} {
	return orderapi.NewOrderServiceCancelOrderResult()
}

func refundOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*orderapi.OrderServiceRefundOrderArgs)
	realResult := result.(*orderapi.OrderServiceRefundOrderResult)
	success, err := handler.(orderapi.OrderService).RefundOrder(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOrderServiceRefundOrderArgs() interface{} {
	return orderapi.NewOrderServiceRefundOrderArgs()
}

func newOrderServiceRefundOrderResult() interface{} {
	return orderapi.NewOrderServiceRefundOrderResult()
}

func getOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*orderapi.OrderServiceGetOrderArgs)
	realResult := result.(*orderapi.OrderServiceGetOrderResult)
	success, err := handler.(orderapi.OrderService).GetOrder(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOrderServiceGetOrderArgs() interface{} {
	return orderapi.NewOrderServiceGetOrderArgs()
}

func newOrderServiceGetOrderResult() interface{} {
	return orderapi.NewOrderServiceGetOrderResult()
}

func listOrdersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*orderapi.OrderServiceListOrdersArgs)
	realResult := result.(*orderapi.OrderServiceListOrdersResult)
	success, err := handler.(orderapi.OrderService).ListOrders(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOrderServiceListOrdersArgs() interface{} {
	return orderapi.NewOrderServiceListOrdersArgs()
}

func newOrderServiceListOrdersResult() interface{} {
	return orderapi.NewOrderServiceListOrdersResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateOrder(ctx context.Context, req *orderapi.CreateOrderReq) (r *orderapi.CreateOrderResp, err error) {
	var _args orderapi.OrderServiceCreateOrderArgs
	_args.Req = req
	var _result orderapi.OrderServiceCreateOrderResult
	if err = p.c.Call(ctx, "CreateOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) PayOrder(ctx context.Context, req *orderapi.PayOrderReq) (r *orderapi.PayOrderResp, err error) {
	var _args orderapi.OrderServicePayOrderArgs
	_args.Req = req
	var _result orderapi.OrderServicePayOrderResult
	if err = p.c.Call(ctx, "PayOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ConfirmPay(ctx context.Context, req *orderapi.ConfirmPayReq) (r *orderapi.ConfirmPayResp, err error) {
	var _args orderapi.OrderServiceConfirmPayArgs
	_args.Req = req
	var _result orderapi.OrderServiceConfirmPayResult
	if err = p.c.Call(ctx, "ConfirmPay", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ChangeOrder(ctx context.Context, req *orderapi.ChangeOrderReq) (r *orderapi.ChangeOrderResp, err error) {
	var _args orderapi.OrderServiceChangeOrderArgs
	_args.Req = req
	var _result orderapi.OrderServiceChangeOrderResult
	if err = p.c.Call(ctx, "ChangeOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CancelOrder(ctx context.Context, req *orderapi.CancelOrderReq) (r *common.BaseResp, err error) {
	var _args orderapi.OrderServiceCancelOrderArgs
	_args.Req = req
	var _result orderapi.OrderServiceCancelOrderResult
	if err = p.c.Call(ctx, "CancelOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RefundOrder(ctx context.Context, req *orderapi.RefundOrderReq) (r *orderapi.RefundOrderResp, err error) {
	var _args orderapi.OrderServiceRefundOrderArgs
	_args.Req = req
	var _result orderapi.OrderServiceRefundOrderResult
	if err = p.c.Call(ctx, "RefundOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetOrder(ctx context.Context, req *orderapi.GetOrderReq) (r *orderapi.GetOrderResp, err error) {
	var _args orderapi.OrderServiceGetOrderArgs
	_args.Req = req
	var _result orderapi.OrderServiceGetOrderResult
	if err = p.c.Call(ctx, "GetOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListOrders(ctx context.Context, req *orderapi.ListOrdersReq) (r *orderapi.ListOrdersResp, err error) {
	var _args orderapi.OrderServiceListOrdersArgs
	_args.Req = req
	var _result orderapi.OrderServiceListOrdersResult
	if err = p.c.Call(ctx, "ListOrders", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
