// Code generated by Kitex v0.15.4. DO NOT EDIT.

package hotelservice

import (
	"context"
	hotel "example_shop/kitex_gen/hotel"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateRoomType(ctx context.Context, req *hotel.CreateRoomTypeReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	UpdateRoomType(ctx context.Context, req *hotel.UpdateRoomTypeReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	GetRoomType(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.RoomType, err error)
	ListRoomTypes(ctx context.Context, req *hotel.ListRoomTypeReq, callOptions ...callopt.Option) (r *hotel.ListRoomTypeResp, err error)
	DeleteRoomType(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	CreateRoomInfo(ctx context.Context, req *hotel.CreateRoomInfoReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	UpdateRoomInfo(ctx context.Context, req *hotel.UpdateRoomInfoReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	GetRoomInfo(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.RoomInfo, err error)
	ListRoomInfos(ctx context.Context, req *hotel.ListRoomInfoReq, callOptions ...callopt.Option) (r *hotel.ListRoomInfoResp, err error)
	DeleteRoomInfo(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	UpdateRoomStatus(ctx context.Context, req *hotel.UpdateRoomStatusReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	BatchUpdateRoomStatus(ctx context.Context, req *hotel.BatchUpdateRoomStatusReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	CreateRoomBinding(ctx context.Context, req *hotel.CreateRoomBindingReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	BatchCreateRoomBindings(ctx context.Context, req *hotel.BatchCreateRoomBindingsReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	GetRoomBindings(ctx context.Context, roomId int64, callOptions ...callopt.Option) (r *hotel.ListRoomBindingsResp, err error)
	DeleteRoomBinding(ctx context.Context, bindingId int64, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	GetRoomImages(ctx context.Context, roomId int64, callOptions ...callopt.Option) (r *hotel.ListRoomImagesResp, err error)
	DeleteRoomImage(ctx context.Context, imageId int64, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	UpdateImageSortOrder(ctx context.Context, req *hotel.UpdateImageSortOrderReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	BatchUpdateImageSortOrder(ctx context.Context, req *hotel.BatchUpdateImageSortOrderReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	CreateFacility(ctx context.Context, req *hotel.CreateFacilityReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	UpdateFacility(ctx context.Context, req *hotel.UpdateFacilityReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	GetFacility(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.Facility, err error)
	ListFacilities(ctx context.Context, req *hotel.ListFacilityReq, callOptions ...callopt.Option) (r *hotel.ListFacilitiesResp, err error)
	DeleteFacility(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	SetRoomFacilities(ctx context.Context, req *hotel.SetRoomFacilitiesReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	GetRoomFacilities(ctx context.Context, roomId int64, callOptions ...callopt.Option) (r *hotel.ListFacilitiesResp, err error)
	AddRoomFacility(ctx context.Context, req *hotel.AddRoomFacilityReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	RemoveRoomFacility(ctx context.Context, req *hotel.RemoveRoomFacilityReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	CreateCancellationPolicy(ctx context.Context, req *hotel.CreateCancellationPolicyReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	UpdateCancellationPolicy(ctx context.Context, req *hotel.UpdateCancellationPolicyReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	GetCancellationPolicy(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.CancellationPolicy, err error)
	ListCancellationPolicies(ctx context.Context, req *hotel.ListCancellationPolicyReq, callOptions ...callopt.Option) (r *hotel.ListCancellationPoliciesResp, err error)
	DeleteCancellationPolicy(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	GetCalendarRoomStatus(ctx context.Context, req *hotel.CalendarRoomStatusReq, callOptions ...callopt.Option) (r *hotel.CalendarRoomStatusResp, err error)
	UpdateCalendarRoomStatus(ctx context.Context, req *hotel.UpdateCalendarRoomStatusReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	BatchUpdateCalendarRoomStatus(ctx context.Context, req *hotel.BatchUpdateCalendarRoomStatusReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	GetRealTimeStatistics(ctx context.Context, req *hotel.RealTimeStatisticsReq, callOptions ...callopt.Option) (r *hotel.RealTimeStatisticsResp, err error)
	ListBranches(ctx context.Context, req *hotel.ListBranchesReq, callOptions ...callopt.Option) (r *hotel.ListBranchesResp, err error)
	GetBranch(ctx context.Context, branchId int64, callOptions ...callopt.Option) (r *hotel.Branch, err error)
	SyncRoomStatusToChannel(ctx context.Context, req *hotel.SyncRoomStatusToChannelReq, callOptions ...callopt.Option) (r *hotel.SyncRoomStatusToChannelResp, err error)
	ListOrders(ctx context.Context, req *hotel.ListOrdersReq, callOptions ...callopt.Option) (r *hotel.ListOrdersResp, err error)
	GetOrder(ctx context.Context, orderId int64, callOptions ...callopt.Option) (r *hotel.Order, err error)
	ListInHouseGuests(ctx context.Context, req *hotel.ListInHouseGuestsReq, callOptions ...callopt.Option) (r *hotel.ListInHouseGuestsResp, err error)
	ListFinancialFlows(ctx context.Context, req *hotel.ListFinancialFlowsReq, callOptions ...callopt.Option) (r *hotel.ListFinancialFlowsResp, err error)
	CreateUserAccount(ctx context.Context, req *hotel.CreateUserAccountReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	UpdateUserAccount(ctx context.Context, req *hotel.UpdateUserAccountReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	GetUserAccount(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.UserAccount, err error)
	ListUserAccounts(ctx context.Context, req *hotel.ListUserAccountsReq, callOptions ...callopt.Option) (r *hotel.ListUserAccountsResp, err error)
	DeleteUserAccount(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	CreateRole(ctx context.Context, req *hotel.CreateRoleReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	UpdateRole(ctx context.Context, req *hotel.UpdateRoleReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	GetRole(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.Role, err error)
	ListRoles(ctx context.Context, req *hotel.ListRolesReq, callOptions ...callopt.Option) (r *hotel.ListRolesResp, err error)
	DeleteRole(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	ListPermissions(ctx context.Context, req *hotel.ListPermissionsReq, callOptions ...callopt.Option) (r *hotel.ListPermissionsResp, err error)
	CreateChannelConfig(ctx context.Context, req *hotel.CreateChannelConfigReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	UpdateChannelConfig(ctx context.Context, req *hotel.UpdateChannelConfigReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	GetChannelConfig(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.ChannelConfig, err error)
	ListChannelConfigs(ctx context.Context, req *hotel.ListChannelConfigsReq, callOptions ...callopt.Option) (r *hotel.ListChannelConfigsResp, err error)
	DeleteChannelConfig(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	CreateSystemConfig(ctx context.Context, req *hotel.CreateSystemConfigReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	UpdateSystemConfig(ctx context.Context, req *hotel.UpdateSystemConfigReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	GetSystemConfig(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.SystemConfig, err error)
	ListSystemConfigs(ctx context.Context, req *hotel.ListSystemConfigsReq, callOptions ...callopt.Option) (r *hotel.ListSystemConfigsResp, err error)
	DeleteSystemConfig(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	GetSystemConfigsByCategory(ctx context.Context, category string, callOptions ...callopt.Option) (r *hotel.ListSystemConfigsResp, err error)
	CreateBlacklist(ctx context.Context, req *hotel.CreateBlacklistReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	UpdateBlacklist(ctx context.Context, req *hotel.UpdateBlacklistReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	GetBlacklist(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.Blacklist, err error)
	ListBlacklists(ctx context.Context, req *hotel.ListBlacklistsReq, callOptions ...callopt.Option) (r *hotel.ListBlacklistsResp, err error)
	DeleteBlacklist(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	CreateMember(ctx context.Context, req *hotel.CreateMemberReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	UpdateMember(ctx context.Context, req *hotel.UpdateMemberReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	GetMember(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.Member, err error)
	GetMemberByGuestID(ctx context.Context, guestId int64, callOptions ...callopt.Option) (r *hotel.Member, err error)
	ListMembers(ctx context.Context, req *hotel.ListMembersReq, callOptions ...callopt.Option) (r *hotel.ListMembersResp, err error)
	DeleteMember(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	CreateMemberRights(ctx context.Context, req *hotel.CreateMemberRightsReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	UpdateMemberRights(ctx context.Context, req *hotel.UpdateMemberRightsReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	GetMemberRights(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.MemberRights, err error)
	ListMemberRights(ctx context.Context, req *hotel.ListMemberRightsReq, callOptions ...callopt.Option) (r *hotel.ListMemberRightsResp, err error)
	GetRightsByMemberLevel(ctx context.Context, memberLevel string, callOptions ...callopt.Option) (r *hotel.ListMemberRightsResp, err error)
	DeleteMemberRights(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	CreatePointsRecord(ctx context.Context, req *hotel.CreatePointsRecordReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	ListPointsRecords(ctx context.Context, req *hotel.ListPointsRecordsReq, callOptions ...callopt.Option) (r *hotel.ListPointsRecordsResp, err error)
	GetMemberPointsBalance(ctx context.Context, memberId int64, callOptions ...callopt.Option) (r int64, err error)
	CreateOperationLog(ctx context.Context, req *hotel.CreateOperationLogReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error)
	ListOperationLogs(ctx context.Context, req *hotel.ListOperationLogsReq, callOptions ...callopt.Option) (r *hotel.ListOperationLogsResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kHotelServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kHotelServiceClient struct {
	*kClient
}

func (p *kHotelServiceClient) CreateRoomType(ctx context.Context, req *hotel.CreateRoomTypeReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateRoomType(ctx, req)
}

func (p *kHotelServiceClient) UpdateRoomType(ctx context.Context, req *hotel.UpdateRoomTypeReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateRoomType(ctx, req)
}

func (p *kHotelServiceClient) GetRoomType(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.RoomType, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRoomType(ctx, id)
}

func (p *kHotelServiceClient) ListRoomTypes(ctx context.Context, req *hotel.ListRoomTypeReq, callOptions ...callopt.Option) (r *hotel.ListRoomTypeResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListRoomTypes(ctx, req)
}

func (p *kHotelServiceClient) DeleteRoomType(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteRoomType(ctx, id)
}

func (p *kHotelServiceClient) CreateRoomInfo(ctx context.Context, req *hotel.CreateRoomInfoReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateRoomInfo(ctx, req)
}

func (p *kHotelServiceClient) UpdateRoomInfo(ctx context.Context, req *hotel.UpdateRoomInfoReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateRoomInfo(ctx, req)
}

func (p *kHotelServiceClient) GetRoomInfo(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.RoomInfo, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRoomInfo(ctx, id)
}

func (p *kHotelServiceClient) ListRoomInfos(ctx context.Context, req *hotel.ListRoomInfoReq, callOptions ...callopt.Option) (r *hotel.ListRoomInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListRoomInfos(ctx, req)
}

func (p *kHotelServiceClient) DeleteRoomInfo(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteRoomInfo(ctx, id)
}

func (p *kHotelServiceClient) UpdateRoomStatus(ctx context.Context, req *hotel.UpdateRoomStatusReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateRoomStatus(ctx, req)
}

func (p *kHotelServiceClient) BatchUpdateRoomStatus(ctx context.Context, req *hotel.BatchUpdateRoomStatusReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchUpdateRoomStatus(ctx, req)
}

func (p *kHotelServiceClient) CreateRoomBinding(ctx context.Context, req *hotel.CreateRoomBindingReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateRoomBinding(ctx, req)
}

func (p *kHotelServiceClient) BatchCreateRoomBindings(ctx context.Context, req *hotel.BatchCreateRoomBindingsReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchCreateRoomBindings(ctx, req)
}

func (p *kHotelServiceClient) GetRoomBindings(ctx context.Context, roomId int64, callOptions ...callopt.Option) (r *hotel.ListRoomBindingsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRoomBindings(ctx, roomId)
}

func (p *kHotelServiceClient) DeleteRoomBinding(ctx context.Context, bindingId int64, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteRoomBinding(ctx, bindingId)
}

func (p *kHotelServiceClient) GetRoomImages(ctx context.Context, roomId int64, callOptions ...callopt.Option) (r *hotel.ListRoomImagesResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRoomImages(ctx, roomId)
}

func (p *kHotelServiceClient) DeleteRoomImage(ctx context.Context, imageId int64, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteRoomImage(ctx, imageId)
}

func (p *kHotelServiceClient) UpdateImageSortOrder(ctx context.Context, req *hotel.UpdateImageSortOrderReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateImageSortOrder(ctx, req)
}

func (p *kHotelServiceClient) BatchUpdateImageSortOrder(ctx context.Context, req *hotel.BatchUpdateImageSortOrderReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchUpdateImageSortOrder(ctx, req)
}

func (p *kHotelServiceClient) CreateFacility(ctx context.Context, req *hotel.CreateFacilityReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateFacility(ctx, req)
}

func (p *kHotelServiceClient) UpdateFacility(ctx context.Context, req *hotel.UpdateFacilityReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateFacility(ctx, req)
}

func (p *kHotelServiceClient) GetFacility(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.Facility, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFacility(ctx, id)
}

func (p *kHotelServiceClient) ListFacilities(ctx context.Context, req *hotel.ListFacilityReq, callOptions ...callopt.Option) (r *hotel.ListFacilitiesResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListFacilities(ctx, req)
}

func (p *kHotelServiceClient) DeleteFacility(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteFacility(ctx, id)
}

func (p *kHotelServiceClient) SetRoomFacilities(ctx context.Context, req *hotel.SetRoomFacilitiesReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SetRoomFacilities(ctx, req)
}

func (p *kHotelServiceClient) GetRoomFacilities(ctx context.Context, roomId int64, callOptions ...callopt.Option) (r *hotel.ListFacilitiesResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRoomFacilities(ctx, roomId)
}

func (p *kHotelServiceClient) AddRoomFacility(ctx context.Context, req *hotel.AddRoomFacilityReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddRoomFacility(ctx, req)
}

func (p *kHotelServiceClient) RemoveRoomFacility(ctx context.Context, req *hotel.RemoveRoomFacilityReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RemoveRoomFacility(ctx, req)
}

func (p *kHotelServiceClient) CreateCancellationPolicy(ctx context.Context, req *hotel.CreateCancellationPolicyReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateCancellationPolicy(ctx, req)
}

func (p *kHotelServiceClient) UpdateCancellationPolicy(ctx context.Context, req *hotel.UpdateCancellationPolicyReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateCancellationPolicy(ctx, req)
}

func (p *kHotelServiceClient) GetCancellationPolicy(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.CancellationPolicy, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCancellationPolicy(ctx, id)
}

func (p *kHotelServiceClient) ListCancellationPolicies(ctx context.Context, req *hotel.ListCancellationPolicyReq, callOptions ...callopt.Option) (r *hotel.ListCancellationPoliciesResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListCancellationPolicies(ctx, req)
}

func (p *kHotelServiceClient) DeleteCancellationPolicy(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteCancellationPolicy(ctx, id)
}

func (p *kHotelServiceClient) GetCalendarRoomStatus(ctx context.Context, req *hotel.CalendarRoomStatusReq, callOptions ...callopt.Option) (r *hotel.CalendarRoomStatusResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCalendarRoomStatus(ctx, req)
}

func (p *kHotelServiceClient) UpdateCalendarRoomStatus(ctx context.Context, req *hotel.UpdateCalendarRoomStatusReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateCalendarRoomStatus(ctx, req)
}

func (p *kHotelServiceClient) BatchUpdateCalendarRoomStatus(ctx context.Context, req *hotel.BatchUpdateCalendarRoomStatusReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchUpdateCalendarRoomStatus(ctx, req)
}

func (p *kHotelServiceClient) GetRealTimeStatistics(ctx context.Context, req *hotel.RealTimeStatisticsReq, callOptions ...callopt.Option) (r *hotel.RealTimeStatisticsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRealTimeStatistics(ctx, req)
}

func (p *kHotelServiceClient) ListBranches(ctx context.Context, req *hotel.ListBranchesReq, callOptions ...callopt.Option) (r *hotel.ListBranchesResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListBranches(ctx, req)
}

func (p *kHotelServiceClient) GetBranch(ctx context.Context, branchId int64, callOptions ...callopt.Option) (r *hotel.Branch, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetBranch(ctx, branchId)
}

func (p *kHotelServiceClient) SyncRoomStatusToChannel(ctx context.Context, req *hotel.SyncRoomStatusToChannelReq, callOptions ...callopt.Option) (r *hotel.SyncRoomStatusToChannelResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SyncRoomStatusToChannel(ctx, req)
}

func (p *kHotelServiceClient) ListOrders(ctx context.Context, req *hotel.ListOrdersReq, callOptions ...callopt.Option) (r *hotel.ListOrdersResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListOrders(ctx, req)
}

func (p *kHotelServiceClient) GetOrder(ctx context.Context, orderId int64, callOptions ...callopt.Option) (r *hotel.Order, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOrder(ctx, orderId)
}

func (p *kHotelServiceClient) ListInHouseGuests(ctx context.Context, req *hotel.ListInHouseGuestsReq, callOptions ...callopt.Option) (r *hotel.ListInHouseGuestsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListInHouseGuests(ctx, req)
}

func (p *kHotelServiceClient) ListFinancialFlows(ctx context.Context, req *hotel.ListFinancialFlowsReq, callOptions ...callopt.Option) (r *hotel.ListFinancialFlowsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListFinancialFlows(ctx, req)
}

func (p *kHotelServiceClient) CreateUserAccount(ctx context.Context, req *hotel.CreateUserAccountReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateUserAccount(ctx, req)
}

func (p *kHotelServiceClient) UpdateUserAccount(ctx context.Context, req *hotel.UpdateUserAccountReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateUserAccount(ctx, req)
}

func (p *kHotelServiceClient) GetUserAccount(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.UserAccount, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserAccount(ctx, id)
}

func (p *kHotelServiceClient) ListUserAccounts(ctx context.Context, req *hotel.ListUserAccountsReq, callOptions ...callopt.Option) (r *hotel.ListUserAccountsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListUserAccounts(ctx, req)
}

func (p *kHotelServiceClient) DeleteUserAccount(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteUserAccount(ctx, id)
}

func (p *kHotelServiceClient) CreateRole(ctx context.Context, req *hotel.CreateRoleReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateRole(ctx, req)
}

func (p *kHotelServiceClient) UpdateRole(ctx context.Context, req *hotel.UpdateRoleReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateRole(ctx, req)
}

func (p *kHotelServiceClient) GetRole(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.Role, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRole(ctx, id)
}

func (p *kHotelServiceClient) ListRoles(ctx context.Context, req *hotel.ListRolesReq, callOptions ...callopt.Option) (r *hotel.ListRolesResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListRoles(ctx, req)
}

func (p *kHotelServiceClient) DeleteRole(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteRole(ctx, id)
}

func (p *kHotelServiceClient) ListPermissions(ctx context.Context, req *hotel.ListPermissionsReq, callOptions ...callopt.Option) (r *hotel.ListPermissionsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListPermissions(ctx, req)
}

func (p *kHotelServiceClient) CreateChannelConfig(ctx context.Context, req *hotel.CreateChannelConfigReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateChannelConfig(ctx, req)
}

func (p *kHotelServiceClient) UpdateChannelConfig(ctx context.Context, req *hotel.UpdateChannelConfigReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateChannelConfig(ctx, req)
}

func (p *kHotelServiceClient) GetChannelConfig(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.ChannelConfig, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetChannelConfig(ctx, id)
}

func (p *kHotelServiceClient) ListChannelConfigs(ctx context.Context, req *hotel.ListChannelConfigsReq, callOptions ...callopt.Option) (r *hotel.ListChannelConfigsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListChannelConfigs(ctx, req)
}

func (p *kHotelServiceClient) DeleteChannelConfig(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteChannelConfig(ctx, id)
}

func (p *kHotelServiceClient) CreateSystemConfig(ctx context.Context, req *hotel.CreateSystemConfigReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateSystemConfig(ctx, req)
}

func (p *kHotelServiceClient) UpdateSystemConfig(ctx context.Context, req *hotel.UpdateSystemConfigReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateSystemConfig(ctx, req)
}

func (p *kHotelServiceClient) GetSystemConfig(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.SystemConfig, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetSystemConfig(ctx, id)
}

func (p *kHotelServiceClient) ListSystemConfigs(ctx context.Context, req *hotel.ListSystemConfigsReq, callOptions ...callopt.Option) (r *hotel.ListSystemConfigsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListSystemConfigs(ctx, req)
}

func (p *kHotelServiceClient) DeleteSystemConfig(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteSystemConfig(ctx, id)
}

func (p *kHotelServiceClient) GetSystemConfigsByCategory(ctx context.Context, category string, callOptions ...callopt.Option) (r *hotel.ListSystemConfigsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetSystemConfigsByCategory(ctx, category)
}

func (p *kHotelServiceClient) CreateBlacklist(ctx context.Context, req *hotel.CreateBlacklistReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateBlacklist(ctx, req)
}

func (p *kHotelServiceClient) UpdateBlacklist(ctx context.Context, req *hotel.UpdateBlacklistReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateBlacklist(ctx, req)
}

func (p *kHotelServiceClient) GetBlacklist(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.Blacklist, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetBlacklist(ctx, id)
}

func (p *kHotelServiceClient) ListBlacklists(ctx context.Context, req *hotel.ListBlacklistsReq, callOptions ...callopt.Option) (r *hotel.ListBlacklistsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListBlacklists(ctx, req)
}

func (p *kHotelServiceClient) DeleteBlacklist(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteBlacklist(ctx, id)
}

func (p *kHotelServiceClient) CreateMember(ctx context.Context, req *hotel.CreateMemberReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateMember(ctx, req)
}

func (p *kHotelServiceClient) UpdateMember(ctx context.Context, req *hotel.UpdateMemberReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateMember(ctx, req)
}

func (p *kHotelServiceClient) GetMember(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.Member, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetMember(ctx, id)
}

func (p *kHotelServiceClient) GetMemberByGuestID(ctx context.Context, guestId int64, callOptions ...callopt.Option) (r *hotel.Member, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetMemberByGuestID(ctx, guestId)
}

func (p *kHotelServiceClient) ListMembers(ctx context.Context, req *hotel.ListMembersReq, callOptions ...callopt.Option) (r *hotel.ListMembersResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListMembers(ctx, req)
}

func (p *kHotelServiceClient) DeleteMember(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteMember(ctx, id)
}

func (p *kHotelServiceClient) CreateMemberRights(ctx context.Context, req *hotel.CreateMemberRightsReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateMemberRights(ctx, req)
}

func (p *kHotelServiceClient) UpdateMemberRights(ctx context.Context, req *hotel.UpdateMemberRightsReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateMemberRights(ctx, req)
}

func (p *kHotelServiceClient) GetMemberRights(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.MemberRights, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetMemberRights(ctx, id)
}

func (p *kHotelServiceClient) ListMemberRights(ctx context.Context, req *hotel.ListMemberRightsReq, callOptions ...callopt.Option) (r *hotel.ListMemberRightsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListMemberRights(ctx, req)
}

func (p *kHotelServiceClient) GetRightsByMemberLevel(ctx context.Context, memberLevel string, callOptions ...callopt.Option) (r *hotel.ListMemberRightsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRightsByMemberLevel(ctx, memberLevel)
}

func (p *kHotelServiceClient) DeleteMemberRights(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteMemberRights(ctx, id)
}

func (p *kHotelServiceClient) CreatePointsRecord(ctx context.Context, req *hotel.CreatePointsRecordReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreatePointsRecord(ctx, req)
}

func (p *kHotelServiceClient) ListPointsRecords(ctx context.Context, req *hotel.ListPointsRecordsReq, callOptions ...callopt.Option) (r *hotel.ListPointsRecordsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListPointsRecords(ctx, req)
}

func (p *kHotelServiceClient) GetMemberPointsBalance(ctx context.Context, memberId int64, callOptions ...callopt.Option) (r int64, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetMemberPointsBalance(ctx, memberId)
}

func (p *kHotelServiceClient) CreateOperationLog(ctx context.Context, req *hotel.CreateOperationLogReq, callOptions ...callopt.Option) (r *hotel.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateOperationLog(ctx, req)
}

func (p *kHotelServiceClient) ListOperationLogs(ctx context.Context, req *hotel.ListOperationLogsReq, callOptions ...callopt.Option) (r *hotel.ListOperationLogsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListOperationLogs(ctx, req)
}
