// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package ticketapi

import (
	"context"
	"example_shop/kitex_gen/common"
	"fmt"
)

type SeatTypeRemain struct {
	SeatType  string  `thrift:"seat_type,1" frugal:"1,default,string" json:"seat_type"`
	Remaining int32   `thrift:"remaining,2" frugal:"2,default,i32" json:"remaining"`
	MinPrice  float64 `thrift:"min_price,3" frugal:"3,default,double" json:"min_price"`
}

func NewSeatTypeRemain() *SeatTypeRemain {
	return &SeatTypeRemain{}
}

func (p *SeatTypeRemain) InitDefault() {
}

func (p *SeatTypeRemain) GetSeatType() (v string) {
	return p.SeatType
}

func (p *SeatTypeRemain) GetRemaining() (v int32) {
	return p.Remaining
}

func (p *SeatTypeRemain) GetMinPrice() (v float64) {
	return p.MinPrice
}
func (p *SeatTypeRemain) SetSeatType(val string) {
	p.SeatType = val
}
func (p *SeatTypeRemain) SetRemaining(val int32) {
	p.Remaining = val
}
func (p *SeatTypeRemain) SetMinPrice(val float64) {
	p.MinPrice = val
}

func (p *SeatTypeRemain) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SeatTypeRemain(%+v)", *p)
}

var fieldIDToName_SeatTypeRemain = map[int16]string{
	1: "seat_type",
	2: "remaining",
	3: "min_price",
}

type GetTrainDetailReq struct {
	TrainId          string  `thrift:"train_id,1" frugal:"1,default,string" json:"train_id"`
	DepartureStation *string `thrift:"departure_station,2,optional" frugal:"2,optional,string" json:"departure_station,omitempty"`
	ArrivalStation   *string `thrift:"arrival_station,3,optional" frugal:"3,optional,string" json:"arrival_station,omitempty"`
}

func NewGetTrainDetailReq() *GetTrainDetailReq {
	return &GetTrainDetailReq{}
}

func (p *GetTrainDetailReq) InitDefault() {
}

func (p *GetTrainDetailReq) GetTrainId() (v string) {
	return p.TrainId
}

var GetTrainDetailReq_DepartureStation_DEFAULT string

func (p *GetTrainDetailReq) GetDepartureStation() (v string) {
	if !p.IsSetDepartureStation() {
		return GetTrainDetailReq_DepartureStation_DEFAULT
	}
	return *p.DepartureStation
}

var GetTrainDetailReq_ArrivalStation_DEFAULT string

func (p *GetTrainDetailReq) GetArrivalStation() (v string) {
	if !p.IsSetArrivalStation() {
		return GetTrainDetailReq_ArrivalStation_DEFAULT
	}
	return *p.ArrivalStation
}
func (p *GetTrainDetailReq) SetTrainId(val string) {
	p.TrainId = val
}
func (p *GetTrainDetailReq) SetDepartureStation(val *string) {
	p.DepartureStation = val
}
func (p *GetTrainDetailReq) SetArrivalStation(val *string) {
	p.ArrivalStation = val
}

func (p *GetTrainDetailReq) IsSetDepartureStation() bool {
	return p.DepartureStation != nil
}

func (p *GetTrainDetailReq) IsSetArrivalStation() bool {
	return p.ArrivalStation != nil
}

func (p *GetTrainDetailReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetTrainDetailReq(%+v)", *p)
}

var fieldIDToName_GetTrainDetailReq = map[int16]string{
	1: "train_id",
	2: "departure_station",
	3: "arrival_station",
}

type GetTrainDetailResp struct {
	BaseResp          *common.BaseResp  `thrift:"base_resp,1" frugal:"1,default,common.BaseResp" json:"base_resp"`
	TrainId           string            `thrift:"train_id,2" frugal:"2,default,string" json:"train_id"`
	TrainCode         string            `thrift:"train_code,3" frugal:"3,default,string" json:"train_code"`
	TrainType         string            `thrift:"train_type,4" frugal:"4,default,string" json:"train_type"`
	DepartureStation  string            `thrift:"departure_station,5" frugal:"5,default,string" json:"departure_station"`
	ArrivalStation    string            `thrift:"arrival_station,6" frugal:"6,default,string" json:"arrival_station"`
	DepartureTimeUnix int64             `thrift:"departure_time_unix,7" frugal:"7,default,i64" json:"departure_time_unix"`
	ArrivalTimeUnix   int64             `thrift:"arrival_time_unix,8" frugal:"8,default,i64" json:"arrival_time_unix"`
	RuntimeMinutes    int32             `thrift:"runtime_minutes,9" frugal:"9,default,i32" json:"runtime_minutes"`
	SeatTypes         []*SeatTypeRemain `thrift:"seat_types,10" frugal:"10,default,list<SeatTypeRemain>" json:"seat_types"`
}

func NewGetTrainDetailResp() *GetTrainDetailResp {
	return &GetTrainDetailResp{}
}

func (p *GetTrainDetailResp) InitDefault() {
}

var GetTrainDetailResp_BaseResp_DEFAULT *common.BaseResp

func (p *GetTrainDetailResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetTrainDetailResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *GetTrainDetailResp) GetTrainId() (v string) {
	return p.TrainId
}

func (p *GetTrainDetailResp) GetTrainCode() (v string) {
	return p.TrainCode
}

func (p *GetTrainDetailResp) GetTrainType() (v string) {
	return p.TrainType
}

func (p *GetTrainDetailResp) GetDepartureStation() (v string) {
	return p.DepartureStation
}

func (p *GetTrainDetailResp) GetArrivalStation() (v string) {
	return p.ArrivalStation
}

func (p *GetTrainDetailResp) GetDepartureTimeUnix() (v int64) {
	return p.DepartureTimeUnix
}

func (p *GetTrainDetailResp) GetArrivalTimeUnix() (v int64) {
	return p.ArrivalTimeUnix
}

func (p *GetTrainDetailResp) GetRuntimeMinutes() (v int32) {
	return p.RuntimeMinutes
}

func (p *GetTrainDetailResp) GetSeatTypes() (v []*SeatTypeRemain) {
	return p.SeatTypes
}
func (p *GetTrainDetailResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *GetTrainDetailResp) SetTrainId(val string) {
	p.TrainId = val
}
func (p *GetTrainDetailResp) SetTrainCode(val string) {
	p.TrainCode = val
}
func (p *GetTrainDetailResp) SetTrainType(val string) {
	p.TrainType = val
}
func (p *GetTrainDetailResp) SetDepartureStation(val string) {
	p.DepartureStation = val
}
func (p *GetTrainDetailResp) SetArrivalStation(val string) {
	p.ArrivalStation = val
}
func (p *GetTrainDetailResp) SetDepartureTimeUnix(val int64) {
	p.DepartureTimeUnix = val
}
func (p *GetTrainDetailResp) SetArrivalTimeUnix(val int64) {
	p.ArrivalTimeUnix = val
}
func (p *GetTrainDetailResp) SetRuntimeMinutes(val int32) {
	p.RuntimeMinutes = val
}
func (p *GetTrainDetailResp) SetSeatTypes(val []*SeatTypeRemain) {
	p.SeatTypes = val
}

func (p *GetTrainDetailResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetTrainDetailResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetTrainDetailResp(%+v)", *p)
}

var fieldIDToName_GetTrainDetailResp = map[int16]string{
	1:  "base_resp",
	2:  "train_id",
	3:  "train_code",
	4:  "train_type",
	5:  "departure_station",
	6:  "arrival_station",
	7:  "departure_time_unix",
	8:  "arrival_time_unix",
	9:  "runtime_minutes",
	10: "seat_types",
}

type TicketService interface {
	GetTrainDetail(ctx context.Context, req *GetTrainDetailReq) (r *GetTrainDetailResp, err error)
}

type TicketServiceGetTrainDetailArgs struct {
	Req *GetTrainDetailReq `thrift:"req,1" frugal:"1,default,GetTrainDetailReq" json:"req"`
}

func NewTicketServiceGetTrainDetailArgs() *TicketServiceGetTrainDetailArgs {
	return &TicketServiceGetTrainDetailArgs{}
}

func (p *TicketServiceGetTrainDetailArgs) InitDefault() {
}

var TicketServiceGetTrainDetailArgs_Req_DEFAULT *GetTrainDetailReq

func (p *TicketServiceGetTrainDetailArgs) GetReq() (v *GetTrainDetailReq) {
	if !p.IsSetReq() {
		return TicketServiceGetTrainDetailArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TicketServiceGetTrainDetailArgs) SetReq(val *GetTrainDetailReq) {
	p.Req = val
}

func (p *TicketServiceGetTrainDetailArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TicketServiceGetTrainDetailArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TicketServiceGetTrainDetailArgs(%+v)", *p)
}

var fieldIDToName_TicketServiceGetTrainDetailArgs = map[int16]string{
	1: "req",
}

type TicketServiceGetTrainDetailResult struct {
	Success *GetTrainDetailResp `thrift:"success,0,optional" frugal:"0,optional,GetTrainDetailResp" json:"success,omitempty"`
}

func NewTicketServiceGetTrainDetailResult() *TicketServiceGetTrainDetailResult {
	return &TicketServiceGetTrainDetailResult{}
}

func (p *TicketServiceGetTrainDetailResult) InitDefault() {
}

var TicketServiceGetTrainDetailResult_Success_DEFAULT *GetTrainDetailResp

func (p *TicketServiceGetTrainDetailResult) GetSuccess() (v *GetTrainDetailResp) {
	if !p.IsSetSuccess() {
		return TicketServiceGetTrainDetailResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TicketServiceGetTrainDetailResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetTrainDetailResp)
}

func (p *TicketServiceGetTrainDetailResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TicketServiceGetTrainDetailResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TicketServiceGetTrainDetailResult(%+v)", *p)
}

var fieldIDToName_TicketServiceGetTrainDetailResult = map[int16]string{
	0: "success",
}
