// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package orderapi

import (
	"context"
	"example_shop/kitex_gen/common"
	"fmt"
)

type OrderSeatInfo struct {
	SeatId      string  `thrift:"seat_id,1" frugal:"1,default,string" json:"seat_id"`
	SeatType    string  `thrift:"seat_type,2" frugal:"2,default,string" json:"seat_type"`
	CarriageNum string  `thrift:"carriage_num,3" frugal:"3,default,string" json:"carriage_num"`
	SeatNum     string  `thrift:"seat_num,4" frugal:"4,default,string" json:"seat_num"`
	SeatPrice   float64 `thrift:"seat_price,5" frugal:"5,default,double" json:"seat_price"`
}

func NewOrderSeatInfo() *OrderSeatInfo {
	return &OrderSeatInfo{}
}

func (p *OrderSeatInfo) InitDefault() {
}

func (p *OrderSeatInfo) GetSeatId() (v string) {
	return p.SeatId
}

func (p *OrderSeatInfo) GetSeatType() (v string) {
	return p.SeatType
}

func (p *OrderSeatInfo) GetCarriageNum() (v string) {
	return p.CarriageNum
}

func (p *OrderSeatInfo) GetSeatNum() (v string) {
	return p.SeatNum
}

func (p *OrderSeatInfo) GetSeatPrice() (v float64) {
	return p.SeatPrice
}
func (p *OrderSeatInfo) SetSeatId(val string) {
	p.SeatId = val
}
func (p *OrderSeatInfo) SetSeatType(val string) {
	p.SeatType = val
}
func (p *OrderSeatInfo) SetCarriageNum(val string) {
	p.CarriageNum = val
}
func (p *OrderSeatInfo) SetSeatNum(val string) {
	p.SeatNum = val
}
func (p *OrderSeatInfo) SetSeatPrice(val float64) {
	p.SeatPrice = val
}

func (p *OrderSeatInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderSeatInfo(%+v)", *p)
}

var fieldIDToName_OrderSeatInfo = map[int16]string{
	1: "seat_id",
	2: "seat_type",
	3: "carriage_num",
	4: "seat_num",
	5: "seat_price",
}

type CreateOrderPassenger struct {
	RealName string `thrift:"real_name,1" frugal:"1,default,string" json:"real_name"`
	IdCard   string `thrift:"id_card,2" frugal:"2,default,string" json:"id_card"`
	SeatType string `thrift:"seat_type,3" frugal:"3,default,string" json:"seat_type"`
}

func NewCreateOrderPassenger() *CreateOrderPassenger {
	return &CreateOrderPassenger{}
}

func (p *CreateOrderPassenger) InitDefault() {
}

func (p *CreateOrderPassenger) GetRealName() (v string) {
	return p.RealName
}

func (p *CreateOrderPassenger) GetIdCard() (v string) {
	return p.IdCard
}

func (p *CreateOrderPassenger) GetSeatType() (v string) {
	return p.SeatType
}
func (p *CreateOrderPassenger) SetRealName(val string) {
	p.RealName = val
}
func (p *CreateOrderPassenger) SetIdCard(val string) {
	p.IdCard = val
}
func (p *CreateOrderPassenger) SetSeatType(val string) {
	p.SeatType = val
}

func (p *CreateOrderPassenger) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateOrderPassenger(%+v)", *p)
}

var fieldIDToName_CreateOrderPassenger = map[int16]string{
	1: "real_name",
	2: "id_card",
	3: "seat_type",
}

type CreateOrderReq struct {
	UserId           string                  `thrift:"user_id,1" frugal:"1,default,string" json:"user_id"`
	TrainId          string                  `thrift:"train_id,2" frugal:"2,default,string" json:"train_id"`
	DepartureStation string                  `thrift:"departure_station,3" frugal:"3,default,string" json:"departure_station"`
	ArrivalStation   string                  `thrift:"arrival_station,4" frugal:"4,default,string" json:"arrival_station"`
	Passengers       []*CreateOrderPassenger `thrift:"passengers,5" frugal:"5,default,list<CreateOrderPassenger>" json:"passengers"`
}

func NewCreateOrderReq() *CreateOrderReq {
	return &CreateOrderReq{}
}

func (p *CreateOrderReq) InitDefault() {
}

func (p *CreateOrderReq) GetUserId() (v string) {
	return p.UserId
}

func (p *CreateOrderReq) GetTrainId() (v string) {
	return p.TrainId
}

func (p *CreateOrderReq) GetDepartureStation() (v string) {
	return p.DepartureStation
}

func (p *CreateOrderReq) GetArrivalStation() (v string) {
	return p.ArrivalStation
}

func (p *CreateOrderReq) GetPassengers() (v []*CreateOrderPassenger) {
	return p.Passengers
}
func (p *CreateOrderReq) SetUserId(val string) {
	p.UserId = val
}
func (p *CreateOrderReq) SetTrainId(val string) {
	p.TrainId = val
}
func (p *CreateOrderReq) SetDepartureStation(val string) {
	p.DepartureStation = val
}
func (p *CreateOrderReq) SetArrivalStation(val string) {
	p.ArrivalStation = val
}
func (p *CreateOrderReq) SetPassengers(val []*CreateOrderPassenger) {
	p.Passengers = val
}

func (p *CreateOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateOrderReq(%+v)", *p)
}

var fieldIDToName_CreateOrderReq = map[int16]string{
	1: "user_id",
	2: "train_id",
	3: "departure_station",
	4: "arrival_station",
	5: "passengers",
}

type CreateOrderResp struct {
	BaseResp        *common.BaseResp `thrift:"base_resp,1" frugal:"1,default,common.BaseResp" json:"base_resp"`
	OrderId         string           `thrift:"order_id,2" frugal:"2,default,string" json:"order_id"`
	PayDeadlineUnix int64            `thrift:"pay_deadline_unix,3" frugal:"3,default,i64" json:"pay_deadline_unix"`
	Seats           []*OrderSeatInfo `thrift:"seats,4" frugal:"4,default,list<OrderSeatInfo>" json:"seats"`
}

func NewCreateOrderResp() *CreateOrderResp {
	return &CreateOrderResp{}
}

func (p *CreateOrderResp) InitDefault() {
}

var CreateOrderResp_BaseResp_DEFAULT *common.BaseResp

func (p *CreateOrderResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return CreateOrderResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *CreateOrderResp) GetOrderId() (v string) {
	return p.OrderId
}

func (p *CreateOrderResp) GetPayDeadlineUnix() (v int64) {
	return p.PayDeadlineUnix
}

func (p *CreateOrderResp) GetSeats() (v []*OrderSeatInfo) {
	return p.Seats
}
func (p *CreateOrderResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *CreateOrderResp) SetOrderId(val string) {
	p.OrderId = val
}
func (p *CreateOrderResp) SetPayDeadlineUnix(val int64) {
	p.PayDeadlineUnix = val
}
func (p *CreateOrderResp) SetSeats(val []*OrderSeatInfo) {
	p.Seats = val
}

func (p *CreateOrderResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *CreateOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateOrderResp(%+v)", *p)
}

var fieldIDToName_CreateOrderResp = map[int16]string{
	1: "base_resp",
	2: "order_id",
	3: "pay_deadline_unix",
	4: "seats",
}

type PayOrderReq struct {
	UserId     string  `thrift:"user_id,1" frugal:"1,default,string" json:"user_id"`
	OrderId    string  `thrift:"order_id,2" frugal:"2,default,string" json:"order_id"`
	PayChannel string  `thrift:"pay_channel,3" frugal:"3,default,string" json:"pay_channel"`
	PayNo      *string `thrift:"pay_no,4,optional" frugal:"4,optional,string" json:"pay_no,omitempty"`
}

func NewPayOrderReq() *PayOrderReq {
	return &PayOrderReq{}
}

func (p *PayOrderReq) InitDefault() {
}

func (p *PayOrderReq) GetUserId() (v string) {
	return p.UserId
}

func (p *PayOrderReq) GetOrderId() (v string) {
	return p.OrderId
}

func (p *PayOrderReq) GetPayChannel() (v string) {
	return p.PayChannel
}

var PayOrderReq_PayNo_DEFAULT string

func (p *PayOrderReq) GetPayNo() (v string) {
	if !p.IsSetPayNo() {
		return PayOrderReq_PayNo_DEFAULT
	}
	return *p.PayNo
}
func (p *PayOrderReq) SetUserId(val string) {
	p.UserId = val
}
func (p *PayOrderReq) SetOrderId(val string) {
	p.OrderId = val
}
func (p *PayOrderReq) SetPayChannel(val string) {
	p.PayChannel = val
}
func (p *PayOrderReq) SetPayNo(val *string) {
	p.PayNo = val
}

func (p *PayOrderReq) IsSetPayNo() bool {
	return p.PayNo != nil
}

func (p *PayOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PayOrderReq(%+v)", *p)
}

var fieldIDToName_PayOrderReq = map[int16]string{
	1: "user_id",
	2: "order_id",
	3: "pay_channel",
	4: "pay_no",
}

type PayOrderResp struct {
	BaseResp    *common.BaseResp `thrift:"base_resp,1" frugal:"1,default,common.BaseResp" json:"base_resp"`
	OrderStatus string           `thrift:"order_status,2" frugal:"2,default,string" json:"order_status"`
	PayStatus   string           `thrift:"pay_status,3" frugal:"3,default,string" json:"pay_status"`
	PayNo       *string          `thrift:"pay_no,4,optional" frugal:"4,optional,string" json:"pay_no,omitempty"`
}

func NewPayOrderResp() *PayOrderResp {
	return &PayOrderResp{}
}

func (p *PayOrderResp) InitDefault() {
}

var PayOrderResp_BaseResp_DEFAULT *common.BaseResp

func (p *PayOrderResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return PayOrderResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *PayOrderResp) GetOrderStatus() (v string) {
	return p.OrderStatus
}

func (p *PayOrderResp) GetPayStatus() (v string) {
	return p.PayStatus
}

var PayOrderResp_PayNo_DEFAULT string

func (p *PayOrderResp) GetPayNo() (v string) {
	if !p.IsSetPayNo() {
		return PayOrderResp_PayNo_DEFAULT
	}
	return *p.PayNo
}
func (p *PayOrderResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *PayOrderResp) SetOrderStatus(val string) {
	p.OrderStatus = val
}
func (p *PayOrderResp) SetPayStatus(val string) {
	p.PayStatus = val
}
func (p *PayOrderResp) SetPayNo(val *string) {
	p.PayNo = val
}

func (p *PayOrderResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *PayOrderResp) IsSetPayNo() bool {
	return p.PayNo != nil
}

func (p *PayOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PayOrderResp(%+v)", *p)
}

var fieldIDToName_PayOrderResp = map[int16]string{
	1: "base_resp",
	2: "order_status",
	3: "pay_status",
	4: "pay_no",
}

type ConfirmPayReq struct {
	UserId           string  `thrift:"user_id,1" frugal:"1,default,string" json:"user_id"`
	OrderId          string  `thrift:"order_id,2" frugal:"2,default,string" json:"order_id"`
	PayNo            string  `thrift:"pay_no,3" frugal:"3,default,string" json:"pay_no"`
	ThirdPartyStatus *string `thrift:"third_party_status,4,optional" frugal:"4,optional,string" json:"third_party_status,omitempty"`
}

func NewConfirmPayReq() *ConfirmPayReq {
	return &ConfirmPayReq{}
}

func (p *ConfirmPayReq) InitDefault() {
}

func (p *ConfirmPayReq) GetUserId() (v string) {
	return p.UserId
}

func (p *ConfirmPayReq) GetOrderId() (v string) {
	return p.OrderId
}

func (p *ConfirmPayReq) GetPayNo() (v string) {
	return p.PayNo
}

var ConfirmPayReq_ThirdPartyStatus_DEFAULT string

func (p *ConfirmPayReq) GetThirdPartyStatus() (v string) {
	if !p.IsSetThirdPartyStatus() {
		return ConfirmPayReq_ThirdPartyStatus_DEFAULT
	}
	return *p.ThirdPartyStatus
}
func (p *ConfirmPayReq) SetUserId(val string) {
	p.UserId = val
}
func (p *ConfirmPayReq) SetOrderId(val string) {
	p.OrderId = val
}
func (p *ConfirmPayReq) SetPayNo(val string) {
	p.PayNo = val
}
func (p *ConfirmPayReq) SetThirdPartyStatus(val *string) {
	p.ThirdPartyStatus = val
}

func (p *ConfirmPayReq) IsSetThirdPartyStatus() bool {
	return p.ThirdPartyStatus != nil
}

func (p *ConfirmPayReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ConfirmPayReq(%+v)", *p)
}

var fieldIDToName_ConfirmPayReq = map[int16]string{
	1: "user_id",
	2: "order_id",
	3: "pay_no",
	4: "third_party_status",
}

type ConfirmPayResp struct {
	BaseResp    *common.BaseResp `thrift:"base_resp,1" frugal:"1,default,common.BaseResp" json:"base_resp"`
	OrderStatus string           `thrift:"order_status,2" frugal:"2,default,string" json:"order_status"`
}

func NewConfirmPayResp() *ConfirmPayResp {
	return &ConfirmPayResp{}
}

func (p *ConfirmPayResp) InitDefault() {
}

var ConfirmPayResp_BaseResp_DEFAULT *common.BaseResp

func (p *ConfirmPayResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return ConfirmPayResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *ConfirmPayResp) GetOrderStatus() (v string) {
	return p.OrderStatus
}
func (p *ConfirmPayResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *ConfirmPayResp) SetOrderStatus(val string) {
	p.OrderStatus = val
}

func (p *ConfirmPayResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *ConfirmPayResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ConfirmPayResp(%+v)", *p)
}

var fieldIDToName_ConfirmPayResp = map[int16]string{
	1: "base_resp",
	2: "order_status",
}

type ChangeOrderReq struct {
	UserId               string `thrift:"user_id,1" frugal:"1,default,string" json:"user_id"`
	OrderId              string `thrift:"order_id,2" frugal:"2,default,string" json:"order_id"`
	NewTrainId_          string `thrift:"new_train_id,3" frugal:"3,default,string" json:"new_train_id"`
	NewDepartureStation_ string `thrift:"new_departure_station,4" frugal:"4,default,string" json:"new_departure_station"`
	NewArrivalStation_   string `thrift:"new_arrival_station,5" frugal:"5,default,string" json:"new_arrival_station"`
}

func NewChangeOrderReq() *ChangeOrderReq {
	return &ChangeOrderReq{}
}

func (p *ChangeOrderReq) InitDefault() {
}

func (p *ChangeOrderReq) GetUserId() (v string) {
	return p.UserId
}

func (p *ChangeOrderReq) GetOrderId() (v string) {
	return p.OrderId
}

func (p *ChangeOrderReq) GetNewTrainId_() (v string) {
	return p.NewTrainId_
}

func (p *ChangeOrderReq) GetNewDepartureStation_() (v string) {
	return p.NewDepartureStation_
}

func (p *ChangeOrderReq) GetNewArrivalStation_() (v string) {
	return p.NewArrivalStation_
}
func (p *ChangeOrderReq) SetUserId(val string) {
	p.UserId = val
}
func (p *ChangeOrderReq) SetOrderId(val string) {
	p.OrderId = val
}
func (p *ChangeOrderReq) SetNewTrainId_(val string) {
	p.NewTrainId_ = val
}
func (p *ChangeOrderReq) SetNewDepartureStation_(val string) {
	p.NewDepartureStation_ = val
}
func (p *ChangeOrderReq) SetNewArrivalStation_(val string) {
	p.NewArrivalStation_ = val
}

func (p *ChangeOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChangeOrderReq(%+v)", *p)
}

var fieldIDToName_ChangeOrderReq = map[int16]string{
	1: "user_id",
	2: "order_id",
	3: "new_train_id",
	4: "new_departure_station",
	5: "new_arrival_station",
}

type ChangeOrderResp struct {
	BaseResp         *common.BaseResp `thrift:"base_resp,1" frugal:"1,default,common.BaseResp" json:"base_resp"`
	OldOrderStatus   string           `thrift:"old_order_status,2" frugal:"2,default,string" json:"old_order_status"`
	NewOrderId_      string           `thrift:"new_order_id,3" frugal:"3,default,string" json:"new_order_id"`
	NewTotalAmount_  float64          `thrift:"new_total_amount,4" frugal:"4,default,double" json:"new_total_amount"`
	RefundDiffAmount float64          `thrift:"refund_diff_amount,5" frugal:"5,default,double" json:"refund_diff_amount"`
	Seats            []*OrderSeatInfo `thrift:"seats,6" frugal:"6,default,list<OrderSeatInfo>" json:"seats"`
}

func NewChangeOrderResp() *ChangeOrderResp {
	return &ChangeOrderResp{}
}

func (p *ChangeOrderResp) InitDefault() {
}

var ChangeOrderResp_BaseResp_DEFAULT *common.BaseResp

func (p *ChangeOrderResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return ChangeOrderResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *ChangeOrderResp) GetOldOrderStatus() (v string) {
	return p.OldOrderStatus
}

func (p *ChangeOrderResp) GetNewOrderId_() (v string) {
	return p.NewOrderId_
}

func (p *ChangeOrderResp) GetNewTotalAmount_() (v float64) {
	return p.NewTotalAmount_
}

func (p *ChangeOrderResp) GetRefundDiffAmount() (v float64) {
	return p.RefundDiffAmount
}

func (p *ChangeOrderResp) GetSeats() (v []*OrderSeatInfo) {
	return p.Seats
}
func (p *ChangeOrderResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *ChangeOrderResp) SetOldOrderStatus(val string) {
	p.OldOrderStatus = val
}
func (p *ChangeOrderResp) SetNewOrderId_(val string) {
	p.NewOrderId_ = val
}
func (p *ChangeOrderResp) SetNewTotalAmount_(val float64) {
	p.NewTotalAmount_ = val
}
func (p *ChangeOrderResp) SetRefundDiffAmount(val float64) {
	p.RefundDiffAmount = val
}
func (p *ChangeOrderResp) SetSeats(val []*OrderSeatInfo) {
	p.Seats = val
}

func (p *ChangeOrderResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *ChangeOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChangeOrderResp(%+v)", *p)
}

var fieldIDToName_ChangeOrderResp = map[int16]string{
	1: "base_resp",
	2: "old_order_status",
	3: "new_order_id",
	4: "new_total_amount",
	5: "refund_diff_amount",
	6: "seats",
}

type CancelOrderReq struct {
	UserId  string `thrift:"user_id,1" frugal:"1,default,string" json:"user_id"`
	OrderId string `thrift:"order_id,2" frugal:"2,default,string" json:"order_id"`
}

func NewCancelOrderReq() *CancelOrderReq {
	return &CancelOrderReq{}
}

func (p *CancelOrderReq) InitDefault() {
}

func (p *CancelOrderReq) GetUserId() (v string) {
	return p.UserId
}

func (p *CancelOrderReq) GetOrderId() (v string) {
	return p.OrderId
}
func (p *CancelOrderReq) SetUserId(val string) {
	p.UserId = val
}
func (p *CancelOrderReq) SetOrderId(val string) {
	p.OrderId = val
}

func (p *CancelOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CancelOrderReq(%+v)", *p)
}

var fieldIDToName_CancelOrderReq = map[int16]string{
	1: "user_id",
	2: "order_id",
}

type RefundOrderReq struct {
	UserId  string  `thrift:"user_id,1" frugal:"1,default,string" json:"user_id"`
	OrderId string  `thrift:"order_id,2" frugal:"2,default,string" json:"order_id"`
	Reason  *string `thrift:"reason,3,optional" frugal:"3,optional,string" json:"reason,omitempty"`
}

func NewRefundOrderReq() *RefundOrderReq {
	return &RefundOrderReq{}
}

func (p *RefundOrderReq) InitDefault() {
}

func (p *RefundOrderReq) GetUserId() (v string) {
	return p.UserId
}

func (p *RefundOrderReq) GetOrderId() (v string) {
	return p.OrderId
}

var RefundOrderReq_Reason_DEFAULT string

func (p *RefundOrderReq) GetReason() (v string) {
	if !p.IsSetReason() {
		return RefundOrderReq_Reason_DEFAULT
	}
	return *p.Reason
}
func (p *RefundOrderReq) SetUserId(val string) {
	p.UserId = val
}
func (p *RefundOrderReq) SetOrderId(val string) {
	p.OrderId = val
}
func (p *RefundOrderReq) SetReason(val *string) {
	p.Reason = val
}

func (p *RefundOrderReq) IsSetReason() bool {
	return p.Reason != nil
}

func (p *RefundOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefundOrderReq(%+v)", *p)
}

var fieldIDToName_RefundOrderReq = map[int16]string{
	1: "user_id",
	2: "order_id",
	3: "reason",
}

type RefundOrderResp struct {
	BaseResp     *common.BaseResp `thrift:"base_resp,1" frugal:"1,default,common.BaseResp" json:"base_resp"`
	RefundAmount float64          `thrift:"refund_amount,2" frugal:"2,default,double" json:"refund_amount"`
	RefundStatus string           `thrift:"refund_status,3" frugal:"3,default,string" json:"refund_status"`
	OrderStatus  string           `thrift:"order_status,4" frugal:"4,default,string" json:"order_status"`
}

func NewRefundOrderResp() *RefundOrderResp {
	return &RefundOrderResp{}
}

func (p *RefundOrderResp) InitDefault() {
}

var RefundOrderResp_BaseResp_DEFAULT *common.BaseResp

func (p *RefundOrderResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return RefundOrderResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *RefundOrderResp) GetRefundAmount() (v float64) {
	return p.RefundAmount
}

func (p *RefundOrderResp) GetRefundStatus() (v string) {
	return p.RefundStatus
}

func (p *RefundOrderResp) GetOrderStatus() (v string) {
	return p.OrderStatus
}
func (p *RefundOrderResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *RefundOrderResp) SetRefundAmount(val float64) {
	p.RefundAmount = val
}
func (p *RefundOrderResp) SetRefundStatus(val string) {
	p.RefundStatus = val
}
func (p *RefundOrderResp) SetOrderStatus(val string) {
	p.OrderStatus = val
}

func (p *RefundOrderResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *RefundOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefundOrderResp(%+v)", *p)
}

var fieldIDToName_RefundOrderResp = map[int16]string{
	1: "base_resp",
	2: "refund_amount",
	3: "refund_status",
	4: "order_status",
}

type ListOrdersReq struct {
	UserId string  `thrift:"user_id,1" frugal:"1,default,string" json:"user_id"`
	Status *string `thrift:"status,2,optional" frugal:"2,optional,string" json:"status,omitempty"`
	Cursor *string `thrift:"cursor,3,optional" frugal:"3,optional,string" json:"cursor,omitempty"`
	Limit  int32   `thrift:"limit,4" frugal:"4,default,i32" json:"limit"`
}

func NewListOrdersReq() *ListOrdersReq {
	return &ListOrdersReq{}
}

func (p *ListOrdersReq) InitDefault() {
}

func (p *ListOrdersReq) GetUserId() (v string) {
	return p.UserId
}

var ListOrdersReq_Status_DEFAULT string

func (p *ListOrdersReq) GetStatus() (v string) {
	if !p.IsSetStatus() {
		return ListOrdersReq_Status_DEFAULT
	}
	return *p.Status
}

var ListOrdersReq_Cursor_DEFAULT string

func (p *ListOrdersReq) GetCursor() (v string) {
	if !p.IsSetCursor() {
		return ListOrdersReq_Cursor_DEFAULT
	}
	return *p.Cursor
}

func (p *ListOrdersReq) GetLimit() (v int32) {
	return p.Limit
}
func (p *ListOrdersReq) SetUserId(val string) {
	p.UserId = val
}
func (p *ListOrdersReq) SetStatus(val *string) {
	p.Status = val
}
func (p *ListOrdersReq) SetCursor(val *string) {
	p.Cursor = val
}
func (p *ListOrdersReq) SetLimit(val int32) {
	p.Limit = val
}

func (p *ListOrdersReq) IsSetStatus() bool {
	return p.Status != nil
}

func (p *ListOrdersReq) IsSetCursor() bool {
	return p.Cursor != nil
}

func (p *ListOrdersReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListOrdersReq(%+v)", *p)
}

var fieldIDToName_ListOrdersReq = map[int16]string{
	1: "user_id",
	2: "status",
	3: "cursor",
	4: "limit",
}

type OrderInfo struct {
	OrderId          string  `thrift:"order_id,1" frugal:"1,default,string" json:"order_id"`
	UserId           string  `thrift:"user_id,2" frugal:"2,default,string" json:"user_id"`
	TrainId          string  `thrift:"train_id,3" frugal:"3,default,string" json:"train_id"`
	DepartureStation string  `thrift:"departure_station,4" frugal:"4,default,string" json:"departure_station"`
	ArrivalStation   string  `thrift:"arrival_station,5" frugal:"5,default,string" json:"arrival_station"`
	FromSeq          int32   `thrift:"from_seq,6" frugal:"6,default,i32" json:"from_seq"`
	ToSeq            int32   `thrift:"to_seq,7" frugal:"7,default,i32" json:"to_seq"`
	TotalAmount      float64 `thrift:"total_amount,8" frugal:"8,default,double" json:"total_amount"`
	OrderStatus      string  `thrift:"order_status,9" frugal:"9,default,string" json:"order_status"`
	PayDeadlineUnix  int64   `thrift:"pay_deadline_unix,10" frugal:"10,default,i64" json:"pay_deadline_unix"`
	PayTimeUnix      *int64  `thrift:"pay_time_unix,11,optional" frugal:"11,optional,i64" json:"pay_time_unix,omitempty"`
	PayChannel       *string `thrift:"pay_channel,12,optional" frugal:"12,optional,string" json:"pay_channel,omitempty"`
	PayNo            *string `thrift:"pay_no,13,optional" frugal:"13,optional,string" json:"pay_no,omitempty"`
	CreatedAtUnix    int64   `thrift:"created_at_unix,14" frugal:"14,default,i64" json:"created_at_unix"`
}

func NewOrderInfo() *OrderInfo {
	return &OrderInfo{}
}

func (p *OrderInfo) InitDefault() {
}

func (p *OrderInfo) GetOrderId() (v string) {
	return p.OrderId
}

func (p *OrderInfo) GetUserId() (v string) {
	return p.UserId
}

func (p *OrderInfo) GetTrainId() (v string) {
	return p.TrainId
}

func (p *OrderInfo) GetDepartureStation() (v string) {
	return p.DepartureStation
}

func (p *OrderInfo) GetArrivalStation() (v string) {
	return p.ArrivalStation
}

func (p *OrderInfo) GetFromSeq() (v int32) {
	return p.FromSeq
}

func (p *OrderInfo) GetToSeq() (v int32) {
	return p.ToSeq
}

func (p *OrderInfo) GetTotalAmount() (v float64) {
	return p.TotalAmount
}

func (p *OrderInfo) GetOrderStatus() (v string) {
	return p.OrderStatus
}

func (p *OrderInfo) GetPayDeadlineUnix() (v int64) {
	return p.PayDeadlineUnix
}

var OrderInfo_PayTimeUnix_DEFAULT int64

func (p *OrderInfo) GetPayTimeUnix() (v int64) {
	if !p.IsSetPayTimeUnix() {
		return OrderInfo_PayTimeUnix_DEFAULT
	}
	return *p.PayTimeUnix
}

var OrderInfo_PayChannel_DEFAULT string

func (p *OrderInfo) GetPayChannel() (v string) {
	if !p.IsSetPayChannel() {
		return OrderInfo_PayChannel_DEFAULT
	}
	return *p.PayChannel
}

var OrderInfo_PayNo_DEFAULT string

func (p *OrderInfo) GetPayNo() (v string) {
	if !p.IsSetPayNo() {
		return OrderInfo_PayNo_DEFAULT
	}
	return *p.PayNo
}

func (p *OrderInfo) GetCreatedAtUnix() (v int64) {
	return p.CreatedAtUnix
}
func (p *OrderInfo) SetOrderId(val string) {
	p.OrderId = val
}
func (p *OrderInfo) SetUserId(val string) {
	p.UserId = val
}
func (p *OrderInfo) SetTrainId(val string) {
	p.TrainId = val
}
func (p *OrderInfo) SetDepartureStation(val string) {
	p.DepartureStation = val
}
func (p *OrderInfo) SetArrivalStation(val string) {
	p.ArrivalStation = val
}
func (p *OrderInfo) SetFromSeq(val int32) {
	p.FromSeq = val
}
func (p *OrderInfo) SetToSeq(val int32) {
	p.ToSeq = val
}
func (p *OrderInfo) SetTotalAmount(val float64) {
	p.TotalAmount = val
}
func (p *OrderInfo) SetOrderStatus(val string) {
	p.OrderStatus = val
}
func (p *OrderInfo) SetPayDeadlineUnix(val int64) {
	p.PayDeadlineUnix = val
}
func (p *OrderInfo) SetPayTimeUnix(val *int64) {
	p.PayTimeUnix = val
}
func (p *OrderInfo) SetPayChannel(val *string) {
	p.PayChannel = val
}
func (p *OrderInfo) SetPayNo(val *string) {
	p.PayNo = val
}
func (p *OrderInfo) SetCreatedAtUnix(val int64) {
	p.CreatedAtUnix = val
}

func (p *OrderInfo) IsSetPayTimeUnix() bool {
	return p.PayTimeUnix != nil
}

func (p *OrderInfo) IsSetPayChannel() bool {
	return p.PayChannel != nil
}

func (p *OrderInfo) IsSetPayNo() bool {
	return p.PayNo != nil
}

func (p *OrderInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderInfo(%+v)", *p)
}

var fieldIDToName_OrderInfo = map[int16]string{
	1:  "order_id",
	2:  "user_id",
	3:  "train_id",
	4:  "departure_station",
	5:  "arrival_station",
	6:  "from_seq",
	7:  "to_seq",
	8:  "total_amount",
	9:  "order_status",
	10: "pay_deadline_unix",
	11: "pay_time_unix",
	12: "pay_channel",
	13: "pay_no",
	14: "created_at_unix",
}

type ListOrdersResp struct {
	BaseResp   *common.BaseResp `thrift:"base_resp,1" frugal:"1,default,common.BaseResp" json:"base_resp"`
	Orders     []*OrderInfo     `thrift:"orders,2" frugal:"2,default,list<OrderInfo>" json:"orders"`
	NextCursor *string          `thrift:"next_cursor,3,optional" frugal:"3,optional,string" json:"next_cursor,omitempty"`
}

func NewListOrdersResp() *ListOrdersResp {
	return &ListOrdersResp{}
}

func (p *ListOrdersResp) InitDefault() {
}

var ListOrdersResp_BaseResp_DEFAULT *common.BaseResp

func (p *ListOrdersResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return ListOrdersResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *ListOrdersResp) GetOrders() (v []*OrderInfo) {
	return p.Orders
}

var ListOrdersResp_NextCursor_DEFAULT string

func (p *ListOrdersResp) GetNextCursor() (v string) {
	if !p.IsSetNextCursor() {
		return ListOrdersResp_NextCursor_DEFAULT
	}
	return *p.NextCursor
}
func (p *ListOrdersResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *ListOrdersResp) SetOrders(val []*OrderInfo) {
	p.Orders = val
}
func (p *ListOrdersResp) SetNextCursor(val *string) {
	p.NextCursor = val
}

func (p *ListOrdersResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *ListOrdersResp) IsSetNextCursor() bool {
	return p.NextCursor != nil
}

func (p *ListOrdersResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListOrdersResp(%+v)", *p)
}

var fieldIDToName_ListOrdersResp = map[int16]string{
	1: "base_resp",
	2: "orders",
	3: "next_cursor",
}

type GetOrderReq struct {
	UserId  string `thrift:"user_id,1" frugal:"1,default,string" json:"user_id"`
	OrderId string `thrift:"order_id,2" frugal:"2,default,string" json:"order_id"`
}

func NewGetOrderReq() *GetOrderReq {
	return &GetOrderReq{}
}

func (p *GetOrderReq) InitDefault() {
}

func (p *GetOrderReq) GetUserId() (v string) {
	return p.UserId
}

func (p *GetOrderReq) GetOrderId() (v string) {
	return p.OrderId
}
func (p *GetOrderReq) SetUserId(val string) {
	p.UserId = val
}
func (p *GetOrderReq) SetOrderId(val string) {
	p.OrderId = val
}

func (p *GetOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetOrderReq(%+v)", *p)
}

var fieldIDToName_GetOrderReq = map[int16]string{
	1: "user_id",
	2: "order_id",
}

type GetOrderResp struct {
	BaseResp *common.BaseResp `thrift:"base_resp,1" frugal:"1,default,common.BaseResp" json:"base_resp"`
	Order    *OrderInfo       `thrift:"order,2,optional" frugal:"2,optional,OrderInfo" json:"order,omitempty"`
	Seats    []*OrderSeatInfo `thrift:"seats,3" frugal:"3,default,list<OrderSeatInfo>" json:"seats"`
}

func NewGetOrderResp() *GetOrderResp {
	return &GetOrderResp{}
}

func (p *GetOrderResp) InitDefault() {
}

var GetOrderResp_BaseResp_DEFAULT *common.BaseResp

func (p *GetOrderResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetOrderResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

var GetOrderResp_Order_DEFAULT *OrderInfo

func (p *GetOrderResp) GetOrder() (v *OrderInfo) {
	if !p.IsSetOrder() {
		return GetOrderResp_Order_DEFAULT
	}
	return p.Order
}

func (p *GetOrderResp) GetSeats() (v []*OrderSeatInfo) {
	return p.Seats
}
func (p *GetOrderResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *GetOrderResp) SetOrder(val *OrderInfo) {
	p.Order = val
}
func (p *GetOrderResp) SetSeats(val []*OrderSeatInfo) {
	p.Seats = val
}

func (p *GetOrderResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetOrderResp) IsSetOrder() bool {
	return p.Order != nil
}

func (p *GetOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetOrderResp(%+v)", *p)
}

var fieldIDToName_GetOrderResp = map[int16]string{
	1: "base_resp",
	2: "order",
	3: "seats",
}

type OrderService interface {
	CreateOrder(ctx context.Context, req *CreateOrderReq) (r *CreateOrderResp, err error)

	PayOrder(ctx context.Context, req *PayOrderReq) (r *PayOrderResp, err error)

	ConfirmPay(ctx context.Context, req *ConfirmPayReq) (r *ConfirmPayResp, err error)

	ChangeOrder(ctx context.Context, req *ChangeOrderReq) (r *ChangeOrderResp, err error)

	CancelOrder(ctx context.Context, req *CancelOrderReq) (r *common.BaseResp, err error)

	RefundOrder(ctx context.Context, req *RefundOrderReq) (r *RefundOrderResp, err error)

	GetOrder(ctx context.Context, req *GetOrderReq) (r *GetOrderResp, err error)

	ListOrders(ctx context.Context, req *ListOrdersReq) (r *ListOrdersResp, err error)
}

type OrderServiceCreateOrderArgs struct {
	Req *CreateOrderReq `thrift:"req,1" frugal:"1,default,CreateOrderReq" json:"req"`
}

func NewOrderServiceCreateOrderArgs() *OrderServiceCreateOrderArgs {
	return &OrderServiceCreateOrderArgs{}
}

func (p *OrderServiceCreateOrderArgs) InitDefault() {
}

var OrderServiceCreateOrderArgs_Req_DEFAULT *CreateOrderReq

func (p *OrderServiceCreateOrderArgs) GetReq() (v *CreateOrderReq) {
	if !p.IsSetReq() {
		return OrderServiceCreateOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceCreateOrderArgs) SetReq(val *CreateOrderReq) {
	p.Req = val
}

func (p *OrderServiceCreateOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceCreateOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceCreateOrderArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceCreateOrderArgs = map[int16]string{
	1: "req",
}

type OrderServiceCreateOrderResult struct {
	Success *CreateOrderResp `thrift:"success,0,optional" frugal:"0,optional,CreateOrderResp" json:"success,omitempty"`
}

func NewOrderServiceCreateOrderResult() *OrderServiceCreateOrderResult {
	return &OrderServiceCreateOrderResult{}
}

func (p *OrderServiceCreateOrderResult) InitDefault() {
}

var OrderServiceCreateOrderResult_Success_DEFAULT *CreateOrderResp

func (p *OrderServiceCreateOrderResult) GetSuccess() (v *CreateOrderResp) {
	if !p.IsSetSuccess() {
		return OrderServiceCreateOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceCreateOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateOrderResp)
}

func (p *OrderServiceCreateOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceCreateOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceCreateOrderResult(%+v)", *p)
}

var fieldIDToName_OrderServiceCreateOrderResult = map[int16]string{
	0: "success",
}

type OrderServicePayOrderArgs struct {
	Req *PayOrderReq `thrift:"req,1" frugal:"1,default,PayOrderReq" json:"req"`
}

func NewOrderServicePayOrderArgs() *OrderServicePayOrderArgs {
	return &OrderServicePayOrderArgs{}
}

func (p *OrderServicePayOrderArgs) InitDefault() {
}

var OrderServicePayOrderArgs_Req_DEFAULT *PayOrderReq

func (p *OrderServicePayOrderArgs) GetReq() (v *PayOrderReq) {
	if !p.IsSetReq() {
		return OrderServicePayOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServicePayOrderArgs) SetReq(val *PayOrderReq) {
	p.Req = val
}

func (p *OrderServicePayOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServicePayOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServicePayOrderArgs(%+v)", *p)
}

var fieldIDToName_OrderServicePayOrderArgs = map[int16]string{
	1: "req",
}

type OrderServicePayOrderResult struct {
	Success *PayOrderResp `thrift:"success,0,optional" frugal:"0,optional,PayOrderResp" json:"success,omitempty"`
}

func NewOrderServicePayOrderResult() *OrderServicePayOrderResult {
	return &OrderServicePayOrderResult{}
}

func (p *OrderServicePayOrderResult) InitDefault() {
}

var OrderServicePayOrderResult_Success_DEFAULT *PayOrderResp

func (p *OrderServicePayOrderResult) GetSuccess() (v *PayOrderResp) {
	if !p.IsSetSuccess() {
		return OrderServicePayOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServicePayOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*PayOrderResp)
}

func (p *OrderServicePayOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServicePayOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServicePayOrderResult(%+v)", *p)
}

var fieldIDToName_OrderServicePayOrderResult = map[int16]string{
	0: "success",
}

type OrderServiceConfirmPayArgs struct {
	Req *ConfirmPayReq `thrift:"req,1" frugal:"1,default,ConfirmPayReq" json:"req"`
}

func NewOrderServiceConfirmPayArgs() *OrderServiceConfirmPayArgs {
	return &OrderServiceConfirmPayArgs{}
}

func (p *OrderServiceConfirmPayArgs) InitDefault() {
}

var OrderServiceConfirmPayArgs_Req_DEFAULT *ConfirmPayReq

func (p *OrderServiceConfirmPayArgs) GetReq() (v *ConfirmPayReq) {
	if !p.IsSetReq() {
		return OrderServiceConfirmPayArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceConfirmPayArgs) SetReq(val *ConfirmPayReq) {
	p.Req = val
}

func (p *OrderServiceConfirmPayArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceConfirmPayArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceConfirmPayArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceConfirmPayArgs = map[int16]string{
	1: "req",
}

type OrderServiceConfirmPayResult struct {
	Success *ConfirmPayResp `thrift:"success,0,optional" frugal:"0,optional,ConfirmPayResp" json:"success,omitempty"`
}

func NewOrderServiceConfirmPayResult() *OrderServiceConfirmPayResult {
	return &OrderServiceConfirmPayResult{}
}

func (p *OrderServiceConfirmPayResult) InitDefault() {
}

var OrderServiceConfirmPayResult_Success_DEFAULT *ConfirmPayResp

func (p *OrderServiceConfirmPayResult) GetSuccess() (v *ConfirmPayResp) {
	if !p.IsSetSuccess() {
		return OrderServiceConfirmPayResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceConfirmPayResult) SetSuccess(x interface{}) {
	p.Success = x.(*ConfirmPayResp)
}

func (p *OrderServiceConfirmPayResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceConfirmPayResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceConfirmPayResult(%+v)", *p)
}

var fieldIDToName_OrderServiceConfirmPayResult = map[int16]string{
	0: "success",
}

type OrderServiceChangeOrderArgs struct {
	Req *ChangeOrderReq `thrift:"req,1" frugal:"1,default,ChangeOrderReq" json:"req"`
}

func NewOrderServiceChangeOrderArgs() *OrderServiceChangeOrderArgs {
	return &OrderServiceChangeOrderArgs{}
}

func (p *OrderServiceChangeOrderArgs) InitDefault() {
}

var OrderServiceChangeOrderArgs_Req_DEFAULT *ChangeOrderReq

func (p *OrderServiceChangeOrderArgs) GetReq() (v *ChangeOrderReq) {
	if !p.IsSetReq() {
		return OrderServiceChangeOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceChangeOrderArgs) SetReq(val *ChangeOrderReq) {
	p.Req = val
}

func (p *OrderServiceChangeOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceChangeOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceChangeOrderArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceChangeOrderArgs = map[int16]string{
	1: "req",
}

type OrderServiceChangeOrderResult struct {
	Success *ChangeOrderResp `thrift:"success,0,optional" frugal:"0,optional,ChangeOrderResp" json:"success,omitempty"`
}

func NewOrderServiceChangeOrderResult() *OrderServiceChangeOrderResult {
	return &OrderServiceChangeOrderResult{}
}

func (p *OrderServiceChangeOrderResult) InitDefault() {
}

var OrderServiceChangeOrderResult_Success_DEFAULT *ChangeOrderResp

func (p *OrderServiceChangeOrderResult) GetSuccess() (v *ChangeOrderResp) {
	if !p.IsSetSuccess() {
		return OrderServiceChangeOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceChangeOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*ChangeOrderResp)
}

func (p *OrderServiceChangeOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceChangeOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceChangeOrderResult(%+v)", *p)
}

var fieldIDToName_OrderServiceChangeOrderResult = map[int16]string{
	0: "success",
}

type OrderServiceCancelOrderArgs struct {
	Req *CancelOrderReq `thrift:"req,1" frugal:"1,default,CancelOrderReq" json:"req"`
}

func NewOrderServiceCancelOrderArgs() *OrderServiceCancelOrderArgs {
	return &OrderServiceCancelOrderArgs{}
}

func (p *OrderServiceCancelOrderArgs) InitDefault() {
}

var OrderServiceCancelOrderArgs_Req_DEFAULT *CancelOrderReq

func (p *OrderServiceCancelOrderArgs) GetReq() (v *CancelOrderReq) {
	if !p.IsSetReq() {
		return OrderServiceCancelOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceCancelOrderArgs) SetReq(val *CancelOrderReq) {
	p.Req = val
}

func (p *OrderServiceCancelOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceCancelOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceCancelOrderArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceCancelOrderArgs = map[int16]string{
	1: "req",
}

type OrderServiceCancelOrderResult struct {
	Success *common.BaseResp `thrift:"success,0,optional" frugal:"0,optional,common.BaseResp" json:"success,omitempty"`
}

func NewOrderServiceCancelOrderResult() *OrderServiceCancelOrderResult {
	return &OrderServiceCancelOrderResult{}
}

func (p *OrderServiceCancelOrderResult) InitDefault() {
}

var OrderServiceCancelOrderResult_Success_DEFAULT *common.BaseResp

func (p *OrderServiceCancelOrderResult) GetSuccess() (v *common.BaseResp) {
	if !p.IsSetSuccess() {
		return OrderServiceCancelOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceCancelOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*common.BaseResp)
}

func (p *OrderServiceCancelOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceCancelOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceCancelOrderResult(%+v)", *p)
}

var fieldIDToName_OrderServiceCancelOrderResult = map[int16]string{
	0: "success",
}

type OrderServiceRefundOrderArgs struct {
	Req *RefundOrderReq `thrift:"req,1" frugal:"1,default,RefundOrderReq" json:"req"`
}

func NewOrderServiceRefundOrderArgs() *OrderServiceRefundOrderArgs {
	return &OrderServiceRefundOrderArgs{}
}

func (p *OrderServiceRefundOrderArgs) InitDefault() {
}

var OrderServiceRefundOrderArgs_Req_DEFAULT *RefundOrderReq

func (p *OrderServiceRefundOrderArgs) GetReq() (v *RefundOrderReq) {
	if !p.IsSetReq() {
		return OrderServiceRefundOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceRefundOrderArgs) SetReq(val *RefundOrderReq) {
	p.Req = val
}

func (p *OrderServiceRefundOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceRefundOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceRefundOrderArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceRefundOrderArgs = map[int16]string{
	1: "req",
}

type OrderServiceRefundOrderResult struct {
	Success *RefundOrderResp `thrift:"success,0,optional" frugal:"0,optional,RefundOrderResp" json:"success,omitempty"`
}

func NewOrderServiceRefundOrderResult() *OrderServiceRefundOrderResult {
	return &OrderServiceRefundOrderResult{}
}

func (p *OrderServiceRefundOrderResult) InitDefault() {
}

var OrderServiceRefundOrderResult_Success_DEFAULT *RefundOrderResp

func (p *OrderServiceRefundOrderResult) GetSuccess() (v *RefundOrderResp) {
	if !p.IsSetSuccess() {
		return OrderServiceRefundOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceRefundOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*RefundOrderResp)
}

func (p *OrderServiceRefundOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceRefundOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceRefundOrderResult(%+v)", *p)
}

var fieldIDToName_OrderServiceRefundOrderResult = map[int16]string{
	0: "success",
}

type OrderServiceGetOrderArgs struct {
	Req *GetOrderReq `thrift:"req,1" frugal:"1,default,GetOrderReq" json:"req"`
}

func NewOrderServiceGetOrderArgs() *OrderServiceGetOrderArgs {
	return &OrderServiceGetOrderArgs{}
}

func (p *OrderServiceGetOrderArgs) InitDefault() {
}

var OrderServiceGetOrderArgs_Req_DEFAULT *GetOrderReq

func (p *OrderServiceGetOrderArgs) GetReq() (v *GetOrderReq) {
	if !p.IsSetReq() {
		return OrderServiceGetOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceGetOrderArgs) SetReq(val *GetOrderReq) {
	p.Req = val
}

func (p *OrderServiceGetOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceGetOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceGetOrderArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceGetOrderArgs = map[int16]string{
	1: "req",
}

type OrderServiceGetOrderResult struct {
	Success *GetOrderResp `thrift:"success,0,optional" frugal:"0,optional,GetOrderResp" json:"success,omitempty"`
}

func NewOrderServiceGetOrderResult() *OrderServiceGetOrderResult {
	return &OrderServiceGetOrderResult{}
}

func (p *OrderServiceGetOrderResult) InitDefault() {
}

var OrderServiceGetOrderResult_Success_DEFAULT *GetOrderResp

func (p *OrderServiceGetOrderResult) GetSuccess() (v *GetOrderResp) {
	if !p.IsSetSuccess() {
		return OrderServiceGetOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceGetOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetOrderResp)
}

func (p *OrderServiceGetOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceGetOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceGetOrderResult(%+v)", *p)
}

var fieldIDToName_OrderServiceGetOrderResult = map[int16]string{
	0: "success",
}

type OrderServiceListOrdersArgs struct {
	Req *ListOrdersReq `thrift:"req,1" frugal:"1,default,ListOrdersReq" json:"req"`
}

func NewOrderServiceListOrdersArgs() *OrderServiceListOrdersArgs {
	return &OrderServiceListOrdersArgs{}
}

func (p *OrderServiceListOrdersArgs) InitDefault() {
}

var OrderServiceListOrdersArgs_Req_DEFAULT *ListOrdersReq

func (p *OrderServiceListOrdersArgs) GetReq() (v *ListOrdersReq) {
	if !p.IsSetReq() {
		return OrderServiceListOrdersArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceListOrdersArgs) SetReq(val *ListOrdersReq) {
	p.Req = val
}

func (p *OrderServiceListOrdersArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceListOrdersArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceListOrdersArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceListOrdersArgs = map[int16]string{
	1: "req",
}

type OrderServiceListOrdersResult struct {
	Success *ListOrdersResp `thrift:"success,0,optional" frugal:"0,optional,ListOrdersResp" json:"success,omitempty"`
}

func NewOrderServiceListOrdersResult() *OrderServiceListOrdersResult {
	return &OrderServiceListOrdersResult{}
}

func (p *OrderServiceListOrdersResult) InitDefault() {
}

var OrderServiceListOrdersResult_Success_DEFAULT *ListOrdersResp

func (p *OrderServiceListOrdersResult) GetSuccess() (v *ListOrdersResp) {
	if !p.IsSetSuccess() {
		return OrderServiceListOrdersResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceListOrdersResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListOrdersResp)
}

func (p *OrderServiceListOrdersResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceListOrdersResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceListOrdersResult(%+v)", *p)
}

var fieldIDToName_OrderServiceListOrdersResult = map[int16]string{
	0: "success",
}
