// Code generated by Kitex v0.15.4. DO NOT EDIT.

package ticketservice

import (
	"context"
	"errors"
	ticketapi "example_shop/kitex_gen/ticketapi"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetTrainDetail": kitex.NewMethodInfo(
		getTrainDetailHandler,
		newTicketServiceGetTrainDetailArgs,
		newTicketServiceGetTrainDetailResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	ticketServiceServiceInfo                = NewServiceInfo()
	ticketServiceServiceInfoForClient       = NewServiceInfoForClient()
	ticketServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return ticketServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return ticketServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return ticketServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "TicketService"
	handlerType := (*ticketapi.TicketService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "ticketapi",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.4",
		Extra:           extra,
	}
	return svcInfo
}

func getTrainDetailHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ticketapi.TicketServiceGetTrainDetailArgs)
	realResult := result.(*ticketapi.TicketServiceGetTrainDetailResult)
	success, err := handler.(ticketapi.TicketService).GetTrainDetail(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTicketServiceGetTrainDetailArgs() interface{} {
	return ticketapi.NewTicketServiceGetTrainDetailArgs()
}

func newTicketServiceGetTrainDetailResult() interface{} {
	return ticketapi.NewTicketServiceGetTrainDetailResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetTrainDetail(ctx context.Context, req *ticketapi.GetTrainDetailReq) (r *ticketapi.GetTrainDetailResp, err error) {
	var _args ticketapi.TicketServiceGetTrainDetailArgs
	_args.Req = req
	var _result ticketapi.TicketServiceGetTrainDetailResult
	if err = p.c.Call(ctx, "GetTrainDetail", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
