// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package userapi

import (
	"context"
	"example_shop/kitex_gen/common"
	"fmt"
)

type VerifyRealNameReq struct {
	UserId   string `thrift:"user_id,1" frugal:"1,default,string" json:"user_id"`
	RealName string `thrift:"real_name,2" frugal:"2,default,string" json:"real_name"`
	IdCard   string `thrift:"id_card,3" frugal:"3,default,string" json:"id_card"`
	Phone    string `thrift:"phone,4" frugal:"4,default,string" json:"phone"`
}

func NewVerifyRealNameReq() *VerifyRealNameReq {
	return &VerifyRealNameReq{}
}

func (p *VerifyRealNameReq) InitDefault() {
}

func (p *VerifyRealNameReq) GetUserId() (v string) {
	return p.UserId
}

func (p *VerifyRealNameReq) GetRealName() (v string) {
	return p.RealName
}

func (p *VerifyRealNameReq) GetIdCard() (v string) {
	return p.IdCard
}

func (p *VerifyRealNameReq) GetPhone() (v string) {
	return p.Phone
}
func (p *VerifyRealNameReq) SetUserId(val string) {
	p.UserId = val
}
func (p *VerifyRealNameReq) SetRealName(val string) {
	p.RealName = val
}
func (p *VerifyRealNameReq) SetIdCard(val string) {
	p.IdCard = val
}
func (p *VerifyRealNameReq) SetPhone(val string) {
	p.Phone = val
}

func (p *VerifyRealNameReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerifyRealNameReq(%+v)", *p)
}

var fieldIDToName_VerifyRealNameReq = map[int16]string{
	1: "user_id",
	2: "real_name",
	3: "id_card",
	4: "phone",
}

type UserInfo struct {
	UserId           string `thrift:"user_id,1" frugal:"1,default,string" json:"user_id"`
	RealName         string `thrift:"real_name,2" frugal:"2,default,string" json:"real_name"`
	IdCard           string `thrift:"id_card,3" frugal:"3,default,string" json:"id_card"`
	Phone            string `thrift:"phone,4" frugal:"4,default,string" json:"phone"`
	UserLevel        string `thrift:"user_level,5" frugal:"5,default,string" json:"user_level"`
	RealNameVerified string `thrift:"real_name_verified,6" frugal:"6,default,string" json:"real_name_verified"`
	Status           string `thrift:"status,7" frugal:"7,default,string" json:"status"`
}

func NewUserInfo() *UserInfo {
	return &UserInfo{}
}

func (p *UserInfo) InitDefault() {
}

func (p *UserInfo) GetUserId() (v string) {
	return p.UserId
}

func (p *UserInfo) GetRealName() (v string) {
	return p.RealName
}

func (p *UserInfo) GetIdCard() (v string) {
	return p.IdCard
}

func (p *UserInfo) GetPhone() (v string) {
	return p.Phone
}

func (p *UserInfo) GetUserLevel() (v string) {
	return p.UserLevel
}

func (p *UserInfo) GetRealNameVerified() (v string) {
	return p.RealNameVerified
}

func (p *UserInfo) GetStatus() (v string) {
	return p.Status
}
func (p *UserInfo) SetUserId(val string) {
	p.UserId = val
}
func (p *UserInfo) SetRealName(val string) {
	p.RealName = val
}
func (p *UserInfo) SetIdCard(val string) {
	p.IdCard = val
}
func (p *UserInfo) SetPhone(val string) {
	p.Phone = val
}
func (p *UserInfo) SetUserLevel(val string) {
	p.UserLevel = val
}
func (p *UserInfo) SetRealNameVerified(val string) {
	p.RealNameVerified = val
}
func (p *UserInfo) SetStatus(val string) {
	p.Status = val
}

func (p *UserInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserInfo(%+v)", *p)
}

var fieldIDToName_UserInfo = map[int16]string{
	1: "user_id",
	2: "real_name",
	3: "id_card",
	4: "phone",
	5: "user_level",
	6: "real_name_verified",
	7: "status",
}

type GetUserInfoReq struct {
	UserId string `thrift:"user_id,1" frugal:"1,default,string" json:"user_id"`
}

func NewGetUserInfoReq() *GetUserInfoReq {
	return &GetUserInfoReq{}
}

func (p *GetUserInfoReq) InitDefault() {
}

func (p *GetUserInfoReq) GetUserId() (v string) {
	return p.UserId
}
func (p *GetUserInfoReq) SetUserId(val string) {
	p.UserId = val
}

func (p *GetUserInfoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserInfoReq(%+v)", *p)
}

var fieldIDToName_GetUserInfoReq = map[int16]string{
	1: "user_id",
}

type GetUserInfoResp struct {
	BaseResp *common.BaseResp `thrift:"base_resp,1" frugal:"1,default,common.BaseResp" json:"base_resp"`
	UserInfo *UserInfo        `thrift:"user_info,2,optional" frugal:"2,optional,UserInfo" json:"user_info,omitempty"`
}

func NewGetUserInfoResp() *GetUserInfoResp {
	return &GetUserInfoResp{}
}

func (p *GetUserInfoResp) InitDefault() {
}

var GetUserInfoResp_BaseResp_DEFAULT *common.BaseResp

func (p *GetUserInfoResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetUserInfoResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

var GetUserInfoResp_UserInfo_DEFAULT *UserInfo

func (p *GetUserInfoResp) GetUserInfo() (v *UserInfo) {
	if !p.IsSetUserInfo() {
		return GetUserInfoResp_UserInfo_DEFAULT
	}
	return p.UserInfo
}
func (p *GetUserInfoResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *GetUserInfoResp) SetUserInfo(val *UserInfo) {
	p.UserInfo = val
}

func (p *GetUserInfoResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetUserInfoResp) IsSetUserInfo() bool {
	return p.UserInfo != nil
}

func (p *GetUserInfoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserInfoResp(%+v)", *p)
}

var fieldIDToName_GetUserInfoResp = map[int16]string{
	1: "base_resp",
	2: "user_info",
}

type RegisterReq struct {
	UserName string `thrift:"user_name,1" frugal:"1,default,string" json:"user_name"`
	Password string `thrift:"password,2" frugal:"2,default,string" json:"password"`
	Phone    string `thrift:"phone,3" frugal:"3,default,string" json:"phone"`
}

func NewRegisterReq() *RegisterReq {
	return &RegisterReq{}
}

func (p *RegisterReq) InitDefault() {
}

func (p *RegisterReq) GetUserName() (v string) {
	return p.UserName
}

func (p *RegisterReq) GetPassword() (v string) {
	return p.Password
}

func (p *RegisterReq) GetPhone() (v string) {
	return p.Phone
}
func (p *RegisterReq) SetUserName(val string) {
	p.UserName = val
}
func (p *RegisterReq) SetPassword(val string) {
	p.Password = val
}
func (p *RegisterReq) SetPhone(val string) {
	p.Phone = val
}

func (p *RegisterReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterReq(%+v)", *p)
}

var fieldIDToName_RegisterReq = map[int16]string{
	1: "user_name",
	2: "password",
	3: "phone",
}

type RegisterResp struct {
	BaseResp *common.BaseResp `thrift:"base_resp,1" frugal:"1,default,common.BaseResp" json:"base_resp"`
	UserId   string           `thrift:"user_id,2" frugal:"2,default,string" json:"user_id"`
}

func NewRegisterResp() *RegisterResp {
	return &RegisterResp{}
}

func (p *RegisterResp) InitDefault() {
}

var RegisterResp_BaseResp_DEFAULT *common.BaseResp

func (p *RegisterResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return RegisterResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *RegisterResp) GetUserId() (v string) {
	return p.UserId
}
func (p *RegisterResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *RegisterResp) SetUserId(val string) {
	p.UserId = val
}

func (p *RegisterResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *RegisterResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterResp(%+v)", *p)
}

var fieldIDToName_RegisterResp = map[int16]string{
	1: "base_resp",
	2: "user_id",
}

type LoginReq struct {
	Phone    string `thrift:"phone,1" frugal:"1,default,string" json:"phone"`
	Password string `thrift:"password,2" frugal:"2,default,string" json:"password"`
}

func NewLoginReq() *LoginReq {
	return &LoginReq{}
}

func (p *LoginReq) InitDefault() {
}

func (p *LoginReq) GetPhone() (v string) {
	return p.Phone
}

func (p *LoginReq) GetPassword() (v string) {
	return p.Password
}
func (p *LoginReq) SetPhone(val string) {
	p.Phone = val
}
func (p *LoginReq) SetPassword(val string) {
	p.Password = val
}

func (p *LoginReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginReq(%+v)", *p)
}

var fieldIDToName_LoginReq = map[int16]string{
	1: "phone",
	2: "password",
}

type LoginResp struct {
	BaseResp *common.BaseResp `thrift:"base_resp,1" frugal:"1,default,common.BaseResp" json:"base_resp"`
	UserId   string           `thrift:"user_id,2" frugal:"2,default,string" json:"user_id"`
	Token    string           `thrift:"token,3" frugal:"3,default,string" json:"token"`
	UserInfo *UserInfo        `thrift:"user_info,4" frugal:"4,default,UserInfo" json:"user_info"`
}

func NewLoginResp() *LoginResp {
	return &LoginResp{}
}

func (p *LoginResp) InitDefault() {
}

var LoginResp_BaseResp_DEFAULT *common.BaseResp

func (p *LoginResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return LoginResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *LoginResp) GetUserId() (v string) {
	return p.UserId
}

func (p *LoginResp) GetToken() (v string) {
	return p.Token
}

var LoginResp_UserInfo_DEFAULT *UserInfo

func (p *LoginResp) GetUserInfo() (v *UserInfo) {
	if !p.IsSetUserInfo() {
		return LoginResp_UserInfo_DEFAULT
	}
	return p.UserInfo
}
func (p *LoginResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *LoginResp) SetUserId(val string) {
	p.UserId = val
}
func (p *LoginResp) SetToken(val string) {
	p.Token = val
}
func (p *LoginResp) SetUserInfo(val *UserInfo) {
	p.UserInfo = val
}

func (p *LoginResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *LoginResp) IsSetUserInfo() bool {
	return p.UserInfo != nil
}

func (p *LoginResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginResp(%+v)", *p)
}

var fieldIDToName_LoginResp = map[int16]string{
	1: "base_resp",
	2: "user_id",
	3: "token",
	4: "user_info",
}

type UserService interface {
	Register(ctx context.Context, req *RegisterReq) (r *RegisterResp, err error)

	Login(ctx context.Context, req *LoginReq) (r *LoginResp, err error)

	VerifyRealName(ctx context.Context, req *VerifyRealNameReq) (r *common.BaseResp, err error)

	GetUserInfo(ctx context.Context, req *GetUserInfoReq) (r *GetUserInfoResp, err error)
}

type UserServiceRegisterArgs struct {
	Req *RegisterReq `thrift:"req,1" frugal:"1,default,RegisterReq" json:"req"`
}

func NewUserServiceRegisterArgs() *UserServiceRegisterArgs {
	return &UserServiceRegisterArgs{}
}

func (p *UserServiceRegisterArgs) InitDefault() {
}

var UserServiceRegisterArgs_Req_DEFAULT *RegisterReq

func (p *UserServiceRegisterArgs) GetReq() (v *RegisterReq) {
	if !p.IsSetReq() {
		return UserServiceRegisterArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceRegisterArgs) SetReq(val *RegisterReq) {
	p.Req = val
}

func (p *UserServiceRegisterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceRegisterArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRegisterArgs(%+v)", *p)
}

var fieldIDToName_UserServiceRegisterArgs = map[int16]string{
	1: "req",
}

type UserServiceRegisterResult struct {
	Success *RegisterResp `thrift:"success,0,optional" frugal:"0,optional,RegisterResp" json:"success,omitempty"`
}

func NewUserServiceRegisterResult() *UserServiceRegisterResult {
	return &UserServiceRegisterResult{}
}

func (p *UserServiceRegisterResult) InitDefault() {
}

var UserServiceRegisterResult_Success_DEFAULT *RegisterResp

func (p *UserServiceRegisterResult) GetSuccess() (v *RegisterResp) {
	if !p.IsSetSuccess() {
		return UserServiceRegisterResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceRegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*RegisterResp)
}

func (p *UserServiceRegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceRegisterResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRegisterResult(%+v)", *p)
}

var fieldIDToName_UserServiceRegisterResult = map[int16]string{
	0: "success",
}

type UserServiceLoginArgs struct {
	Req *LoginReq `thrift:"req,1" frugal:"1,default,LoginReq" json:"req"`
}

func NewUserServiceLoginArgs() *UserServiceLoginArgs {
	return &UserServiceLoginArgs{}
}

func (p *UserServiceLoginArgs) InitDefault() {
}

var UserServiceLoginArgs_Req_DEFAULT *LoginReq

func (p *UserServiceLoginArgs) GetReq() (v *LoginReq) {
	if !p.IsSetReq() {
		return UserServiceLoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceLoginArgs) SetReq(val *LoginReq) {
	p.Req = val
}

func (p *UserServiceLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLoginArgs(%+v)", *p)
}

var fieldIDToName_UserServiceLoginArgs = map[int16]string{
	1: "req",
}

type UserServiceLoginResult struct {
	Success *LoginResp `thrift:"success,0,optional" frugal:"0,optional,LoginResp" json:"success,omitempty"`
}

func NewUserServiceLoginResult() *UserServiceLoginResult {
	return &UserServiceLoginResult{}
}

func (p *UserServiceLoginResult) InitDefault() {
}

var UserServiceLoginResult_Success_DEFAULT *LoginResp

func (p *UserServiceLoginResult) GetSuccess() (v *LoginResp) {
	if !p.IsSetSuccess() {
		return UserServiceLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*LoginResp)
}

func (p *UserServiceLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLoginResult(%+v)", *p)
}

var fieldIDToName_UserServiceLoginResult = map[int16]string{
	0: "success",
}

type UserServiceVerifyRealNameArgs struct {
	Req *VerifyRealNameReq `thrift:"req,1" frugal:"1,default,VerifyRealNameReq" json:"req"`
}

func NewUserServiceVerifyRealNameArgs() *UserServiceVerifyRealNameArgs {
	return &UserServiceVerifyRealNameArgs{}
}

func (p *UserServiceVerifyRealNameArgs) InitDefault() {
}

var UserServiceVerifyRealNameArgs_Req_DEFAULT *VerifyRealNameReq

func (p *UserServiceVerifyRealNameArgs) GetReq() (v *VerifyRealNameReq) {
	if !p.IsSetReq() {
		return UserServiceVerifyRealNameArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceVerifyRealNameArgs) SetReq(val *VerifyRealNameReq) {
	p.Req = val
}

func (p *UserServiceVerifyRealNameArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceVerifyRealNameArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceVerifyRealNameArgs(%+v)", *p)
}

var fieldIDToName_UserServiceVerifyRealNameArgs = map[int16]string{
	1: "req",
}

type UserServiceVerifyRealNameResult struct {
	Success *common.BaseResp `thrift:"success,0,optional" frugal:"0,optional,common.BaseResp" json:"success,omitempty"`
}

func NewUserServiceVerifyRealNameResult() *UserServiceVerifyRealNameResult {
	return &UserServiceVerifyRealNameResult{}
}

func (p *UserServiceVerifyRealNameResult) InitDefault() {
}

var UserServiceVerifyRealNameResult_Success_DEFAULT *common.BaseResp

func (p *UserServiceVerifyRealNameResult) GetSuccess() (v *common.BaseResp) {
	if !p.IsSetSuccess() {
		return UserServiceVerifyRealNameResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceVerifyRealNameResult) SetSuccess(x interface{}) {
	p.Success = x.(*common.BaseResp)
}

func (p *UserServiceVerifyRealNameResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceVerifyRealNameResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceVerifyRealNameResult(%+v)", *p)
}

var fieldIDToName_UserServiceVerifyRealNameResult = map[int16]string{
	0: "success",
}

type UserServiceGetUserInfoArgs struct {
	Req *GetUserInfoReq `thrift:"req,1" frugal:"1,default,GetUserInfoReq" json:"req"`
}

func NewUserServiceGetUserInfoArgs() *UserServiceGetUserInfoArgs {
	return &UserServiceGetUserInfoArgs{}
}

func (p *UserServiceGetUserInfoArgs) InitDefault() {
}

var UserServiceGetUserInfoArgs_Req_DEFAULT *GetUserInfoReq

func (p *UserServiceGetUserInfoArgs) GetReq() (v *GetUserInfoReq) {
	if !p.IsSetReq() {
		return UserServiceGetUserInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceGetUserInfoArgs) SetReq(val *GetUserInfoReq) {
	p.Req = val
}

func (p *UserServiceGetUserInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceGetUserInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserInfoArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserInfoArgs = map[int16]string{
	1: "req",
}

type UserServiceGetUserInfoResult struct {
	Success *GetUserInfoResp `thrift:"success,0,optional" frugal:"0,optional,GetUserInfoResp" json:"success,omitempty"`
}

func NewUserServiceGetUserInfoResult() *UserServiceGetUserInfoResult {
	return &UserServiceGetUserInfoResult{}
}

func (p *UserServiceGetUserInfoResult) InitDefault() {
}

var UserServiceGetUserInfoResult_Success_DEFAULT *GetUserInfoResp

func (p *UserServiceGetUserInfoResult) GetSuccess() (v *GetUserInfoResp) {
	if !p.IsSetSuccess() {
		return UserServiceGetUserInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetUserInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUserInfoResp)
}

func (p *UserServiceGetUserInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetUserInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserInfoResult(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserInfoResult = map[int16]string{
	0: "success",
}
