// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package user

import (
	"context"
	"fmt"
)

type BaseResp struct {
	Code int32  `thrift:"code,1" frugal:"1,default,i32" json:"code"`
	Msg  string `thrift:"msg,2" frugal:"2,default,string" json:"msg"`
}

func NewBaseResp() *BaseResp {
	return &BaseResp{}
}

func (p *BaseResp) InitDefault() {
}

func (p *BaseResp) GetCode() (v int32) {
	return p.Code
}

func (p *BaseResp) GetMsg() (v string) {
	return p.Msg
}
func (p *BaseResp) SetCode(val int32) {
	p.Code = val
}
func (p *BaseResp) SetMsg(val string) {
	p.Msg = val
}

func (p *BaseResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BaseResp(%+v)", *p)
}

var fieldIDToName_BaseResp = map[int16]string{
	1: "code",
	2: "msg",
}

type VerifyRealNameReq struct {
	UserId   string `thrift:"user_id,1" frugal:"1,default,string" json:"user_id"`
	RealName string `thrift:"real_name,2" frugal:"2,default,string" json:"real_name"`
	IdCard   string `thrift:"id_card,3" frugal:"3,default,string" json:"id_card"`
	Phone    string `thrift:"phone,4" frugal:"4,default,string" json:"phone"`
}

func NewVerifyRealNameReq() *VerifyRealNameReq {
	return &VerifyRealNameReq{}
}

func (p *VerifyRealNameReq) InitDefault() {
}

func (p *VerifyRealNameReq) GetUserId() (v string) {
	return p.UserId
}

func (p *VerifyRealNameReq) GetRealName() (v string) {
	return p.RealName
}

func (p *VerifyRealNameReq) GetIdCard() (v string) {
	return p.IdCard
}

func (p *VerifyRealNameReq) GetPhone() (v string) {
	return p.Phone
}
func (p *VerifyRealNameReq) SetUserId(val string) {
	p.UserId = val
}
func (p *VerifyRealNameReq) SetRealName(val string) {
	p.RealName = val
}
func (p *VerifyRealNameReq) SetIdCard(val string) {
	p.IdCard = val
}
func (p *VerifyRealNameReq) SetPhone(val string) {
	p.Phone = val
}

func (p *VerifyRealNameReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerifyRealNameReq(%+v)", *p)
}

var fieldIDToName_VerifyRealNameReq = map[int16]string{
	1: "user_id",
	2: "real_name",
	3: "id_card",
	4: "phone",
}

type UserInfo struct {
	UserId           string `thrift:"user_id,1" frugal:"1,default,string" json:"user_id"`
	RealName         string `thrift:"real_name,2" frugal:"2,default,string" json:"real_name"`
	IdCard           string `thrift:"id_card,3" frugal:"3,default,string" json:"id_card"`
	Phone            string `thrift:"phone,4" frugal:"4,default,string" json:"phone"`
	UserLevel        string `thrift:"user_level,5" frugal:"5,default,string" json:"user_level"`
	RealNameVerified string `thrift:"real_name_verified,6" frugal:"6,default,string" json:"real_name_verified"`
	Status           string `thrift:"status,7" frugal:"7,default,string" json:"status"`
}

func NewUserInfo() *UserInfo {
	return &UserInfo{}
}

func (p *UserInfo) InitDefault() {
}

func (p *UserInfo) GetUserId() (v string) {
	return p.UserId
}

func (p *UserInfo) GetRealName() (v string) {
	return p.RealName
}

func (p *UserInfo) GetIdCard() (v string) {
	return p.IdCard
}

func (p *UserInfo) GetPhone() (v string) {
	return p.Phone
}

func (p *UserInfo) GetUserLevel() (v string) {
	return p.UserLevel
}

func (p *UserInfo) GetRealNameVerified() (v string) {
	return p.RealNameVerified
}

func (p *UserInfo) GetStatus() (v string) {
	return p.Status
}
func (p *UserInfo) SetUserId(val string) {
	p.UserId = val
}
func (p *UserInfo) SetRealName(val string) {
	p.RealName = val
}
func (p *UserInfo) SetIdCard(val string) {
	p.IdCard = val
}
func (p *UserInfo) SetPhone(val string) {
	p.Phone = val
}
func (p *UserInfo) SetUserLevel(val string) {
	p.UserLevel = val
}
func (p *UserInfo) SetRealNameVerified(val string) {
	p.RealNameVerified = val
}
func (p *UserInfo) SetStatus(val string) {
	p.Status = val
}

func (p *UserInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserInfo(%+v)", *p)
}

var fieldIDToName_UserInfo = map[int16]string{
	1: "user_id",
	2: "real_name",
	3: "id_card",
	4: "phone",
	5: "user_level",
	6: "real_name_verified",
	7: "status",
}

type GetUserInfoReq struct {
	UserId string `thrift:"user_id,1" frugal:"1,default,string" json:"user_id"`
}

func NewGetUserInfoReq() *GetUserInfoReq {
	return &GetUserInfoReq{}
}

func (p *GetUserInfoReq) InitDefault() {
}

func (p *GetUserInfoReq) GetUserId() (v string) {
	return p.UserId
}
func (p *GetUserInfoReq) SetUserId(val string) {
	p.UserId = val
}

func (p *GetUserInfoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserInfoReq(%+v)", *p)
}

var fieldIDToName_GetUserInfoReq = map[int16]string{
	1: "user_id",
}

type GetUserInfoResp struct {
	BaseResp *BaseResp `thrift:"base_resp,1" frugal:"1,default,BaseResp" json:"base_resp"`
	UserInfo *UserInfo `thrift:"user_info,2,optional" frugal:"2,optional,UserInfo" json:"user_info,omitempty"`
}

func NewGetUserInfoResp() *GetUserInfoResp {
	return &GetUserInfoResp{}
}

func (p *GetUserInfoResp) InitDefault() {
}

var GetUserInfoResp_BaseResp_DEFAULT *BaseResp

func (p *GetUserInfoResp) GetBaseResp() (v *BaseResp) {
	if !p.IsSetBaseResp() {
		return GetUserInfoResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

var GetUserInfoResp_UserInfo_DEFAULT *UserInfo

func (p *GetUserInfoResp) GetUserInfo() (v *UserInfo) {
	if !p.IsSetUserInfo() {
		return GetUserInfoResp_UserInfo_DEFAULT
	}
	return p.UserInfo
}
func (p *GetUserInfoResp) SetBaseResp(val *BaseResp) {
	p.BaseResp = val
}
func (p *GetUserInfoResp) SetUserInfo(val *UserInfo) {
	p.UserInfo = val
}

func (p *GetUserInfoResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetUserInfoResp) IsSetUserInfo() bool {
	return p.UserInfo != nil
}

func (p *GetUserInfoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserInfoResp(%+v)", *p)
}

var fieldIDToName_GetUserInfoResp = map[int16]string{
	1: "base_resp",
	2: "user_info",
}

type RegisterReq struct {
	UserName string `thrift:"user_name,1" frugal:"1,default,string" json:"user_name"`
	Password string `thrift:"password,2" frugal:"2,default,string" json:"password"`
	Phone    string `thrift:"phone,3" frugal:"3,default,string" json:"phone"`
}

func NewRegisterReq() *RegisterReq {
	return &RegisterReq{}
}

func (p *RegisterReq) InitDefault() {
}

func (p *RegisterReq) GetUserName() (v string) {
	return p.UserName
}

func (p *RegisterReq) GetPassword() (v string) {
	return p.Password
}

func (p *RegisterReq) GetPhone() (v string) {
	return p.Phone
}
func (p *RegisterReq) SetUserName(val string) {
	p.UserName = val
}
func (p *RegisterReq) SetPassword(val string) {
	p.Password = val
}
func (p *RegisterReq) SetPhone(val string) {
	p.Phone = val
}

func (p *RegisterReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterReq(%+v)", *p)
}

var fieldIDToName_RegisterReq = map[int16]string{
	1: "user_name",
	2: "password",
	3: "phone",
}

type RegisterResp struct {
	BaseResp *BaseResp `thrift:"base_resp,1" frugal:"1,default,BaseResp" json:"base_resp"`
	UserId   string    `thrift:"user_id,2" frugal:"2,default,string" json:"user_id"`
}

func NewRegisterResp() *RegisterResp {
	return &RegisterResp{}
}

func (p *RegisterResp) InitDefault() {
}

var RegisterResp_BaseResp_DEFAULT *BaseResp

func (p *RegisterResp) GetBaseResp() (v *BaseResp) {
	if !p.IsSetBaseResp() {
		return RegisterResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *RegisterResp) GetUserId() (v string) {
	return p.UserId
}
func (p *RegisterResp) SetBaseResp(val *BaseResp) {
	p.BaseResp = val
}
func (p *RegisterResp) SetUserId(val string) {
	p.UserId = val
}

func (p *RegisterResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *RegisterResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterResp(%+v)", *p)
}

var fieldIDToName_RegisterResp = map[int16]string{
	1: "base_resp",
	2: "user_id",
}

type LoginReq struct {
	Phone    string `thrift:"phone,1" frugal:"1,default,string" json:"phone"`
	Password string `thrift:"password,2" frugal:"2,default,string" json:"password"`
}

func NewLoginReq() *LoginReq {
	return &LoginReq{}
}

func (p *LoginReq) InitDefault() {
}

func (p *LoginReq) GetPhone() (v string) {
	return p.Phone
}

func (p *LoginReq) GetPassword() (v string) {
	return p.Password
}
func (p *LoginReq) SetPhone(val string) {
	p.Phone = val
}
func (p *LoginReq) SetPassword(val string) {
	p.Password = val
}

func (p *LoginReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginReq(%+v)", *p)
}

var fieldIDToName_LoginReq = map[int16]string{
	1: "phone",
	2: "password",
}

type LoginResp struct {
	BaseResp *BaseResp `thrift:"base_resp,1" frugal:"1,default,BaseResp" json:"base_resp"`
	UserId   string    `thrift:"user_id,2" frugal:"2,default,string" json:"user_id"`
	Token    string    `thrift:"token,3" frugal:"3,default,string" json:"token"`
	UserInfo *UserInfo `thrift:"user_info,4" frugal:"4,default,UserInfo" json:"user_info"`
}

func NewLoginResp() *LoginResp {
	return &LoginResp{}
}

func (p *LoginResp) InitDefault() {
}

var LoginResp_BaseResp_DEFAULT *BaseResp

func (p *LoginResp) GetBaseResp() (v *BaseResp) {
	if !p.IsSetBaseResp() {
		return LoginResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *LoginResp) GetUserId() (v string) {
	return p.UserId
}

func (p *LoginResp) GetToken() (v string) {
	return p.Token
}

var LoginResp_UserInfo_DEFAULT *UserInfo

func (p *LoginResp) GetUserInfo() (v *UserInfo) {
	if !p.IsSetUserInfo() {
		return LoginResp_UserInfo_DEFAULT
	}
	return p.UserInfo
}
func (p *LoginResp) SetBaseResp(val *BaseResp) {
	p.BaseResp = val
}
func (p *LoginResp) SetUserId(val string) {
	p.UserId = val
}
func (p *LoginResp) SetToken(val string) {
	p.Token = val
}
func (p *LoginResp) SetUserInfo(val *UserInfo) {
	p.UserInfo = val
}

func (p *LoginResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *LoginResp) IsSetUserInfo() bool {
	return p.UserInfo != nil
}

func (p *LoginResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginResp(%+v)", *p)
}

var fieldIDToName_LoginResp = map[int16]string{
	1: "base_resp",
	2: "user_id",
	3: "token",
	4: "user_info",
}

type OrderSeatInfo struct {
	SeatId      string  `thrift:"seat_id,1" frugal:"1,default,string" json:"seat_id"`
	SeatType    string  `thrift:"seat_type,2" frugal:"2,default,string" json:"seat_type"`
	CarriageNum string  `thrift:"carriage_num,3" frugal:"3,default,string" json:"carriage_num"`
	SeatNum     string  `thrift:"seat_num,4" frugal:"4,default,string" json:"seat_num"`
	SeatPrice   float64 `thrift:"seat_price,5" frugal:"5,default,double" json:"seat_price"`
}

func NewOrderSeatInfo() *OrderSeatInfo {
	return &OrderSeatInfo{}
}

func (p *OrderSeatInfo) InitDefault() {
}

func (p *OrderSeatInfo) GetSeatId() (v string) {
	return p.SeatId
}

func (p *OrderSeatInfo) GetSeatType() (v string) {
	return p.SeatType
}

func (p *OrderSeatInfo) GetCarriageNum() (v string) {
	return p.CarriageNum
}

func (p *OrderSeatInfo) GetSeatNum() (v string) {
	return p.SeatNum
}

func (p *OrderSeatInfo) GetSeatPrice() (v float64) {
	return p.SeatPrice
}
func (p *OrderSeatInfo) SetSeatId(val string) {
	p.SeatId = val
}
func (p *OrderSeatInfo) SetSeatType(val string) {
	p.SeatType = val
}
func (p *OrderSeatInfo) SetCarriageNum(val string) {
	p.CarriageNum = val
}
func (p *OrderSeatInfo) SetSeatNum(val string) {
	p.SeatNum = val
}
func (p *OrderSeatInfo) SetSeatPrice(val float64) {
	p.SeatPrice = val
}

func (p *OrderSeatInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderSeatInfo(%+v)", *p)
}

var fieldIDToName_OrderSeatInfo = map[int16]string{
	1: "seat_id",
	2: "seat_type",
	3: "carriage_num",
	4: "seat_num",
	5: "seat_price",
}

type CreateOrderPassenger struct {
	RealName string `thrift:"real_name,1" frugal:"1,default,string" json:"real_name"`
	IdCard   string `thrift:"id_card,2" frugal:"2,default,string" json:"id_card"`
	SeatType string `thrift:"seat_type,3" frugal:"3,default,string" json:"seat_type"`
}

func NewCreateOrderPassenger() *CreateOrderPassenger {
	return &CreateOrderPassenger{}
}

func (p *CreateOrderPassenger) InitDefault() {
}

func (p *CreateOrderPassenger) GetRealName() (v string) {
	return p.RealName
}

func (p *CreateOrderPassenger) GetIdCard() (v string) {
	return p.IdCard
}

func (p *CreateOrderPassenger) GetSeatType() (v string) {
	return p.SeatType
}
func (p *CreateOrderPassenger) SetRealName(val string) {
	p.RealName = val
}
func (p *CreateOrderPassenger) SetIdCard(val string) {
	p.IdCard = val
}
func (p *CreateOrderPassenger) SetSeatType(val string) {
	p.SeatType = val
}

func (p *CreateOrderPassenger) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateOrderPassenger(%+v)", *p)
}

var fieldIDToName_CreateOrderPassenger = map[int16]string{
	1: "real_name",
	2: "id_card",
	3: "seat_type",
}

type CreateOrderReq struct {
	UserId           string                  `thrift:"user_id,1" frugal:"1,default,string" json:"user_id"`
	TrainId          string                  `thrift:"train_id,2" frugal:"2,default,string" json:"train_id"`
	DepartureStation string                  `thrift:"departure_station,3" frugal:"3,default,string" json:"departure_station"`
	ArrivalStation   string                  `thrift:"arrival_station,4" frugal:"4,default,string" json:"arrival_station"`
	Passengers       []*CreateOrderPassenger `thrift:"passengers,5" frugal:"5,default,list<CreateOrderPassenger>" json:"passengers"`
}

func NewCreateOrderReq() *CreateOrderReq {
	return &CreateOrderReq{}
}

func (p *CreateOrderReq) InitDefault() {
}

func (p *CreateOrderReq) GetUserId() (v string) {
	return p.UserId
}

func (p *CreateOrderReq) GetTrainId() (v string) {
	return p.TrainId
}

func (p *CreateOrderReq) GetDepartureStation() (v string) {
	return p.DepartureStation
}

func (p *CreateOrderReq) GetArrivalStation() (v string) {
	return p.ArrivalStation
}

func (p *CreateOrderReq) GetPassengers() (v []*CreateOrderPassenger) {
	return p.Passengers
}
func (p *CreateOrderReq) SetUserId(val string) {
	p.UserId = val
}
func (p *CreateOrderReq) SetTrainId(val string) {
	p.TrainId = val
}
func (p *CreateOrderReq) SetDepartureStation(val string) {
	p.DepartureStation = val
}
func (p *CreateOrderReq) SetArrivalStation(val string) {
	p.ArrivalStation = val
}
func (p *CreateOrderReq) SetPassengers(val []*CreateOrderPassenger) {
	p.Passengers = val
}

func (p *CreateOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateOrderReq(%+v)", *p)
}

var fieldIDToName_CreateOrderReq = map[int16]string{
	1: "user_id",
	2: "train_id",
	3: "departure_station",
	4: "arrival_station",
	5: "passengers",
}

type CreateOrderResp struct {
	BaseResp        *BaseResp        `thrift:"base_resp,1" frugal:"1,default,BaseResp" json:"base_resp"`
	OrderId         string           `thrift:"order_id,2" frugal:"2,default,string" json:"order_id"`
	PayDeadlineUnix int64            `thrift:"pay_deadline_unix,3" frugal:"3,default,i64" json:"pay_deadline_unix"`
	Seats           []*OrderSeatInfo `thrift:"seats,4" frugal:"4,default,list<OrderSeatInfo>" json:"seats"`
}

func NewCreateOrderResp() *CreateOrderResp {
	return &CreateOrderResp{}
}

func (p *CreateOrderResp) InitDefault() {
}

var CreateOrderResp_BaseResp_DEFAULT *BaseResp

func (p *CreateOrderResp) GetBaseResp() (v *BaseResp) {
	if !p.IsSetBaseResp() {
		return CreateOrderResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *CreateOrderResp) GetOrderId() (v string) {
	return p.OrderId
}

func (p *CreateOrderResp) GetPayDeadlineUnix() (v int64) {
	return p.PayDeadlineUnix
}

func (p *CreateOrderResp) GetSeats() (v []*OrderSeatInfo) {
	return p.Seats
}
func (p *CreateOrderResp) SetBaseResp(val *BaseResp) {
	p.BaseResp = val
}
func (p *CreateOrderResp) SetOrderId(val string) {
	p.OrderId = val
}
func (p *CreateOrderResp) SetPayDeadlineUnix(val int64) {
	p.PayDeadlineUnix = val
}
func (p *CreateOrderResp) SetSeats(val []*OrderSeatInfo) {
	p.Seats = val
}

func (p *CreateOrderResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *CreateOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateOrderResp(%+v)", *p)
}

var fieldIDToName_CreateOrderResp = map[int16]string{
	1: "base_resp",
	2: "order_id",
	3: "pay_deadline_unix",
	4: "seats",
}

type PayOrderReq struct {
	UserId     string  `thrift:"user_id,1" frugal:"1,default,string" json:"user_id"`
	OrderId    string  `thrift:"order_id,2" frugal:"2,default,string" json:"order_id"`
	PayChannel string  `thrift:"pay_channel,3" frugal:"3,default,string" json:"pay_channel"`
	PayNo      *string `thrift:"pay_no,4,optional" frugal:"4,optional,string" json:"pay_no,omitempty"`
}

func NewPayOrderReq() *PayOrderReq {
	return &PayOrderReq{}
}

func (p *PayOrderReq) InitDefault() {
}

func (p *PayOrderReq) GetUserId() (v string) {
	return p.UserId
}

func (p *PayOrderReq) GetOrderId() (v string) {
	return p.OrderId
}

func (p *PayOrderReq) GetPayChannel() (v string) {
	return p.PayChannel
}

var PayOrderReq_PayNo_DEFAULT string

func (p *PayOrderReq) GetPayNo() (v string) {
	if !p.IsSetPayNo() {
		return PayOrderReq_PayNo_DEFAULT
	}
	return *p.PayNo
}
func (p *PayOrderReq) SetUserId(val string) {
	p.UserId = val
}
func (p *PayOrderReq) SetOrderId(val string) {
	p.OrderId = val
}
func (p *PayOrderReq) SetPayChannel(val string) {
	p.PayChannel = val
}
func (p *PayOrderReq) SetPayNo(val *string) {
	p.PayNo = val
}

func (p *PayOrderReq) IsSetPayNo() bool {
	return p.PayNo != nil
}

func (p *PayOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PayOrderReq(%+v)", *p)
}

var fieldIDToName_PayOrderReq = map[int16]string{
	1: "user_id",
	2: "order_id",
	3: "pay_channel",
	4: "pay_no",
}

type PayOrderResp struct {
	BaseResp    *BaseResp `thrift:"base_resp,1" frugal:"1,default,BaseResp" json:"base_resp"`
	OrderStatus string    `thrift:"order_status,2" frugal:"2,default,string" json:"order_status"`
	PayStatus   string    `thrift:"pay_status,3" frugal:"3,default,string" json:"pay_status"`
	PayNo       *string   `thrift:"pay_no,4,optional" frugal:"4,optional,string" json:"pay_no,omitempty"`
}

func NewPayOrderResp() *PayOrderResp {
	return &PayOrderResp{}
}

func (p *PayOrderResp) InitDefault() {
}

var PayOrderResp_BaseResp_DEFAULT *BaseResp

func (p *PayOrderResp) GetBaseResp() (v *BaseResp) {
	if !p.IsSetBaseResp() {
		return PayOrderResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *PayOrderResp) GetOrderStatus() (v string) {
	return p.OrderStatus
}

func (p *PayOrderResp) GetPayStatus() (v string) {
	return p.PayStatus
}

var PayOrderResp_PayNo_DEFAULT string

func (p *PayOrderResp) GetPayNo() (v string) {
	if !p.IsSetPayNo() {
		return PayOrderResp_PayNo_DEFAULT
	}
	return *p.PayNo
}
func (p *PayOrderResp) SetBaseResp(val *BaseResp) {
	p.BaseResp = val
}
func (p *PayOrderResp) SetOrderStatus(val string) {
	p.OrderStatus = val
}
func (p *PayOrderResp) SetPayStatus(val string) {
	p.PayStatus = val
}
func (p *PayOrderResp) SetPayNo(val *string) {
	p.PayNo = val
}

func (p *PayOrderResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *PayOrderResp) IsSetPayNo() bool {
	return p.PayNo != nil
}

func (p *PayOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PayOrderResp(%+v)", *p)
}

var fieldIDToName_PayOrderResp = map[int16]string{
	1: "base_resp",
	2: "order_status",
	3: "pay_status",
	4: "pay_no",
}

type ConfirmPayReq struct {
	UserId           string  `thrift:"user_id,1" frugal:"1,default,string" json:"user_id"`
	OrderId          string  `thrift:"order_id,2" frugal:"2,default,string" json:"order_id"`
	PayNo            string  `thrift:"pay_no,3" frugal:"3,default,string" json:"pay_no"`
	ThirdPartyStatus *string `thrift:"third_party_status,4,optional" frugal:"4,optional,string" json:"third_party_status,omitempty"`
}

func NewConfirmPayReq() *ConfirmPayReq {
	return &ConfirmPayReq{}
}

func (p *ConfirmPayReq) InitDefault() {
}

func (p *ConfirmPayReq) GetUserId() (v string) {
	return p.UserId
}

func (p *ConfirmPayReq) GetOrderId() (v string) {
	return p.OrderId
}

func (p *ConfirmPayReq) GetPayNo() (v string) {
	return p.PayNo
}

var ConfirmPayReq_ThirdPartyStatus_DEFAULT string

func (p *ConfirmPayReq) GetThirdPartyStatus() (v string) {
	if !p.IsSetThirdPartyStatus() {
		return ConfirmPayReq_ThirdPartyStatus_DEFAULT
	}
	return *p.ThirdPartyStatus
}
func (p *ConfirmPayReq) SetUserId(val string) {
	p.UserId = val
}
func (p *ConfirmPayReq) SetOrderId(val string) {
	p.OrderId = val
}
func (p *ConfirmPayReq) SetPayNo(val string) {
	p.PayNo = val
}
func (p *ConfirmPayReq) SetThirdPartyStatus(val *string) {
	p.ThirdPartyStatus = val
}

func (p *ConfirmPayReq) IsSetThirdPartyStatus() bool {
	return p.ThirdPartyStatus != nil
}

func (p *ConfirmPayReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ConfirmPayReq(%+v)", *p)
}

var fieldIDToName_ConfirmPayReq = map[int16]string{
	1: "user_id",
	2: "order_id",
	3: "pay_no",
	4: "third_party_status",
}

type ConfirmPayResp struct {
	BaseResp    *BaseResp `thrift:"base_resp,1" frugal:"1,default,BaseResp" json:"base_resp"`
	OrderStatus string    `thrift:"order_status,2" frugal:"2,default,string" json:"order_status"`
}

func NewConfirmPayResp() *ConfirmPayResp {
	return &ConfirmPayResp{}
}

func (p *ConfirmPayResp) InitDefault() {
}

var ConfirmPayResp_BaseResp_DEFAULT *BaseResp

func (p *ConfirmPayResp) GetBaseResp() (v *BaseResp) {
	if !p.IsSetBaseResp() {
		return ConfirmPayResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *ConfirmPayResp) GetOrderStatus() (v string) {
	return p.OrderStatus
}
func (p *ConfirmPayResp) SetBaseResp(val *BaseResp) {
	p.BaseResp = val
}
func (p *ConfirmPayResp) SetOrderStatus(val string) {
	p.OrderStatus = val
}

func (p *ConfirmPayResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *ConfirmPayResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ConfirmPayResp(%+v)", *p)
}

var fieldIDToName_ConfirmPayResp = map[int16]string{
	1: "base_resp",
	2: "order_status",
}

type ChangeOrderReq struct {
	UserId               string `thrift:"user_id,1" frugal:"1,default,string" json:"user_id"`
	OrderId              string `thrift:"order_id,2" frugal:"2,default,string" json:"order_id"`
	NewTrainId_          string `thrift:"new_train_id,3" frugal:"3,default,string" json:"new_train_id"`
	NewDepartureStation_ string `thrift:"new_departure_station,4" frugal:"4,default,string" json:"new_departure_station"`
	NewArrivalStation_   string `thrift:"new_arrival_station,5" frugal:"5,default,string" json:"new_arrival_station"`
}

func NewChangeOrderReq() *ChangeOrderReq {
	return &ChangeOrderReq{}
}

func (p *ChangeOrderReq) InitDefault() {
}

func (p *ChangeOrderReq) GetUserId() (v string) {
	return p.UserId
}

func (p *ChangeOrderReq) GetOrderId() (v string) {
	return p.OrderId
}

func (p *ChangeOrderReq) GetNewTrainId_() (v string) {
	return p.NewTrainId_
}

func (p *ChangeOrderReq) GetNewDepartureStation_() (v string) {
	return p.NewDepartureStation_
}

func (p *ChangeOrderReq) GetNewArrivalStation_() (v string) {
	return p.NewArrivalStation_
}
func (p *ChangeOrderReq) SetUserId(val string) {
	p.UserId = val
}
func (p *ChangeOrderReq) SetOrderId(val string) {
	p.OrderId = val
}
func (p *ChangeOrderReq) SetNewTrainId_(val string) {
	p.NewTrainId_ = val
}
func (p *ChangeOrderReq) SetNewDepartureStation_(val string) {
	p.NewDepartureStation_ = val
}
func (p *ChangeOrderReq) SetNewArrivalStation_(val string) {
	p.NewArrivalStation_ = val
}

func (p *ChangeOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChangeOrderReq(%+v)", *p)
}

var fieldIDToName_ChangeOrderReq = map[int16]string{
	1: "user_id",
	2: "order_id",
	3: "new_train_id",
	4: "new_departure_station",
	5: "new_arrival_station",
}

type ChangeOrderResp struct {
	BaseResp         *BaseResp        `thrift:"base_resp,1" frugal:"1,default,BaseResp" json:"base_resp"`
	OldOrderStatus   string           `thrift:"old_order_status,2" frugal:"2,default,string" json:"old_order_status"`
	NewOrderId_      string           `thrift:"new_order_id,3" frugal:"3,default,string" json:"new_order_id"`
	NewTotalAmount_  float64          `thrift:"new_total_amount,4" frugal:"4,default,double" json:"new_total_amount"`
	RefundDiffAmount float64          `thrift:"refund_diff_amount,5" frugal:"5,default,double" json:"refund_diff_amount"`
	Seats            []*OrderSeatInfo `thrift:"seats,6" frugal:"6,default,list<OrderSeatInfo>" json:"seats"`
}

func NewChangeOrderResp() *ChangeOrderResp {
	return &ChangeOrderResp{}
}

func (p *ChangeOrderResp) InitDefault() {
}

var ChangeOrderResp_BaseResp_DEFAULT *BaseResp

func (p *ChangeOrderResp) GetBaseResp() (v *BaseResp) {
	if !p.IsSetBaseResp() {
		return ChangeOrderResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *ChangeOrderResp) GetOldOrderStatus() (v string) {
	return p.OldOrderStatus
}

func (p *ChangeOrderResp) GetNewOrderId_() (v string) {
	return p.NewOrderId_
}

func (p *ChangeOrderResp) GetNewTotalAmount_() (v float64) {
	return p.NewTotalAmount_
}

func (p *ChangeOrderResp) GetRefundDiffAmount() (v float64) {
	return p.RefundDiffAmount
}

func (p *ChangeOrderResp) GetSeats() (v []*OrderSeatInfo) {
	return p.Seats
}
func (p *ChangeOrderResp) SetBaseResp(val *BaseResp) {
	p.BaseResp = val
}
func (p *ChangeOrderResp) SetOldOrderStatus(val string) {
	p.OldOrderStatus = val
}
func (p *ChangeOrderResp) SetNewOrderId_(val string) {
	p.NewOrderId_ = val
}
func (p *ChangeOrderResp) SetNewTotalAmount_(val float64) {
	p.NewTotalAmount_ = val
}
func (p *ChangeOrderResp) SetRefundDiffAmount(val float64) {
	p.RefundDiffAmount = val
}
func (p *ChangeOrderResp) SetSeats(val []*OrderSeatInfo) {
	p.Seats = val
}

func (p *ChangeOrderResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *ChangeOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChangeOrderResp(%+v)", *p)
}

var fieldIDToName_ChangeOrderResp = map[int16]string{
	1: "base_resp",
	2: "old_order_status",
	3: "new_order_id",
	4: "new_total_amount",
	5: "refund_diff_amount",
	6: "seats",
}

type CancelOrderReq struct {
	UserId  string `thrift:"user_id,1" frugal:"1,default,string" json:"user_id"`
	OrderId string `thrift:"order_id,2" frugal:"2,default,string" json:"order_id"`
}

func NewCancelOrderReq() *CancelOrderReq {
	return &CancelOrderReq{}
}

func (p *CancelOrderReq) InitDefault() {
}

func (p *CancelOrderReq) GetUserId() (v string) {
	return p.UserId
}

func (p *CancelOrderReq) GetOrderId() (v string) {
	return p.OrderId
}
func (p *CancelOrderReq) SetUserId(val string) {
	p.UserId = val
}
func (p *CancelOrderReq) SetOrderId(val string) {
	p.OrderId = val
}

func (p *CancelOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CancelOrderReq(%+v)", *p)
}

var fieldIDToName_CancelOrderReq = map[int16]string{
	1: "user_id",
	2: "order_id",
}

type RefundOrderReq struct {
	UserId  string  `thrift:"user_id,1" frugal:"1,default,string" json:"user_id"`
	OrderId string  `thrift:"order_id,2" frugal:"2,default,string" json:"order_id"`
	Reason  *string `thrift:"reason,3,optional" frugal:"3,optional,string" json:"reason,omitempty"`
}

func NewRefundOrderReq() *RefundOrderReq {
	return &RefundOrderReq{}
}

func (p *RefundOrderReq) InitDefault() {
}

func (p *RefundOrderReq) GetUserId() (v string) {
	return p.UserId
}

func (p *RefundOrderReq) GetOrderId() (v string) {
	return p.OrderId
}

var RefundOrderReq_Reason_DEFAULT string

func (p *RefundOrderReq) GetReason() (v string) {
	if !p.IsSetReason() {
		return RefundOrderReq_Reason_DEFAULT
	}
	return *p.Reason
}
func (p *RefundOrderReq) SetUserId(val string) {
	p.UserId = val
}
func (p *RefundOrderReq) SetOrderId(val string) {
	p.OrderId = val
}
func (p *RefundOrderReq) SetReason(val *string) {
	p.Reason = val
}

func (p *RefundOrderReq) IsSetReason() bool {
	return p.Reason != nil
}

func (p *RefundOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefundOrderReq(%+v)", *p)
}

var fieldIDToName_RefundOrderReq = map[int16]string{
	1: "user_id",
	2: "order_id",
	3: "reason",
}

type RefundOrderResp struct {
	BaseResp     *BaseResp `thrift:"base_resp,1" frugal:"1,default,BaseResp" json:"base_resp"`
	RefundAmount float64   `thrift:"refund_amount,2" frugal:"2,default,double" json:"refund_amount"`
	RefundStatus string    `thrift:"refund_status,3" frugal:"3,default,string" json:"refund_status"`
	OrderStatus  string    `thrift:"order_status,4" frugal:"4,default,string" json:"order_status"`
}

func NewRefundOrderResp() *RefundOrderResp {
	return &RefundOrderResp{}
}

func (p *RefundOrderResp) InitDefault() {
}

var RefundOrderResp_BaseResp_DEFAULT *BaseResp

func (p *RefundOrderResp) GetBaseResp() (v *BaseResp) {
	if !p.IsSetBaseResp() {
		return RefundOrderResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *RefundOrderResp) GetRefundAmount() (v float64) {
	return p.RefundAmount
}

func (p *RefundOrderResp) GetRefundStatus() (v string) {
	return p.RefundStatus
}

func (p *RefundOrderResp) GetOrderStatus() (v string) {
	return p.OrderStatus
}
func (p *RefundOrderResp) SetBaseResp(val *BaseResp) {
	p.BaseResp = val
}
func (p *RefundOrderResp) SetRefundAmount(val float64) {
	p.RefundAmount = val
}
func (p *RefundOrderResp) SetRefundStatus(val string) {
	p.RefundStatus = val
}
func (p *RefundOrderResp) SetOrderStatus(val string) {
	p.OrderStatus = val
}

func (p *RefundOrderResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *RefundOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefundOrderResp(%+v)", *p)
}

var fieldIDToName_RefundOrderResp = map[int16]string{
	1: "base_resp",
	2: "refund_amount",
	3: "refund_status",
	4: "order_status",
}

type ListOrdersReq struct {
	UserId string  `thrift:"user_id,1" frugal:"1,default,string" json:"user_id"`
	Status *string `thrift:"status,2,optional" frugal:"2,optional,string" json:"status,omitempty"`
	Cursor *string `thrift:"cursor,3,optional" frugal:"3,optional,string" json:"cursor,omitempty"`
	Limit  int32   `thrift:"limit,4" frugal:"4,default,i32" json:"limit"`
}

func NewListOrdersReq() *ListOrdersReq {
	return &ListOrdersReq{}
}

func (p *ListOrdersReq) InitDefault() {
}

func (p *ListOrdersReq) GetUserId() (v string) {
	return p.UserId
}

var ListOrdersReq_Status_DEFAULT string

func (p *ListOrdersReq) GetStatus() (v string) {
	if !p.IsSetStatus() {
		return ListOrdersReq_Status_DEFAULT
	}
	return *p.Status
}

var ListOrdersReq_Cursor_DEFAULT string

func (p *ListOrdersReq) GetCursor() (v string) {
	if !p.IsSetCursor() {
		return ListOrdersReq_Cursor_DEFAULT
	}
	return *p.Cursor
}

func (p *ListOrdersReq) GetLimit() (v int32) {
	return p.Limit
}
func (p *ListOrdersReq) SetUserId(val string) {
	p.UserId = val
}
func (p *ListOrdersReq) SetStatus(val *string) {
	p.Status = val
}
func (p *ListOrdersReq) SetCursor(val *string) {
	p.Cursor = val
}
func (p *ListOrdersReq) SetLimit(val int32) {
	p.Limit = val
}

func (p *ListOrdersReq) IsSetStatus() bool {
	return p.Status != nil
}

func (p *ListOrdersReq) IsSetCursor() bool {
	return p.Cursor != nil
}

func (p *ListOrdersReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListOrdersReq(%+v)", *p)
}

var fieldIDToName_ListOrdersReq = map[int16]string{
	1: "user_id",
	2: "status",
	3: "cursor",
	4: "limit",
}

type ListOrdersResp struct {
	BaseResp   *BaseResp    `thrift:"base_resp,1" frugal:"1,default,BaseResp" json:"base_resp"`
	Orders     []*OrderInfo `thrift:"orders,2" frugal:"2,default,list<OrderInfo>" json:"orders"`
	NextCursor *string      `thrift:"next_cursor,3,optional" frugal:"3,optional,string" json:"next_cursor,omitempty"`
}

func NewListOrdersResp() *ListOrdersResp {
	return &ListOrdersResp{}
}

func (p *ListOrdersResp) InitDefault() {
}

var ListOrdersResp_BaseResp_DEFAULT *BaseResp

func (p *ListOrdersResp) GetBaseResp() (v *BaseResp) {
	if !p.IsSetBaseResp() {
		return ListOrdersResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *ListOrdersResp) GetOrders() (v []*OrderInfo) {
	return p.Orders
}

var ListOrdersResp_NextCursor_DEFAULT string

func (p *ListOrdersResp) GetNextCursor() (v string) {
	if !p.IsSetNextCursor() {
		return ListOrdersResp_NextCursor_DEFAULT
	}
	return *p.NextCursor
}
func (p *ListOrdersResp) SetBaseResp(val *BaseResp) {
	p.BaseResp = val
}
func (p *ListOrdersResp) SetOrders(val []*OrderInfo) {
	p.Orders = val
}
func (p *ListOrdersResp) SetNextCursor(val *string) {
	p.NextCursor = val
}

func (p *ListOrdersResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *ListOrdersResp) IsSetNextCursor() bool {
	return p.NextCursor != nil
}

func (p *ListOrdersResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListOrdersResp(%+v)", *p)
}

var fieldIDToName_ListOrdersResp = map[int16]string{
	1: "base_resp",
	2: "orders",
	3: "next_cursor",
}

type GetOrderReq struct {
	UserId  string `thrift:"user_id,1" frugal:"1,default,string" json:"user_id"`
	OrderId string `thrift:"order_id,2" frugal:"2,default,string" json:"order_id"`
}

func NewGetOrderReq() *GetOrderReq {
	return &GetOrderReq{}
}

func (p *GetOrderReq) InitDefault() {
}

func (p *GetOrderReq) GetUserId() (v string) {
	return p.UserId
}

func (p *GetOrderReq) GetOrderId() (v string) {
	return p.OrderId
}
func (p *GetOrderReq) SetUserId(val string) {
	p.UserId = val
}
func (p *GetOrderReq) SetOrderId(val string) {
	p.OrderId = val
}

func (p *GetOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetOrderReq(%+v)", *p)
}

var fieldIDToName_GetOrderReq = map[int16]string{
	1: "user_id",
	2: "order_id",
}

type OrderInfo struct {
	OrderId          string  `thrift:"order_id,1" frugal:"1,default,string" json:"order_id"`
	UserId           string  `thrift:"user_id,2" frugal:"2,default,string" json:"user_id"`
	TrainId          string  `thrift:"train_id,3" frugal:"3,default,string" json:"train_id"`
	DepartureStation string  `thrift:"departure_station,4" frugal:"4,default,string" json:"departure_station"`
	ArrivalStation   string  `thrift:"arrival_station,5" frugal:"5,default,string" json:"arrival_station"`
	FromSeq          int32   `thrift:"from_seq,6" frugal:"6,default,i32" json:"from_seq"`
	ToSeq            int32   `thrift:"to_seq,7" frugal:"7,default,i32" json:"to_seq"`
	TotalAmount      float64 `thrift:"total_amount,8" frugal:"8,default,double" json:"total_amount"`
	OrderStatus      string  `thrift:"order_status,9" frugal:"9,default,string" json:"order_status"`
	PayDeadlineUnix  int64   `thrift:"pay_deadline_unix,10" frugal:"10,default,i64" json:"pay_deadline_unix"`
	PayTimeUnix      *int64  `thrift:"pay_time_unix,11,optional" frugal:"11,optional,i64" json:"pay_time_unix,omitempty"`
	PayChannel       *string `thrift:"pay_channel,12,optional" frugal:"12,optional,string" json:"pay_channel,omitempty"`
	PayNo            *string `thrift:"pay_no,13,optional" frugal:"13,optional,string" json:"pay_no,omitempty"`
	CreatedAtUnix    int64   `thrift:"created_at_unix,14" frugal:"14,default,i64" json:"created_at_unix"`
}

func NewOrderInfo() *OrderInfo {
	return &OrderInfo{}
}

func (p *OrderInfo) InitDefault() {
}

func (p *OrderInfo) GetOrderId() (v string) {
	return p.OrderId
}

func (p *OrderInfo) GetUserId() (v string) {
	return p.UserId
}

func (p *OrderInfo) GetTrainId() (v string) {
	return p.TrainId
}

func (p *OrderInfo) GetDepartureStation() (v string) {
	return p.DepartureStation
}

func (p *OrderInfo) GetArrivalStation() (v string) {
	return p.ArrivalStation
}

func (p *OrderInfo) GetFromSeq() (v int32) {
	return p.FromSeq
}

func (p *OrderInfo) GetToSeq() (v int32) {
	return p.ToSeq
}

func (p *OrderInfo) GetTotalAmount() (v float64) {
	return p.TotalAmount
}

func (p *OrderInfo) GetOrderStatus() (v string) {
	return p.OrderStatus
}

func (p *OrderInfo) GetPayDeadlineUnix() (v int64) {
	return p.PayDeadlineUnix
}

var OrderInfo_PayTimeUnix_DEFAULT int64

func (p *OrderInfo) GetPayTimeUnix() (v int64) {
	if !p.IsSetPayTimeUnix() {
		return OrderInfo_PayTimeUnix_DEFAULT
	}
	return *p.PayTimeUnix
}

var OrderInfo_PayChannel_DEFAULT string

func (p *OrderInfo) GetPayChannel() (v string) {
	if !p.IsSetPayChannel() {
		return OrderInfo_PayChannel_DEFAULT
	}
	return *p.PayChannel
}

var OrderInfo_PayNo_DEFAULT string

func (p *OrderInfo) GetPayNo() (v string) {
	if !p.IsSetPayNo() {
		return OrderInfo_PayNo_DEFAULT
	}
	return *p.PayNo
}

func (p *OrderInfo) GetCreatedAtUnix() (v int64) {
	return p.CreatedAtUnix
}
func (p *OrderInfo) SetOrderId(val string) {
	p.OrderId = val
}
func (p *OrderInfo) SetUserId(val string) {
	p.UserId = val
}
func (p *OrderInfo) SetTrainId(val string) {
	p.TrainId = val
}
func (p *OrderInfo) SetDepartureStation(val string) {
	p.DepartureStation = val
}
func (p *OrderInfo) SetArrivalStation(val string) {
	p.ArrivalStation = val
}
func (p *OrderInfo) SetFromSeq(val int32) {
	p.FromSeq = val
}
func (p *OrderInfo) SetToSeq(val int32) {
	p.ToSeq = val
}
func (p *OrderInfo) SetTotalAmount(val float64) {
	p.TotalAmount = val
}
func (p *OrderInfo) SetOrderStatus(val string) {
	p.OrderStatus = val
}
func (p *OrderInfo) SetPayDeadlineUnix(val int64) {
	p.PayDeadlineUnix = val
}
func (p *OrderInfo) SetPayTimeUnix(val *int64) {
	p.PayTimeUnix = val
}
func (p *OrderInfo) SetPayChannel(val *string) {
	p.PayChannel = val
}
func (p *OrderInfo) SetPayNo(val *string) {
	p.PayNo = val
}
func (p *OrderInfo) SetCreatedAtUnix(val int64) {
	p.CreatedAtUnix = val
}

func (p *OrderInfo) IsSetPayTimeUnix() bool {
	return p.PayTimeUnix != nil
}

func (p *OrderInfo) IsSetPayChannel() bool {
	return p.PayChannel != nil
}

func (p *OrderInfo) IsSetPayNo() bool {
	return p.PayNo != nil
}

func (p *OrderInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderInfo(%+v)", *p)
}

var fieldIDToName_OrderInfo = map[int16]string{
	1:  "order_id",
	2:  "user_id",
	3:  "train_id",
	4:  "departure_station",
	5:  "arrival_station",
	6:  "from_seq",
	7:  "to_seq",
	8:  "total_amount",
	9:  "order_status",
	10: "pay_deadline_unix",
	11: "pay_time_unix",
	12: "pay_channel",
	13: "pay_no",
	14: "created_at_unix",
}

type GetOrderResp struct {
	BaseResp *BaseResp        `thrift:"base_resp,1" frugal:"1,default,BaseResp" json:"base_resp"`
	Order    *OrderInfo       `thrift:"order,2,optional" frugal:"2,optional,OrderInfo" json:"order,omitempty"`
	Seats    []*OrderSeatInfo `thrift:"seats,3" frugal:"3,default,list<OrderSeatInfo>" json:"seats"`
}

func NewGetOrderResp() *GetOrderResp {
	return &GetOrderResp{}
}

func (p *GetOrderResp) InitDefault() {
}

var GetOrderResp_BaseResp_DEFAULT *BaseResp

func (p *GetOrderResp) GetBaseResp() (v *BaseResp) {
	if !p.IsSetBaseResp() {
		return GetOrderResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

var GetOrderResp_Order_DEFAULT *OrderInfo

func (p *GetOrderResp) GetOrder() (v *OrderInfo) {
	if !p.IsSetOrder() {
		return GetOrderResp_Order_DEFAULT
	}
	return p.Order
}

func (p *GetOrderResp) GetSeats() (v []*OrderSeatInfo) {
	return p.Seats
}
func (p *GetOrderResp) SetBaseResp(val *BaseResp) {
	p.BaseResp = val
}
func (p *GetOrderResp) SetOrder(val *OrderInfo) {
	p.Order = val
}
func (p *GetOrderResp) SetSeats(val []*OrderSeatInfo) {
	p.Seats = val
}

func (p *GetOrderResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetOrderResp) IsSetOrder() bool {
	return p.Order != nil
}

func (p *GetOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetOrderResp(%+v)", *p)
}

var fieldIDToName_GetOrderResp = map[int16]string{
	1: "base_resp",
	2: "order",
	3: "seats",
}

type SeatTypeRemain struct {
	SeatType  string  `thrift:"seat_type,1" frugal:"1,default,string" json:"seat_type"`
	Remaining int32   `thrift:"remaining,2" frugal:"2,default,i32" json:"remaining"`
	MinPrice  float64 `thrift:"min_price,3" frugal:"3,default,double" json:"min_price"`
}

func NewSeatTypeRemain() *SeatTypeRemain {
	return &SeatTypeRemain{}
}

func (p *SeatTypeRemain) InitDefault() {
}

func (p *SeatTypeRemain) GetSeatType() (v string) {
	return p.SeatType
}

func (p *SeatTypeRemain) GetRemaining() (v int32) {
	return p.Remaining
}

func (p *SeatTypeRemain) GetMinPrice() (v float64) {
	return p.MinPrice
}
func (p *SeatTypeRemain) SetSeatType(val string) {
	p.SeatType = val
}
func (p *SeatTypeRemain) SetRemaining(val int32) {
	p.Remaining = val
}
func (p *SeatTypeRemain) SetMinPrice(val float64) {
	p.MinPrice = val
}

func (p *SeatTypeRemain) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SeatTypeRemain(%+v)", *p)
}

var fieldIDToName_SeatTypeRemain = map[int16]string{
	1: "seat_type",
	2: "remaining",
	3: "min_price",
}

type GetTrainDetailReq struct {
	TrainId          string  `thrift:"train_id,1" frugal:"1,default,string" json:"train_id"`
	DepartureStation *string `thrift:"departure_station,2,optional" frugal:"2,optional,string" json:"departure_station,omitempty"`
	ArrivalStation   *string `thrift:"arrival_station,3,optional" frugal:"3,optional,string" json:"arrival_station,omitempty"`
}

func NewGetTrainDetailReq() *GetTrainDetailReq {
	return &GetTrainDetailReq{}
}

func (p *GetTrainDetailReq) InitDefault() {
}

func (p *GetTrainDetailReq) GetTrainId() (v string) {
	return p.TrainId
}

var GetTrainDetailReq_DepartureStation_DEFAULT string

func (p *GetTrainDetailReq) GetDepartureStation() (v string) {
	if !p.IsSetDepartureStation() {
		return GetTrainDetailReq_DepartureStation_DEFAULT
	}
	return *p.DepartureStation
}

var GetTrainDetailReq_ArrivalStation_DEFAULT string

func (p *GetTrainDetailReq) GetArrivalStation() (v string) {
	if !p.IsSetArrivalStation() {
		return GetTrainDetailReq_ArrivalStation_DEFAULT
	}
	return *p.ArrivalStation
}
func (p *GetTrainDetailReq) SetTrainId(val string) {
	p.TrainId = val
}
func (p *GetTrainDetailReq) SetDepartureStation(val *string) {
	p.DepartureStation = val
}
func (p *GetTrainDetailReq) SetArrivalStation(val *string) {
	p.ArrivalStation = val
}

func (p *GetTrainDetailReq) IsSetDepartureStation() bool {
	return p.DepartureStation != nil
}

func (p *GetTrainDetailReq) IsSetArrivalStation() bool {
	return p.ArrivalStation != nil
}

func (p *GetTrainDetailReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetTrainDetailReq(%+v)", *p)
}

var fieldIDToName_GetTrainDetailReq = map[int16]string{
	1: "train_id",
	2: "departure_station",
	3: "arrival_station",
}

type GetTrainDetailResp struct {
	BaseResp          *BaseResp         `thrift:"base_resp,1" frugal:"1,default,BaseResp" json:"base_resp"`
	TrainId           string            `thrift:"train_id,2" frugal:"2,default,string" json:"train_id"`
	TrainCode         string            `thrift:"train_code,3" frugal:"3,default,string" json:"train_code"`
	TrainType         string            `thrift:"train_type,4" frugal:"4,default,string" json:"train_type"`
	DepartureStation  string            `thrift:"departure_station,5" frugal:"5,default,string" json:"departure_station"`
	ArrivalStation    string            `thrift:"arrival_station,6" frugal:"6,default,string" json:"arrival_station"`
	DepartureTimeUnix int64             `thrift:"departure_time_unix,7" frugal:"7,default,i64" json:"departure_time_unix"`
	ArrivalTimeUnix   int64             `thrift:"arrival_time_unix,8" frugal:"8,default,i64" json:"arrival_time_unix"`
	RuntimeMinutes    int32             `thrift:"runtime_minutes,9" frugal:"9,default,i32" json:"runtime_minutes"`
	SeatTypes         []*SeatTypeRemain `thrift:"seat_types,10" frugal:"10,default,list<SeatTypeRemain>" json:"seat_types"`
}

func NewGetTrainDetailResp() *GetTrainDetailResp {
	return &GetTrainDetailResp{}
}

func (p *GetTrainDetailResp) InitDefault() {
}

var GetTrainDetailResp_BaseResp_DEFAULT *BaseResp

func (p *GetTrainDetailResp) GetBaseResp() (v *BaseResp) {
	if !p.IsSetBaseResp() {
		return GetTrainDetailResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *GetTrainDetailResp) GetTrainId() (v string) {
	return p.TrainId
}

func (p *GetTrainDetailResp) GetTrainCode() (v string) {
	return p.TrainCode
}

func (p *GetTrainDetailResp) GetTrainType() (v string) {
	return p.TrainType
}

func (p *GetTrainDetailResp) GetDepartureStation() (v string) {
	return p.DepartureStation
}

func (p *GetTrainDetailResp) GetArrivalStation() (v string) {
	return p.ArrivalStation
}

func (p *GetTrainDetailResp) GetDepartureTimeUnix() (v int64) {
	return p.DepartureTimeUnix
}

func (p *GetTrainDetailResp) GetArrivalTimeUnix() (v int64) {
	return p.ArrivalTimeUnix
}

func (p *GetTrainDetailResp) GetRuntimeMinutes() (v int32) {
	return p.RuntimeMinutes
}

func (p *GetTrainDetailResp) GetSeatTypes() (v []*SeatTypeRemain) {
	return p.SeatTypes
}
func (p *GetTrainDetailResp) SetBaseResp(val *BaseResp) {
	p.BaseResp = val
}
func (p *GetTrainDetailResp) SetTrainId(val string) {
	p.TrainId = val
}
func (p *GetTrainDetailResp) SetTrainCode(val string) {
	p.TrainCode = val
}
func (p *GetTrainDetailResp) SetTrainType(val string) {
	p.TrainType = val
}
func (p *GetTrainDetailResp) SetDepartureStation(val string) {
	p.DepartureStation = val
}
func (p *GetTrainDetailResp) SetArrivalStation(val string) {
	p.ArrivalStation = val
}
func (p *GetTrainDetailResp) SetDepartureTimeUnix(val int64) {
	p.DepartureTimeUnix = val
}
func (p *GetTrainDetailResp) SetArrivalTimeUnix(val int64) {
	p.ArrivalTimeUnix = val
}
func (p *GetTrainDetailResp) SetRuntimeMinutes(val int32) {
	p.RuntimeMinutes = val
}
func (p *GetTrainDetailResp) SetSeatTypes(val []*SeatTypeRemain) {
	p.SeatTypes = val
}

func (p *GetTrainDetailResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetTrainDetailResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetTrainDetailResp(%+v)", *p)
}

var fieldIDToName_GetTrainDetailResp = map[int16]string{
	1:  "base_resp",
	2:  "train_id",
	3:  "train_code",
	4:  "train_type",
	5:  "departure_station",
	6:  "arrival_station",
	7:  "departure_time_unix",
	8:  "arrival_time_unix",
	9:  "runtime_minutes",
	10: "seat_types",
}

type UserService interface {
	Register(ctx context.Context, req *RegisterReq) (r *RegisterResp, err error)

	Login(ctx context.Context, req *LoginReq) (r *LoginResp, err error)

	VerifyRealName(ctx context.Context, req *VerifyRealNameReq) (r *BaseResp, err error)

	GetUserInfo(ctx context.Context, req *GetUserInfoReq) (r *GetUserInfoResp, err error)

	GetTrainDetail(ctx context.Context, req *GetTrainDetailReq) (r *GetTrainDetailResp, err error)

	CreateOrder(ctx context.Context, req *CreateOrderReq) (r *CreateOrderResp, err error)

	PayOrder(ctx context.Context, req *PayOrderReq) (r *PayOrderResp, err error)

	ConfirmPay(ctx context.Context, req *ConfirmPayReq) (r *ConfirmPayResp, err error)

	ChangeOrder(ctx context.Context, req *ChangeOrderReq) (r *ChangeOrderResp, err error)

	CancelOrder(ctx context.Context, req *CancelOrderReq) (r *BaseResp, err error)

	RefundOrder(ctx context.Context, req *RefundOrderReq) (r *RefundOrderResp, err error)

	GetOrder(ctx context.Context, req *GetOrderReq) (r *GetOrderResp, err error)

	ListOrders(ctx context.Context, req *ListOrdersReq) (r *ListOrdersResp, err error)
}

type UserServiceRegisterArgs struct {
	Req *RegisterReq `thrift:"req,1" frugal:"1,default,RegisterReq" json:"req"`
}

func NewUserServiceRegisterArgs() *UserServiceRegisterArgs {
	return &UserServiceRegisterArgs{}
}

func (p *UserServiceRegisterArgs) InitDefault() {
}

var UserServiceRegisterArgs_Req_DEFAULT *RegisterReq

func (p *UserServiceRegisterArgs) GetReq() (v *RegisterReq) {
	if !p.IsSetReq() {
		return UserServiceRegisterArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceRegisterArgs) SetReq(val *RegisterReq) {
	p.Req = val
}

func (p *UserServiceRegisterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceRegisterArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRegisterArgs(%+v)", *p)
}

var fieldIDToName_UserServiceRegisterArgs = map[int16]string{
	1: "req",
}

type UserServiceRegisterResult struct {
	Success *RegisterResp `thrift:"success,0,optional" frugal:"0,optional,RegisterResp" json:"success,omitempty"`
}

func NewUserServiceRegisterResult() *UserServiceRegisterResult {
	return &UserServiceRegisterResult{}
}

func (p *UserServiceRegisterResult) InitDefault() {
}

var UserServiceRegisterResult_Success_DEFAULT *RegisterResp

func (p *UserServiceRegisterResult) GetSuccess() (v *RegisterResp) {
	if !p.IsSetSuccess() {
		return UserServiceRegisterResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceRegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*RegisterResp)
}

func (p *UserServiceRegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceRegisterResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRegisterResult(%+v)", *p)
}

var fieldIDToName_UserServiceRegisterResult = map[int16]string{
	0: "success",
}

type UserServiceLoginArgs struct {
	Req *LoginReq `thrift:"req,1" frugal:"1,default,LoginReq" json:"req"`
}

func NewUserServiceLoginArgs() *UserServiceLoginArgs {
	return &UserServiceLoginArgs{}
}

func (p *UserServiceLoginArgs) InitDefault() {
}

var UserServiceLoginArgs_Req_DEFAULT *LoginReq

func (p *UserServiceLoginArgs) GetReq() (v *LoginReq) {
	if !p.IsSetReq() {
		return UserServiceLoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceLoginArgs) SetReq(val *LoginReq) {
	p.Req = val
}

func (p *UserServiceLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLoginArgs(%+v)", *p)
}

var fieldIDToName_UserServiceLoginArgs = map[int16]string{
	1: "req",
}

type UserServiceLoginResult struct {
	Success *LoginResp `thrift:"success,0,optional" frugal:"0,optional,LoginResp" json:"success,omitempty"`
}

func NewUserServiceLoginResult() *UserServiceLoginResult {
	return &UserServiceLoginResult{}
}

func (p *UserServiceLoginResult) InitDefault() {
}

var UserServiceLoginResult_Success_DEFAULT *LoginResp

func (p *UserServiceLoginResult) GetSuccess() (v *LoginResp) {
	if !p.IsSetSuccess() {
		return UserServiceLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*LoginResp)
}

func (p *UserServiceLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLoginResult(%+v)", *p)
}

var fieldIDToName_UserServiceLoginResult = map[int16]string{
	0: "success",
}

type UserServiceVerifyRealNameArgs struct {
	Req *VerifyRealNameReq `thrift:"req,1" frugal:"1,default,VerifyRealNameReq" json:"req"`
}

func NewUserServiceVerifyRealNameArgs() *UserServiceVerifyRealNameArgs {
	return &UserServiceVerifyRealNameArgs{}
}

func (p *UserServiceVerifyRealNameArgs) InitDefault() {
}

var UserServiceVerifyRealNameArgs_Req_DEFAULT *VerifyRealNameReq

func (p *UserServiceVerifyRealNameArgs) GetReq() (v *VerifyRealNameReq) {
	if !p.IsSetReq() {
		return UserServiceVerifyRealNameArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceVerifyRealNameArgs) SetReq(val *VerifyRealNameReq) {
	p.Req = val
}

func (p *UserServiceVerifyRealNameArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceVerifyRealNameArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceVerifyRealNameArgs(%+v)", *p)
}

var fieldIDToName_UserServiceVerifyRealNameArgs = map[int16]string{
	1: "req",
}

type UserServiceVerifyRealNameResult struct {
	Success *BaseResp `thrift:"success,0,optional" frugal:"0,optional,BaseResp" json:"success,omitempty"`
}

func NewUserServiceVerifyRealNameResult() *UserServiceVerifyRealNameResult {
	return &UserServiceVerifyRealNameResult{}
}

func (p *UserServiceVerifyRealNameResult) InitDefault() {
}

var UserServiceVerifyRealNameResult_Success_DEFAULT *BaseResp

func (p *UserServiceVerifyRealNameResult) GetSuccess() (v *BaseResp) {
	if !p.IsSetSuccess() {
		return UserServiceVerifyRealNameResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceVerifyRealNameResult) SetSuccess(x interface{}) {
	p.Success = x.(*BaseResp)
}

func (p *UserServiceVerifyRealNameResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceVerifyRealNameResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceVerifyRealNameResult(%+v)", *p)
}

var fieldIDToName_UserServiceVerifyRealNameResult = map[int16]string{
	0: "success",
}

type UserServiceGetUserInfoArgs struct {
	Req *GetUserInfoReq `thrift:"req,1" frugal:"1,default,GetUserInfoReq" json:"req"`
}

func NewUserServiceGetUserInfoArgs() *UserServiceGetUserInfoArgs {
	return &UserServiceGetUserInfoArgs{}
}

func (p *UserServiceGetUserInfoArgs) InitDefault() {
}

var UserServiceGetUserInfoArgs_Req_DEFAULT *GetUserInfoReq

func (p *UserServiceGetUserInfoArgs) GetReq() (v *GetUserInfoReq) {
	if !p.IsSetReq() {
		return UserServiceGetUserInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceGetUserInfoArgs) SetReq(val *GetUserInfoReq) {
	p.Req = val
}

func (p *UserServiceGetUserInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceGetUserInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserInfoArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserInfoArgs = map[int16]string{
	1: "req",
}

type UserServiceGetUserInfoResult struct {
	Success *GetUserInfoResp `thrift:"success,0,optional" frugal:"0,optional,GetUserInfoResp" json:"success,omitempty"`
}

func NewUserServiceGetUserInfoResult() *UserServiceGetUserInfoResult {
	return &UserServiceGetUserInfoResult{}
}

func (p *UserServiceGetUserInfoResult) InitDefault() {
}

var UserServiceGetUserInfoResult_Success_DEFAULT *GetUserInfoResp

func (p *UserServiceGetUserInfoResult) GetSuccess() (v *GetUserInfoResp) {
	if !p.IsSetSuccess() {
		return UserServiceGetUserInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetUserInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUserInfoResp)
}

func (p *UserServiceGetUserInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetUserInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserInfoResult(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserInfoResult = map[int16]string{
	0: "success",
}

type UserServiceGetTrainDetailArgs struct {
	Req *GetTrainDetailReq `thrift:"req,1" frugal:"1,default,GetTrainDetailReq" json:"req"`
}

func NewUserServiceGetTrainDetailArgs() *UserServiceGetTrainDetailArgs {
	return &UserServiceGetTrainDetailArgs{}
}

func (p *UserServiceGetTrainDetailArgs) InitDefault() {
}

var UserServiceGetTrainDetailArgs_Req_DEFAULT *GetTrainDetailReq

func (p *UserServiceGetTrainDetailArgs) GetReq() (v *GetTrainDetailReq) {
	if !p.IsSetReq() {
		return UserServiceGetTrainDetailArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceGetTrainDetailArgs) SetReq(val *GetTrainDetailReq) {
	p.Req = val
}

func (p *UserServiceGetTrainDetailArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceGetTrainDetailArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetTrainDetailArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGetTrainDetailArgs = map[int16]string{
	1: "req",
}

type UserServiceGetTrainDetailResult struct {
	Success *GetTrainDetailResp `thrift:"success,0,optional" frugal:"0,optional,GetTrainDetailResp" json:"success,omitempty"`
}

func NewUserServiceGetTrainDetailResult() *UserServiceGetTrainDetailResult {
	return &UserServiceGetTrainDetailResult{}
}

func (p *UserServiceGetTrainDetailResult) InitDefault() {
}

var UserServiceGetTrainDetailResult_Success_DEFAULT *GetTrainDetailResp

func (p *UserServiceGetTrainDetailResult) GetSuccess() (v *GetTrainDetailResp) {
	if !p.IsSetSuccess() {
		return UserServiceGetTrainDetailResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetTrainDetailResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetTrainDetailResp)
}

func (p *UserServiceGetTrainDetailResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetTrainDetailResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetTrainDetailResult(%+v)", *p)
}

var fieldIDToName_UserServiceGetTrainDetailResult = map[int16]string{
	0: "success",
}

type UserServiceCreateOrderArgs struct {
	Req *CreateOrderReq `thrift:"req,1" frugal:"1,default,CreateOrderReq" json:"req"`
}

func NewUserServiceCreateOrderArgs() *UserServiceCreateOrderArgs {
	return &UserServiceCreateOrderArgs{}
}

func (p *UserServiceCreateOrderArgs) InitDefault() {
}

var UserServiceCreateOrderArgs_Req_DEFAULT *CreateOrderReq

func (p *UserServiceCreateOrderArgs) GetReq() (v *CreateOrderReq) {
	if !p.IsSetReq() {
		return UserServiceCreateOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceCreateOrderArgs) SetReq(val *CreateOrderReq) {
	p.Req = val
}

func (p *UserServiceCreateOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceCreateOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCreateOrderArgs(%+v)", *p)
}

var fieldIDToName_UserServiceCreateOrderArgs = map[int16]string{
	1: "req",
}

type UserServiceCreateOrderResult struct {
	Success *CreateOrderResp `thrift:"success,0,optional" frugal:"0,optional,CreateOrderResp" json:"success,omitempty"`
}

func NewUserServiceCreateOrderResult() *UserServiceCreateOrderResult {
	return &UserServiceCreateOrderResult{}
}

func (p *UserServiceCreateOrderResult) InitDefault() {
}

var UserServiceCreateOrderResult_Success_DEFAULT *CreateOrderResp

func (p *UserServiceCreateOrderResult) GetSuccess() (v *CreateOrderResp) {
	if !p.IsSetSuccess() {
		return UserServiceCreateOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceCreateOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateOrderResp)
}

func (p *UserServiceCreateOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceCreateOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCreateOrderResult(%+v)", *p)
}

var fieldIDToName_UserServiceCreateOrderResult = map[int16]string{
	0: "success",
}

type UserServicePayOrderArgs struct {
	Req *PayOrderReq `thrift:"req,1" frugal:"1,default,PayOrderReq" json:"req"`
}

func NewUserServicePayOrderArgs() *UserServicePayOrderArgs {
	return &UserServicePayOrderArgs{}
}

func (p *UserServicePayOrderArgs) InitDefault() {
}

var UserServicePayOrderArgs_Req_DEFAULT *PayOrderReq

func (p *UserServicePayOrderArgs) GetReq() (v *PayOrderReq) {
	if !p.IsSetReq() {
		return UserServicePayOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServicePayOrderArgs) SetReq(val *PayOrderReq) {
	p.Req = val
}

func (p *UserServicePayOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServicePayOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServicePayOrderArgs(%+v)", *p)
}

var fieldIDToName_UserServicePayOrderArgs = map[int16]string{
	1: "req",
}

type UserServicePayOrderResult struct {
	Success *PayOrderResp `thrift:"success,0,optional" frugal:"0,optional,PayOrderResp" json:"success,omitempty"`
}

func NewUserServicePayOrderResult() *UserServicePayOrderResult {
	return &UserServicePayOrderResult{}
}

func (p *UserServicePayOrderResult) InitDefault() {
}

var UserServicePayOrderResult_Success_DEFAULT *PayOrderResp

func (p *UserServicePayOrderResult) GetSuccess() (v *PayOrderResp) {
	if !p.IsSetSuccess() {
		return UserServicePayOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServicePayOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*PayOrderResp)
}

func (p *UserServicePayOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServicePayOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServicePayOrderResult(%+v)", *p)
}

var fieldIDToName_UserServicePayOrderResult = map[int16]string{
	0: "success",
}

type UserServiceConfirmPayArgs struct {
	Req *ConfirmPayReq `thrift:"req,1" frugal:"1,default,ConfirmPayReq" json:"req"`
}

func NewUserServiceConfirmPayArgs() *UserServiceConfirmPayArgs {
	return &UserServiceConfirmPayArgs{}
}

func (p *UserServiceConfirmPayArgs) InitDefault() {
}

var UserServiceConfirmPayArgs_Req_DEFAULT *ConfirmPayReq

func (p *UserServiceConfirmPayArgs) GetReq() (v *ConfirmPayReq) {
	if !p.IsSetReq() {
		return UserServiceConfirmPayArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceConfirmPayArgs) SetReq(val *ConfirmPayReq) {
	p.Req = val
}

func (p *UserServiceConfirmPayArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceConfirmPayArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceConfirmPayArgs(%+v)", *p)
}

var fieldIDToName_UserServiceConfirmPayArgs = map[int16]string{
	1: "req",
}

type UserServiceConfirmPayResult struct {
	Success *ConfirmPayResp `thrift:"success,0,optional" frugal:"0,optional,ConfirmPayResp" json:"success,omitempty"`
}

func NewUserServiceConfirmPayResult() *UserServiceConfirmPayResult {
	return &UserServiceConfirmPayResult{}
}

func (p *UserServiceConfirmPayResult) InitDefault() {
}

var UserServiceConfirmPayResult_Success_DEFAULT *ConfirmPayResp

func (p *UserServiceConfirmPayResult) GetSuccess() (v *ConfirmPayResp) {
	if !p.IsSetSuccess() {
		return UserServiceConfirmPayResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceConfirmPayResult) SetSuccess(x interface{}) {
	p.Success = x.(*ConfirmPayResp)
}

func (p *UserServiceConfirmPayResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceConfirmPayResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceConfirmPayResult(%+v)", *p)
}

var fieldIDToName_UserServiceConfirmPayResult = map[int16]string{
	0: "success",
}

type UserServiceChangeOrderArgs struct {
	Req *ChangeOrderReq `thrift:"req,1" frugal:"1,default,ChangeOrderReq" json:"req"`
}

func NewUserServiceChangeOrderArgs() *UserServiceChangeOrderArgs {
	return &UserServiceChangeOrderArgs{}
}

func (p *UserServiceChangeOrderArgs) InitDefault() {
}

var UserServiceChangeOrderArgs_Req_DEFAULT *ChangeOrderReq

func (p *UserServiceChangeOrderArgs) GetReq() (v *ChangeOrderReq) {
	if !p.IsSetReq() {
		return UserServiceChangeOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceChangeOrderArgs) SetReq(val *ChangeOrderReq) {
	p.Req = val
}

func (p *UserServiceChangeOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceChangeOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceChangeOrderArgs(%+v)", *p)
}

var fieldIDToName_UserServiceChangeOrderArgs = map[int16]string{
	1: "req",
}

type UserServiceChangeOrderResult struct {
	Success *ChangeOrderResp `thrift:"success,0,optional" frugal:"0,optional,ChangeOrderResp" json:"success,omitempty"`
}

func NewUserServiceChangeOrderResult() *UserServiceChangeOrderResult {
	return &UserServiceChangeOrderResult{}
}

func (p *UserServiceChangeOrderResult) InitDefault() {
}

var UserServiceChangeOrderResult_Success_DEFAULT *ChangeOrderResp

func (p *UserServiceChangeOrderResult) GetSuccess() (v *ChangeOrderResp) {
	if !p.IsSetSuccess() {
		return UserServiceChangeOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceChangeOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*ChangeOrderResp)
}

func (p *UserServiceChangeOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceChangeOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceChangeOrderResult(%+v)", *p)
}

var fieldIDToName_UserServiceChangeOrderResult = map[int16]string{
	0: "success",
}

type UserServiceCancelOrderArgs struct {
	Req *CancelOrderReq `thrift:"req,1" frugal:"1,default,CancelOrderReq" json:"req"`
}

func NewUserServiceCancelOrderArgs() *UserServiceCancelOrderArgs {
	return &UserServiceCancelOrderArgs{}
}

func (p *UserServiceCancelOrderArgs) InitDefault() {
}

var UserServiceCancelOrderArgs_Req_DEFAULT *CancelOrderReq

func (p *UserServiceCancelOrderArgs) GetReq() (v *CancelOrderReq) {
	if !p.IsSetReq() {
		return UserServiceCancelOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceCancelOrderArgs) SetReq(val *CancelOrderReq) {
	p.Req = val
}

func (p *UserServiceCancelOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceCancelOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCancelOrderArgs(%+v)", *p)
}

var fieldIDToName_UserServiceCancelOrderArgs = map[int16]string{
	1: "req",
}

type UserServiceCancelOrderResult struct {
	Success *BaseResp `thrift:"success,0,optional" frugal:"0,optional,BaseResp" json:"success,omitempty"`
}

func NewUserServiceCancelOrderResult() *UserServiceCancelOrderResult {
	return &UserServiceCancelOrderResult{}
}

func (p *UserServiceCancelOrderResult) InitDefault() {
}

var UserServiceCancelOrderResult_Success_DEFAULT *BaseResp

func (p *UserServiceCancelOrderResult) GetSuccess() (v *BaseResp) {
	if !p.IsSetSuccess() {
		return UserServiceCancelOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceCancelOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*BaseResp)
}

func (p *UserServiceCancelOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceCancelOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCancelOrderResult(%+v)", *p)
}

var fieldIDToName_UserServiceCancelOrderResult = map[int16]string{
	0: "success",
}

type UserServiceRefundOrderArgs struct {
	Req *RefundOrderReq `thrift:"req,1" frugal:"1,default,RefundOrderReq" json:"req"`
}

func NewUserServiceRefundOrderArgs() *UserServiceRefundOrderArgs {
	return &UserServiceRefundOrderArgs{}
}

func (p *UserServiceRefundOrderArgs) InitDefault() {
}

var UserServiceRefundOrderArgs_Req_DEFAULT *RefundOrderReq

func (p *UserServiceRefundOrderArgs) GetReq() (v *RefundOrderReq) {
	if !p.IsSetReq() {
		return UserServiceRefundOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceRefundOrderArgs) SetReq(val *RefundOrderReq) {
	p.Req = val
}

func (p *UserServiceRefundOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceRefundOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRefundOrderArgs(%+v)", *p)
}

var fieldIDToName_UserServiceRefundOrderArgs = map[int16]string{
	1: "req",
}

type UserServiceRefundOrderResult struct {
	Success *RefundOrderResp `thrift:"success,0,optional" frugal:"0,optional,RefundOrderResp" json:"success,omitempty"`
}

func NewUserServiceRefundOrderResult() *UserServiceRefundOrderResult {
	return &UserServiceRefundOrderResult{}
}

func (p *UserServiceRefundOrderResult) InitDefault() {
}

var UserServiceRefundOrderResult_Success_DEFAULT *RefundOrderResp

func (p *UserServiceRefundOrderResult) GetSuccess() (v *RefundOrderResp) {
	if !p.IsSetSuccess() {
		return UserServiceRefundOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceRefundOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*RefundOrderResp)
}

func (p *UserServiceRefundOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceRefundOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRefundOrderResult(%+v)", *p)
}

var fieldIDToName_UserServiceRefundOrderResult = map[int16]string{
	0: "success",
}

type UserServiceGetOrderArgs struct {
	Req *GetOrderReq `thrift:"req,1" frugal:"1,default,GetOrderReq" json:"req"`
}

func NewUserServiceGetOrderArgs() *UserServiceGetOrderArgs {
	return &UserServiceGetOrderArgs{}
}

func (p *UserServiceGetOrderArgs) InitDefault() {
}

var UserServiceGetOrderArgs_Req_DEFAULT *GetOrderReq

func (p *UserServiceGetOrderArgs) GetReq() (v *GetOrderReq) {
	if !p.IsSetReq() {
		return UserServiceGetOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceGetOrderArgs) SetReq(val *GetOrderReq) {
	p.Req = val
}

func (p *UserServiceGetOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceGetOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetOrderArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGetOrderArgs = map[int16]string{
	1: "req",
}

type UserServiceGetOrderResult struct {
	Success *GetOrderResp `thrift:"success,0,optional" frugal:"0,optional,GetOrderResp" json:"success,omitempty"`
}

func NewUserServiceGetOrderResult() *UserServiceGetOrderResult {
	return &UserServiceGetOrderResult{}
}

func (p *UserServiceGetOrderResult) InitDefault() {
}

var UserServiceGetOrderResult_Success_DEFAULT *GetOrderResp

func (p *UserServiceGetOrderResult) GetSuccess() (v *GetOrderResp) {
	if !p.IsSetSuccess() {
		return UserServiceGetOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetOrderResp)
}

func (p *UserServiceGetOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetOrderResult(%+v)", *p)
}

var fieldIDToName_UserServiceGetOrderResult = map[int16]string{
	0: "success",
}

type UserServiceListOrdersArgs struct {
	Req *ListOrdersReq `thrift:"req,1" frugal:"1,default,ListOrdersReq" json:"req"`
}

func NewUserServiceListOrdersArgs() *UserServiceListOrdersArgs {
	return &UserServiceListOrdersArgs{}
}

func (p *UserServiceListOrdersArgs) InitDefault() {
}

var UserServiceListOrdersArgs_Req_DEFAULT *ListOrdersReq

func (p *UserServiceListOrdersArgs) GetReq() (v *ListOrdersReq) {
	if !p.IsSetReq() {
		return UserServiceListOrdersArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceListOrdersArgs) SetReq(val *ListOrdersReq) {
	p.Req = val
}

func (p *UserServiceListOrdersArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceListOrdersArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceListOrdersArgs(%+v)", *p)
}

var fieldIDToName_UserServiceListOrdersArgs = map[int16]string{
	1: "req",
}

type UserServiceListOrdersResult struct {
	Success *ListOrdersResp `thrift:"success,0,optional" frugal:"0,optional,ListOrdersResp" json:"success,omitempty"`
}

func NewUserServiceListOrdersResult() *UserServiceListOrdersResult {
	return &UserServiceListOrdersResult{}
}

func (p *UserServiceListOrdersResult) InitDefault() {
}

var UserServiceListOrdersResult_Success_DEFAULT *ListOrdersResp

func (p *UserServiceListOrdersResult) GetSuccess() (v *ListOrdersResp) {
	if !p.IsSetSuccess() {
		return UserServiceListOrdersResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceListOrdersResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListOrdersResp)
}

func (p *UserServiceListOrdersResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceListOrdersResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceListOrdersResult(%+v)", *p)
}

var fieldIDToName_UserServiceListOrdersResult = map[int16]string{
	0: "success",
}
