// Code generated by Kitex v0.15.4. DO NOT EDIT.

package userservice

import (
	"context"
	common "example_shop/kitex_gen/common"
	userapi "example_shop/kitex_gen/userapi"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Register(ctx context.Context, req *userapi.RegisterReq, callOptions ...callopt.Option) (r *userapi.RegisterResp, err error)
	Login(ctx context.Context, req *userapi.LoginReq, callOptions ...callopt.Option) (r *userapi.LoginResp, err error)
	VerifyRealName(ctx context.Context, req *userapi.VerifyRealNameReq, callOptions ...callopt.Option) (r *common.BaseResp, err error)
	GetUserInfo(ctx context.Context, req *userapi.GetUserInfoReq, callOptions ...callopt.Option) (r *userapi.GetUserInfoResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) Register(ctx context.Context, req *userapi.RegisterReq, callOptions ...callopt.Option) (r *userapi.RegisterResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Register(ctx, req)
}

func (p *kUserServiceClient) Login(ctx context.Context, req *userapi.LoginReq, callOptions ...callopt.Option) (r *userapi.LoginResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, req)
}

func (p *kUserServiceClient) VerifyRealName(ctx context.Context, req *userapi.VerifyRealNameReq, callOptions ...callopt.Option) (r *common.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.VerifyRealName(ctx, req)
}

func (p *kUserServiceClient) GetUserInfo(ctx context.Context, req *userapi.GetUserInfoReq, callOptions ...callopt.Option) (r *userapi.GetUserInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserInfo(ctx, req)
}
