// Code generated by Kitex v0.15.4. DO NOT EDIT.

package userservice

import (
	"context"
	"errors"
	common "example_shop/kitex_gen/common"
	userapi "example_shop/kitex_gen/userapi"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Register": kitex.NewMethodInfo(
		registerHandler,
		newUserServiceRegisterArgs,
		newUserServiceRegisterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Login": kitex.NewMethodInfo(
		loginHandler,
		newUserServiceLoginArgs,
		newUserServiceLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"VerifyRealName": kitex.NewMethodInfo(
		verifyRealNameHandler,
		newUserServiceVerifyRealNameArgs,
		newUserServiceVerifyRealNameResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUserInfo": kitex.NewMethodInfo(
		getUserInfoHandler,
		newUserServiceGetUserInfoArgs,
		newUserServiceGetUserInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	userServiceServiceInfo                = NewServiceInfo()
	userServiceServiceInfoForClient       = NewServiceInfoForClient()
	userServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return userServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "UserService"
	handlerType := (*userapi.UserService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "userapi",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.4",
		Extra:           extra,
	}
	return svcInfo
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*userapi.UserServiceRegisterArgs)
	realResult := result.(*userapi.UserServiceRegisterResult)
	success, err := handler.(userapi.UserService).Register(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceRegisterArgs() interface{} {
	return userapi.NewUserServiceRegisterArgs()
}

func newUserServiceRegisterResult() interface{} {
	return userapi.NewUserServiceRegisterResult()
}

func loginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*userapi.UserServiceLoginArgs)
	realResult := result.(*userapi.UserServiceLoginResult)
	success, err := handler.(userapi.UserService).Login(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceLoginArgs() interface{} {
	return userapi.NewUserServiceLoginArgs()
}

func newUserServiceLoginResult() interface{} {
	return userapi.NewUserServiceLoginResult()
}

func verifyRealNameHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*userapi.UserServiceVerifyRealNameArgs)
	realResult := result.(*userapi.UserServiceVerifyRealNameResult)
	success, err := handler.(userapi.UserService).VerifyRealName(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceVerifyRealNameArgs() interface{} {
	return userapi.NewUserServiceVerifyRealNameArgs()
}

func newUserServiceVerifyRealNameResult() interface{} {
	return userapi.NewUserServiceVerifyRealNameResult()
}

func getUserInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*userapi.UserServiceGetUserInfoArgs)
	realResult := result.(*userapi.UserServiceGetUserInfoResult)
	success, err := handler.(userapi.UserService).GetUserInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetUserInfoArgs() interface{} {
	return userapi.NewUserServiceGetUserInfoArgs()
}

func newUserServiceGetUserInfoResult() interface{} {
	return userapi.NewUserServiceGetUserInfoResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Register(ctx context.Context, req *userapi.RegisterReq) (r *userapi.RegisterResp, err error) {
	var _args userapi.UserServiceRegisterArgs
	_args.Req = req
	var _result userapi.UserServiceRegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Login(ctx context.Context, req *userapi.LoginReq) (r *userapi.LoginResp, err error) {
	var _args userapi.UserServiceLoginArgs
	_args.Req = req
	var _result userapi.UserServiceLoginResult
	if err = p.c.Call(ctx, "Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) VerifyRealName(ctx context.Context, req *userapi.VerifyRealNameReq) (r *common.BaseResp, err error) {
	var _args userapi.UserServiceVerifyRealNameArgs
	_args.Req = req
	var _result userapi.UserServiceVerifyRealNameResult
	if err = p.c.Call(ctx, "VerifyRealName", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserInfo(ctx context.Context, req *userapi.GetUserInfoReq) (r *userapi.GetUserInfoResp, err error) {
	var _args userapi.UserServiceGetUserInfoArgs
	_args.Req = req
	var _result userapi.UserServiceGetUserInfoResult
	if err = p.c.Call(ctx, "GetUserInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
